<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Equipment_ucMenu_rptLevel1_lnkLink1_3</name>
   <tag></tag>
   <elementGuidId>fdca678b-082b-43eb-adfe-40cefe785440</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucMenu_rptLevel1_lnkLink1_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Parts')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Parts&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2d665373-a233-41cd-a4a6-4df21a84c024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucMenu_rptLevel1_lnkLink1_3</value>
      <webElementGuid>8b2934ca-a984-47e1-a767-85701940b873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main_menu parts_icon active</value>
      <webElementGuid>dc1d37dd-0cf9-49ef-9772-11378d4e0732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../Parts/parts.aspx?PageTitle=Parts Data</value>
      <webElementGuid>09881535-7a68-4be2-ab93-f5f84e12328e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Parts</value>
      <webElementGuid>0d4fc187-2d9a-43d9-ac57-544af51eecab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucMenu_rptLevel1_lnkLink1_3&quot;)</value>
      <webElementGuid>acdf4466-c5f1-408d-b13d-8d9cd3521b40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucMenu_rptLevel1_lnkLink1_3']</value>
      <webElementGuid>cc076254-ed7c-48b2-9a67-6fd9a4a38dd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='ucMenu_rptLevel1_l1_3']/a</value>
      <webElementGuid>9069fd67-ddc2-4f63-9715-e5df5bba6e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Parts')]</value>
      <webElementGuid>fa72e1f4-019b-4738-9026-3aeffa85b83e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Equipment'])[1]/following::a[1]</value>
      <webElementGuid>e8dd1ed7-2a51-4508-9d68-9f804870c1bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle'])[1]/following::a[2]</value>
      <webElementGuid>df675a1d-0ebd-410f-b505-cf312c025cb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export Data'])[1]/preceding::a[1]</value>
      <webElementGuid>c63c3402-fe52-4f7d-a003-8b0c8fc76a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Catalogs'])[1]/preceding::a[2]</value>
      <webElementGuid>9667e972-070b-4224-8440-a44a6ce285ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Parts']/parent::*</value>
      <webElementGuid>aad7d74e-abed-48c3-9b1f-3133bd3ecd36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '../Parts/parts.aspx?PageTitle=Parts Data')]</value>
      <webElementGuid>57e2e75d-cdea-4ac0-b860-c064776f996d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>96680cd4-b87b-49fc-b306-fcff490afbe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucMenu_rptLevel1_lnkLink1_3' and @href = '../Parts/parts.aspx?PageTitle=Parts Data' and (text() = 'Parts' or . = 'Parts')]</value>
      <webElementGuid>10da9662-d214-47ce-8118-f0652a39a380</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
