<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Enter Long Description (DES) first_d_7e7635</name>
   <tag></tag>
   <elementGuidId>b2a6b10c-121f-4730-8b7e-d167321102ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drpNotesType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='drpNotesType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#drpNotesType</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2b9d8b06-0f66-4678-895e-0a99d173471f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_select</value>
      <webElementGuid>b4293732-7a20-4997-be06-44aeaf8c3765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drpNotesType</value>
      <webElementGuid>59e17071-c277-4c83-a734-47abd304de94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;--Select-->AAIA Part Type Description-80(DEF)Application Summary - 2000(ASM)Application Summary - 240(APS)Associated Comments - 2000(ASC)Caption - 240(CAP)Caution Note - 500(CAU)Features and Benefits - 240(FAB)Informational Note - 500(INF)Key Search Word - 80(KSW)Key Search Words - 2000(KEY)Market Type-1(MTP)Marketing Description - 2000(MKT)Product Description - Abbreviated - 12(ABR)Product Description - Extended-240(EXT)Product Description - Invoice - 40(INV)Product Description - Label - 80(LAB)Product Description - Long - 80(DES)Product Description - SEO - 200(TLE)Product Description - Short - 20(SHO)Shipping Restrictions - 2000(SHP)Slang Description - 2000(SLA)Slang Description - 80(SLD)Technical Tips - 240(TTP)Technical Tips - Marketing Description - 2000(TTD)Transcription - 2000(TRA)UN/SPSC Description - 80(UNS)VMRS Description-80(VMR)</value>
      <webElementGuid>911691c4-6ebf-40d8-bfe8-21d7eee84b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drpNotesType&quot;)</value>
      <webElementGuid>75d3c1c5-a667-4acb-aa1c-9575fea7cb73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='drpNotesType']</value>
      <webElementGuid>252f877c-cac4-4f86-b8f9-5aefb12db262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div[2]/div[2]/div[3]/div[2]/select</value>
      <webElementGuid>906a8ea4-9589-420d-808d-ca8d42e56db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter Long Description (DES) first'])[1]/following::select[1]</value>
      <webElementGuid>8cd1aaab-e1df-40db-86fd-888098a11777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::select[1]</value>
      <webElementGuid>51ee32fe-f23e-4846-be71-0b47a43e144a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description Sequence'])[1]/preceding::select[1]</value>
      <webElementGuid>84ea597b-3e43-471f-9a0b-83cacc5e68ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language (Code)'])[1]/preceding::select[1]</value>
      <webElementGuid>f5359b15-801b-49a1-a857-e740b4250f63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>a5e2dd33-626e-4f3a-966a-a429beb95ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'drpNotesType' and (text() = '&lt;--Select-->AAIA Part Type Description-80(DEF)Application Summary - 2000(ASM)Application Summary - 240(APS)Associated Comments - 2000(ASC)Caption - 240(CAP)Caution Note - 500(CAU)Features and Benefits - 240(FAB)Informational Note - 500(INF)Key Search Word - 80(KSW)Key Search Words - 2000(KEY)Market Type-1(MTP)Marketing Description - 2000(MKT)Product Description - Abbreviated - 12(ABR)Product Description - Extended-240(EXT)Product Description - Invoice - 40(INV)Product Description - Label - 80(LAB)Product Description - Long - 80(DES)Product Description - SEO - 200(TLE)Product Description - Short - 20(SHO)Shipping Restrictions - 2000(SHP)Slang Description - 2000(SLA)Slang Description - 80(SLD)Technical Tips - 240(TTP)Technical Tips - Marketing Description - 2000(TTD)Transcription - 2000(TRA)UN/SPSC Description - 80(UNS)VMRS Description-80(VMR)' or . = '&lt;--Select-->AAIA Part Type Description-80(DEF)Application Summary - 2000(ASM)Application Summary - 240(APS)Associated Comments - 2000(ASC)Caption - 240(CAP)Caution Note - 500(CAU)Features and Benefits - 240(FAB)Informational Note - 500(INF)Key Search Word - 80(KSW)Key Search Words - 2000(KEY)Market Type-1(MTP)Marketing Description - 2000(MKT)Product Description - Abbreviated - 12(ABR)Product Description - Extended-240(EXT)Product Description - Invoice - 40(INV)Product Description - Label - 80(LAB)Product Description - Long - 80(DES)Product Description - SEO - 200(TLE)Product Description - Short - 20(SHO)Shipping Restrictions - 2000(SHP)Slang Description - 2000(SLA)Slang Description - 80(SLD)Technical Tips - 240(TTP)Technical Tips - Marketing Description - 2000(TTD)Transcription - 2000(TRA)UN/SPSC Description - 80(UNS)VMRS Description-80(VMR)')]</value>
      <webElementGuid>5091287c-5b27-4d79-97bf-d7122bbb4890</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
