<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Select_note-codable</name>
   <tag></tag>
   <elementGuidId>121d24df-6abe-4d7a-8a7d-cde8458f2283</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.note-codable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='piespages']/div[2]/div[2]/div[4]/div/div[3]/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>textarea >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3d1c7aca-ad2a-4324-81ba-bc743ef7bf2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>note-codable</value>
      <webElementGuid>f5e528ea-d185-45a2-8487-6a857f425343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a5507058-e5be-4798-aa70-5d7ebd49a358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;piespages&quot;)/div[@class=&quot;parts_main_div&quot;]/div[@class=&quot;dvSearchPart&quot;]/div[@class=&quot;field_label_full mar_bottom_0&quot;]/div[@class=&quot;note-editor note-frame codeview&quot;]/div[@class=&quot;note-editing-area&quot;]/textarea[@class=&quot;note-codable&quot;]</value>
      <webElementGuid>97890c8e-10e3-4628-b8bb-ca3b78a60aa2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div[2]/div[2]/div[4]/div/div[3]/textarea</value>
      <webElementGuid>e22931f7-9eb5-4ed5-b31a-f0886d86b453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/textarea</value>
      <webElementGuid>fea03460-be6c-4d8c-894c-f65947c5a7db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
