<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Recommended_txtHazMaterialCodeQualifier</name>
   <tag></tag>
   <elementGuidId>1c82d034-c622-4986-9001-9b2e21e017a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtHazMaterialCodeQualifier</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtHazMaterialCodeQualifier']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtHazMaterialCodeQualifier</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d167b619-6c52-48ce-b888-fe38936af71d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>abdd783b-a9bc-48f8-a640-bfb4cd497df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtHazMaterialCodeQualifier</value>
      <webElementGuid>e0c3b152-2c25-49fe-96d6-12966d2bbeed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_input</value>
      <webElementGuid>f2308fb4-0764-4ae3-ba06-93eb8db29271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>495fa883-543d-4559-a55c-451ce6247bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>PartnoValidate(this)</value>
      <webElementGuid>894efd3a-2fd9-4ad1-97c5-a032294e0730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtHazMaterialCodeQualifier&quot;)</value>
      <webElementGuid>7cd9af14-9613-4a52-9597-4b8ab9d3dcca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtHazMaterialCodeQualifier']</value>
      <webElementGuid>85932232-300d-4c17-9fe2-65ed5be2db5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div[2]/div[2]/div[2]/div[14]/input</value>
      <webElementGuid>ee825372-fa2e-4d1d-a248-56fc2662ba1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/input</value>
      <webElementGuid>8aa2c65d-0b1f-41ad-a1f2-fafd9787f533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtHazMaterialCodeQualifier']</value>
      <webElementGuid>ca943504-eea2-46de-b1e6-9812fbc7ffca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
