<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Recommended_txtShippingName</name>
   <tag></tag>
   <elementGuidId>39b38a86-fa0b-4de0-bbdd-a6ce55446b3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtShippingName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtShippingName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtShippingName</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f2eedf42-e24c-4a28-8c75-f805063da8b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6d4e2010-1919-4c86-bfa4-0310f7ac3a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtShippingName</value>
      <webElementGuid>67141284-bd77-488a-8e9a-0da9f6577794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_input</value>
      <webElementGuid>1985e675-a71c-4bd0-899e-f08773838f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>textmode</name>
      <type>Main</type>
      <value>MultiLine</value>
      <webElementGuid>a203948d-de1d-4c17-a5af-29f31ccdc0f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>PartnoValidate(this)</value>
      <webElementGuid>a1a554fe-a095-47ba-9925-717fef6e785c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>260</value>
      <webElementGuid>092ab60b-55b1-4ccd-bfac-eb310f1253d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtShippingName&quot;)</value>
      <webElementGuid>f83aff3f-b69b-404f-b90f-98ec870fc2e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtShippingName']</value>
      <webElementGuid>4da7173a-6dde-41e3-a246-afd3c667f1a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div[2]/div[2]/div[2]/div[4]/input</value>
      <webElementGuid>8b2ee404-0afc-429d-a311-4abebcd3089a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/input</value>
      <webElementGuid>20a77c23-90eb-4e2f-acec-59a725439c61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtShippingName']</value>
      <webElementGuid>c5e76f54-8aee-4f5b-a202-be9846caa675</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
