<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Recommended_txtHazMaterialDesc</name>
   <tag></tag>
   <elementGuidId>c09afe81-68fb-46f8-bc8a-92211fb557ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtHazMaterialDesc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtHazMaterialDesc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtHazMaterialDesc</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a53f9f72-220a-4d20-82ce-d23cee8e6d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dbd4ce30-d0e4-435c-92a7-0c8aff7d994d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtHazMaterialDesc</value>
      <webElementGuid>dfc25e6c-34fc-4df4-b957-7ba529275850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_input</value>
      <webElementGuid>3fba92ee-d0d8-44af-b599-c9f3130a55b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>textmode</name>
      <type>Main</type>
      <value>MultiLine</value>
      <webElementGuid>cc303a7e-5f8a-4dce-8877-c6cebd1e4fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>24502a1d-10e2-4321-9204-eef76320ec47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtHazMaterialDesc&quot;)</value>
      <webElementGuid>e500d130-b3a6-4f61-a3c0-b182999037a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtHazMaterialDesc']</value>
      <webElementGuid>887605b6-f1f9-4d19-a093-707adf1abb5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div[2]/div[2]/div[2]/div[5]/input</value>
      <webElementGuid>cb2e20b3-6160-476e-b1d7-2f6f19bd9dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/input</value>
      <webElementGuid>63d95548-3159-4a34-bdb4-bfdcb8542caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtHazMaterialDesc']</value>
      <webElementGuid>4d07ca0d-6c8d-4781-95c1-1dd364a6e917</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
