<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_WHMIS Free Text_txtWHMISFree</name>
   <tag></tag>
   <elementGuidId>69e67889-5509-4305-96a6-25fa7ee1194d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtWHMISFree</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtWHMISFree']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtWHMISFree</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ac6f000-4a39-4424-9cef-9b658e442d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>41e7ed66-6434-4975-a55d-556c187e5678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtWHMISFree</value>
      <webElementGuid>940a56b0-dc80-4210-a419-96ca74ff2e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_input</value>
      <webElementGuid>c677a671-8c2f-4916-b580-fd3590eb33b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>textmode</name>
      <type>Main</type>
      <value>MultiLine</value>
      <webElementGuid>44d46b2d-102b-40bc-a98b-56bfe6953046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>e241654f-bcf1-4f4d-a4a2-c543786d3d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>PartnoValidate(this)</value>
      <webElementGuid>e954b1c9-4c2d-4648-ac75-3a8d1a51a227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtWHMISFree&quot;)</value>
      <webElementGuid>4bd715a0-dfaa-4f44-a877-39bda7e3b966</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtWHMISFree']</value>
      <webElementGuid>3a4ffbc7-1c76-436f-bb89-ae46eed94c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div[2]/div[2]/div[2]/div[13]/input</value>
      <webElementGuid>9763bb89-13c3-4827-ba2b-af3cf4ee4846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/input</value>
      <webElementGuid>cf0ef0df-d497-4031-9621-b721eb1f992b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtWHMISFree']</value>
      <webElementGuid>55ab5204-1952-41cb-a392-62f49f954063</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
