<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description_txtDescription</name>
   <tag></tag>
   <elementGuidId>2ca27fd3-e05d-4ea6-937b-194f31e35c3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtDescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtDescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtDescription</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a3c242d-7844-4d17-9223-eaff04a85af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1aa798ec-714a-4b1f-8689-a4fd8560dd55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDescription</value>
      <webElementGuid>5f4c986e-a22a-4703-bb87-7b0db14fb2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_input</value>
      <webElementGuid>af20a33c-a7da-4d94-b990-c54f4b9256c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>textmode</name>
      <type>Main</type>
      <value>MultiLine</value>
      <webElementGuid>66b8108b-2964-4815-852e-0f27c2add165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>90615886-71be-499e-90fe-7765b1f01709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDescription&quot;)</value>
      <webElementGuid>d96c3435-d51e-4679-adb8-962b81387641</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtDescription']</value>
      <webElementGuid>0de3d8f4-2645-4bcd-82b5-9116cfe6e866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div[2]/div[2]/div[2]/div[20]/input</value>
      <webElementGuid>6d20dfa6-5024-4d09-873a-7a33ec2617d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/input</value>
      <webElementGuid>7db22e16-6cf2-4928-8676-500f91c61e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtDescription']</value>
      <webElementGuid>dc8ee0de-12ff-49a6-acb0-8f1e83a01c7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
