<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hazardous Placard Notation_txtHazPlac_1b9ab4</name>
   <tag></tag>
   <elementGuidId>8d96b342-53a2-4cd7-a986-c090e81aadb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtHazPlacardNotation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtHazPlacardNotation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtHazPlacardNotation</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>44838d14-d635-4b5b-bc19-c2a18446c5b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtHazPlacardNotation</value>
      <webElementGuid>cc6cd56e-8d87-40fc-8a6f-ff2df3aecbc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_input</value>
      <webElementGuid>f7b6641f-6bd0-4176-85df-4b85712ee931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>textmode</name>
      <type>Main</type>
      <value>MultiLine</value>
      <webElementGuid>efbc1260-5283-443f-8d0c-98197c0c16b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>c9391152-a689-43cd-a179-5edd6d417415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>PartnoValidate(this)</value>
      <webElementGuid>c8c5e6d6-9c73-49ba-a412-0b1b0043a6bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtHazPlacardNotation&quot;)</value>
      <webElementGuid>d3d83ada-5b38-4a7a-98ad-a28b06f3a664</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtHazPlacardNotation']</value>
      <webElementGuid>cd34cfb3-c9a5-4e56-be3b-4446e8ae58be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div[2]/div[2]/div[2]/div[12]/input</value>
      <webElementGuid>e16d16a4-9740-4dd8-b166-d6dff6d01083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/input</value>
      <webElementGuid>80e47c18-72a3-4185-a434-d9ba6b917cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtHazPlacardNotation']</value>
      <webElementGuid>d370ec33-c4a0-4dea-9ab1-da10c1809ecf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
