<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__drpRegulated</name>
   <tag></tag>
   <elementGuidId>41293244-76de-4e85-a065-6cdeb7f9565c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drpRegulated</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='drpRegulated']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#drpRegulated</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c4ea4f1f-9bc9-4457-adf6-fe03dd0bdce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drpRegulated</value>
      <webElementGuid>2df4043c-72c2-40e9-856c-c7efbe677535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_select</value>
      <webElementGuid>d0646d4c-4f73-4b9a-9486-e8b9cd27d873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
              Yes
              No
          </value>
      <webElementGuid>8c68ecc2-902b-406c-ae1c-ea7370c80de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drpRegulated&quot;)</value>
      <webElementGuid>cb42392f-2bfe-4258-b6cd-7323b2f98569</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='drpRegulated']</value>
      <webElementGuid>f4963f90-608f-4799-a3ac-3624c6bb21e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div[2]/div[2]/div[2]/div[10]/select</value>
      <webElementGuid>227dba87-9263-4925-bd1e-f2a1bcdea367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[12]/following::select[1]</value>
      <webElementGuid>24b160ed-1906-4540-b9ea-24e21519df33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WHMIS Code'])[1]/preceding::select[1]</value>
      <webElementGuid>d37cc091-09f2-45d7-b06f-3657c818f881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hazardous Placard Notation'])[1]/preceding::select[2]</value>
      <webElementGuid>d5de407a-586b-48a3-ba0c-88fea6ad1b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/select</value>
      <webElementGuid>b1235e80-8d49-4bcb-b4f2-9fc060be4498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'drpRegulated' and (text() = '
              Yes
              No
          ' or . = '
              Yes
              No
          ')]</value>
      <webElementGuid>3936c715-f5f4-4589-b3dd-a73d27f6fd12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
