<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Language_drpLanguageCode</name>
   <tag></tag>
   <elementGuidId>e4268687-8509-4eed-87d1-c50db7d51a9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drpLanguageCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='drpLanguageCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#drpLanguageCode</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7bdc97b0-6e17-4473-bc03-ed5df69483e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drpLanguageCode</value>
      <webElementGuid>028cf58a-0ea7-45f6-8369-ca5efd0ab020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_select</value>
      <webElementGuid>c5bf1139-f94f-4d81-8350-9052d3c57667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;----Select---->Cabo Verde (CV)English (EN)French (FR)German (DE)Italian (IT)Japanese (JA)Portuguese (PT)Spanish (ES)</value>
      <webElementGuid>b0570b75-cb00-43c8-be4b-f30653466f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drpLanguageCode&quot;)</value>
      <webElementGuid>e2cb7f55-4c9d-4a7a-981b-5df66e9c3600</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='drpLanguageCode']</value>
      <webElementGuid>2d939f0a-6957-47b7-91e0-5674f221e4b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div[2]/div[2]/div[2]/div[9]/select</value>
      <webElementGuid>8dd6dbe3-c3e0-459b-a981-e5958bbf9227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language'])[1]/following::select[1]</value>
      <webElementGuid>6e3f3eca-7698-465e-94af-e6478ad9f854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/following::select[2]</value>
      <webElementGuid>d99d007b-d314-43b7-b8d1-bb7cdc1336ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[12]/preceding::select[1]</value>
      <webElementGuid>dbf67bbc-58d5-4f34-b598-1431ab4f628a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/select</value>
      <webElementGuid>d8f36183-3508-4e81-b629-99fa19f51a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'drpLanguageCode' and (text() = '&lt;----Select---->Cabo Verde (CV)English (EN)French (FR)German (DE)Italian (IT)Japanese (JA)Portuguese (PT)Spanish (ES)' or . = '&lt;----Select---->Cabo Verde (CV)English (EN)French (FR)German (DE)Italian (IT)Japanese (JA)Portuguese (PT)Spanish (ES)')]</value>
      <webElementGuid>23fc4c53-01c0-4478-b66b-fa9589dfd39c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
