<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__drpBulk</name>
   <tag></tag>
   <elementGuidId>82409bcd-7c35-43e2-af2b-0e535279f652</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drpBulk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='drpBulk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#drpBulk</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>92f2ff87-b9c1-4b6f-9556-c03ff04f960a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drpBulk</value>
      <webElementGuid>74e10e84-b75d-4d7b-851c-6abf3742edc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_select</value>
      <webElementGuid>f49b4e7b-1cb9-43b8-a0e6-5bffb57230dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;----Select---->Bulk (B)Non-Bulk (N)</value>
      <webElementGuid>752ea96f-ce15-4566-a2d6-594974b34962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drpBulk&quot;)</value>
      <webElementGuid>acf9d70d-93ff-4553-a650-c3ec4e19bc93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='drpBulk']</value>
      <webElementGuid>05f84983-406e-462d-8c3e-d3ff2c082d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div[2]/div[2]/div[2]/div[3]/select</value>
      <webElementGuid>d12e99e5-ab3d-41d6-a9e3-85ac170947e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/following::select[1]</value>
      <webElementGuid>7ab6bdc2-9b36-4f28-a64d-eaf66ecf8698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>4543a705-8a0b-4b53-919e-40b72008aedf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'drpBulk' and (text() = '&lt;----Select---->Bulk (B)Non-Bulk (N)' or . = '&lt;----Select---->Bulk (B)Non-Bulk (N)')]</value>
      <webElementGuid>d6ac9209-646d-46f0-9900-d18731270d39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
