<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Recommended_drpHazardousMaterial</name>
   <tag></tag>
   <elementGuidId>5150c6ee-af50-434c-8057-dee73af9fabd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drpHazardousMaterial</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='drpHazardousMaterial']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#drpHazardousMaterial</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d956e593-8fd1-4b2b-b039-5154d081dc70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drpHazardousMaterial</value>
      <webElementGuid>62fab274-be30-431f-bba9-05edfe3ec186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_select</value>
      <webElementGuid>24114432-1352-48cf-947c-e8e9805f9649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;----Select---->Corrosives (8)Explosives (1)Flammable Combustion (3)Flammable Solids (4)Gases (2)Misc. Haz Material (9)Ozidizing Substance (5)Radioactive Material (7)Toxic Substances (6)</value>
      <webElementGuid>0fd7ddb6-115b-4345-b7de-c350ccec78ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drpHazardousMaterial&quot;)</value>
      <webElementGuid>08610b9e-a926-465d-a13a-cf4ec0b0e954</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='drpHazardousMaterial']</value>
      <webElementGuid>046db2a4-4883-40f4-8884-b6cbc3652d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div[2]/div[2]/div[2]/div[18]/select</value>
      <webElementGuid>22450841-42a8-4099-b2a6-23ea97c25985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recommended.'])[8]/following::select[1]</value>
      <webElementGuid>87697bdb-dfde-4e59-87ba-9819213f45c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outer Package Label'])[1]/preceding::select[1]</value>
      <webElementGuid>1ada081a-9e1e-4522-9819-8ba5a86d3623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::select[1]</value>
      <webElementGuid>e09ec73b-c194-4ffc-bc32-372b3ca04dc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/select</value>
      <webElementGuid>808cac28-0410-42f6-ba96-2d947894c4b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'drpHazardousMaterial' and (text() = '&lt;----Select---->Corrosives (8)Explosives (1)Flammable Combustion (3)Flammable Solids (4)Gases (2)Misc. Haz Material (9)Ozidizing Substance (5)Radioactive Material (7)Toxic Substances (6)' or . = '&lt;----Select---->Corrosives (8)Explosives (1)Flammable Combustion (3)Flammable Solids (4)Gases (2)Misc. Haz Material (9)Ozidizing Substance (5)Radioactive Material (7)Toxic Substances (6)')]</value>
      <webElementGuid>eb76e1dc-cb39-4f3f-994f-b0f4174da6d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
