<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__drpTransportMethod</name>
   <tag></tag>
   <elementGuidId>b41f05cd-382d-4047-98b0-b26ec9f68427</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drpTransportMethod</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='drpTransportMethod']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#drpTransportMethod</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b81ef49d-fe94-4a6b-8d1c-8bcd3c505321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drpTransportMethod</value>
      <webElementGuid>67099f2e-6526-4da4-81f9-3723adb7035f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_select</value>
      <webElementGuid>643c63a8-9f30-4346-8906-e39d69fd9c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;----Select---->Air (A)Rail (R)Truck (Canada:&quot;Road&quot;) (T)Vessel (Canada: Marine) (V)</value>
      <webElementGuid>4de8bba5-373b-4e5a-b054-30016a1dea57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drpTransportMethod&quot;)</value>
      <webElementGuid>be5e6f44-39dc-4031-93dd-6c66f673a573</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='drpTransportMethod']</value>
      <webElementGuid>7631c83e-e895-4be1-a145-f40f4bd37d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div[2]/div[2]/div[2]/div[8]/select</value>
      <webElementGuid>40778d2d-aa28-4e1c-8465-5434eaa301ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/following::select[1]</value>
      <webElementGuid>8acc50f5-6bd0-4494-94ac-8a72037db923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language'])[1]/preceding::select[1]</value>
      <webElementGuid>b3ccc5f4-3a80-4794-8409-07c3e17e8aa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/select</value>
      <webElementGuid>a8a65910-6979-43c7-8f0d-2f4666dac7c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'drpTransportMethod' and (text() = '&lt;----Select---->Air (A)Rail (R)Truck (Canada:&quot;Road&quot;) (T)Vessel (Canada: Marine) (V)' or . = '&lt;----Select---->Air (A)Rail (R)Truck (Canada:&quot;Road&quot;) (T)Vessel (Canada: Marine) (V)')]</value>
      <webElementGuid>2d658154-ae68-4115-b353-f28bf1b08a86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
