<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Hazardous Material Label Code_drpMat_e4c667</name>
   <tag></tag>
   <elementGuidId>6266011d-ede2-41d5-83aa-20649dc8b6de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drpMaterialLabelCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='drpMaterialLabelCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#drpMaterialLabelCode</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7d56a80f-816d-4a08-9298-416a18481ded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drpMaterialLabelCode</value>
      <webElementGuid>110c58a1-b281-4e8a-8a25-98ea34f5e03b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_select</value>
      <webElementGuid>0bc2f905-8415-4784-9bc9-843ce710d233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;----Select---->Combustible Material (4.2)Corrosive Material (8)Dangerous when wet (4.3)Explosives (1.1)Explosives Fire (1.3)Explosives No Blast (1.4)Explosives Projected (1.2)Extremely Insensitive (1.6)Flammable Gas (2.1)Flammable Liquid (3)Flammable Solid (4.1)Infectious substance (6.2)Misc. Haz Material (9)Non-flammable gas (2.2)Organic Peroxide (5.2)Oxidizer (5.1)Poisonous gas (2.3)Poisonous materials (6.1)Radioactive (7)Very Insensitive Explos (1.5)</value>
      <webElementGuid>da16cac3-be55-4a80-a47c-cfc3bc03dc01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drpMaterialLabelCode&quot;)</value>
      <webElementGuid>358591cd-be9d-4217-a3a7-6642092d144c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='drpMaterialLabelCode']</value>
      <webElementGuid>04d72cc7-0b94-4fe3-a29f-575adf56c9cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div[2]/div[2]/div[2]/div[22]/select</value>
      <webElementGuid>1581e588-0774-4f7a-82fb-26641fc493e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hazardous Material Label Code'])[1]/following::select[1]</value>
      <webElementGuid>ca321c36-6cd7-42cf-a660-3ac0c8ebd51e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Text Message'])[1]/following::select[1]</value>
      <webElementGuid>e7dcc0f2-5818-4e65-895e-c93ef628a18f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Appparts'])[1]/preceding::select[1]</value>
      <webElementGuid>e41c8fc2-930c-4312-8485-e73a9b94f57a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attributes'])[1]/preceding::select[1]</value>
      <webElementGuid>98e93d44-4408-4a44-9632-e33c066351dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/select</value>
      <webElementGuid>4dc4bc70-8931-4fbc-bf3f-099440709c76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'drpMaterialLabelCode' and (text() = '&lt;----Select---->Combustible Material (4.2)Corrosive Material (8)Dangerous when wet (4.3)Explosives (1.1)Explosives Fire (1.3)Explosives No Blast (1.4)Explosives Projected (1.2)Extremely Insensitive (1.6)Flammable Gas (2.1)Flammable Liquid (3)Flammable Solid (4.1)Infectious substance (6.2)Misc. Haz Material (9)Non-flammable gas (2.2)Organic Peroxide (5.2)Oxidizer (5.1)Poisonous gas (2.3)Poisonous materials (6.1)Radioactive (7)Very Insensitive Explos (1.5)' or . = '&lt;----Select---->Combustible Material (4.2)Corrosive Material (8)Dangerous when wet (4.3)Explosives (1.1)Explosives Fire (1.3)Explosives No Blast (1.4)Explosives Projected (1.2)Extremely Insensitive (1.6)Flammable Gas (2.1)Flammable Liquid (3)Flammable Solid (4.1)Infectious substance (6.2)Misc. Haz Material (9)Non-flammable gas (2.2)Organic Peroxide (5.2)Oxidizer (5.1)Poisonous gas (2.3)Poisonous materials (6.1)Radioactive (7)Very Insensitive Explos (1.5)')]</value>
      <webElementGuid>c204cdc1-4d71-4d2f-bb99-e215ce028c12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
