<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Custom Category_btnadd_new</name>
   <tag></tag>
   <elementGuidId>04ac23bb-2e50-4c05-8826-70198bec8afb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnadd_new</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='btnadd_new']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#btnadd_new</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5f4cbf9d-d71f-4255-9475-53b326a672e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnadd_new</value>
      <webElementGuid>5231eeed-40ed-4192-acfe-a1c13bf59d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add_button_icon</value>
      <webElementGuid>75a3be35-f2f7-4eb7-980e-cc81da3bcd33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>add_new_cat()</value>
      <webElementGuid>e0abac44-f1ea-4c7f-b1d2-ed0f8a91b681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>818a27a5-7527-452e-986e-3beaf3dd93ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnadd_new&quot;)</value>
      <webElementGuid>da796aed-6398-45a8-a42a-05ec8f875857</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='btnadd_new']</value>
      <webElementGuid>8f85f0aa-0208-47a8-bbe2-5bd5f6f780f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div/div/div/div/div/div</value>
      <webElementGuid>15a17c52-4828-4db7-a276-4b61c1646618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Custom Category'])[1]/following::div[3]</value>
      <webElementGuid>2da64d1f-5c1e-4eba-96de-6e7539707f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close Out'])[1]/following::div[16]</value>
      <webElementGuid>be9f091e-aa26-479e-8577-76ccecf6b758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search:'])[1]/preceding::div[5]</value>
      <webElementGuid>41d9fa6c-3c01-4dd6-aedd-c8643eb0a1d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/div/div/div/div/div/div</value>
      <webElementGuid>b9861bfd-4a44-428b-8c8f-86526c3dcd1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'btnadd_new' and (text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>0b8ddbb0-40f9-4ac3-904f-f4f1e91ac45d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
