<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>3e51b032-1336-4e1a-9af3-81933758d5cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CustomCategory > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='MultiLevelCustomCategory']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#CustomCategory >> internal:role=img >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>43a382eb-3aec-4a50-83cd-de1c78c3181c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//bddemo.apapmt.com/Images/New_design_img/customcategory.png</value>
      <webElementGuid>e0017e4e-17f0-4a20-9929-aea342c20206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CustomCategory&quot;)/img[1]</value>
      <webElementGuid>303e5b6b-c201-471d-a653-82f3371c1ee4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CustomCategory']/img</value>
      <webElementGuid>9938e352-cb15-42eb-89e9-0ff781156a05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[32]/img</value>
      <webElementGuid>f3745524-ef6f-4c6d-81e1-d19da25dd705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//bddemo.apapmt.com/Images/New_design_img/customcategory.png']</value>
      <webElementGuid>665ed9bc-da94-48d0-ba4f-4941fcb672c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
