<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No Record Found_Category1_Add4</name>
   <tag></tag>
   <elementGuidId>51a929dd-1131-4bba-9009-398b92ecbabe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Category1_Add4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Category1_Add4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Category1_Add4</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f45ccbe8-5f1a-4aa1-82dc-9d5880cbc710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84c33129-fece-498d-9d7a-a74d91aeaff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Category1_Add4</value>
      <webElementGuid>71afe571-b359-416e-a362-86b60f290e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>loadCategory1(event,1,4)</value>
      <webElementGuid>421dd74d-c5d9-4602-9628-ded7a293ed7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CategoryChange(event,1,4,2)</value>
      <webElementGuid>f6871f66-a881-46b8-9211-011910cccb60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sortorder_txt</value>
      <webElementGuid>ec489846-594c-4b52-ab06-55362132777d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Category1_Add4&quot;)</value>
      <webElementGuid>181e823f-35f9-4835-9b09-b6a2ace2f530</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Category1_Add4']</value>
      <webElementGuid>c325e80c-cc16-489c-a486-7fee7ad2cfd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr_4']/td[3]/input</value>
      <webElementGuid>1e6b92b2-88a2-4b2e-9a5c-4a4721165977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>20fa0cdd-3bd5-4bfb-80e0-7ada06569c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Category1_Add4']</value>
      <webElementGuid>65dac71e-36e9-4fac-9561-76ab2a2aad42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
