<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Defragment Index_posi_abs_back</name>
   <tag></tag>
   <elementGuidId>c348ff68-4251-4e48-b179-65822abf1f04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.posi_abs_back</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='Form1']/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.posi_abs_back</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f11ad92b-bf54-460c-922b-b810a6249ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>posi_abs_back</value>
      <webElementGuid>d4759bd7-3000-451b-8888-8af56a8ccd6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Form1&quot;)/div[@class=&quot;loader_main_spin&quot;]/div[@class=&quot;posi_abs_back&quot;]</value>
      <webElementGuid>3ab0a040-b9b2-400c-9475-bfa9599e6807</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='Form1']/div[3]/div</value>
      <webElementGuid>7b7a6284-f389-441b-900a-aabcd5115f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]/div</value>
      <webElementGuid>00f135b2-8066-4db3-afd4-d7e113aa82ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
