<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>aa9079d2-fd31-43a0-b01a-a02f1a6ced64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Package > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Package']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Package >> internal:role=img >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>730c2b5f-57dd-4128-95ad-e1b5ad0359c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//bddemo.apapmt.com/Images/New_design_img/part_package.png</value>
      <webElementGuid>d1a899e9-e4d4-4b07-b033-7f4778be7dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Package&quot;)/img[1]</value>
      <webElementGuid>0bb6b2ee-82db-4e5f-91a0-39cdbefcfab8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Package']/img</value>
      <webElementGuid>8b348f43-3df5-43ab-8913-48b59c4301fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/img</value>
      <webElementGuid>4a3216a8-d0da-45d0-9a17-836b07b55ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//bddemo.apapmt.com/Images/New_design_img/part_package.png']</value>
      <webElementGuid>16bc20a5-e469-4dd6-8c85-710c8a7fa584</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
