<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Asset ID_txtAssetID</name>
   <tag></tag>
   <elementGuidId>8ed1cdb3-aa4d-496e-bd11-c61618bba8bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtAssetID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtAssetID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtAssetID</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6a71de2-912d-4a44-a3db-eb4b9fafefa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_input</value>
      <webElementGuid>cd2ef081-d144-401b-a593-30df42425025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4a41d782-90f4-4545-a702-1f82c70b68c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>34</value>
      <webElementGuid>5c0c28e3-27f1-480c-83cf-c2d3df2945b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtAssetID</value>
      <webElementGuid>aa938329-5e9a-4d63-b2f3-b85dc04c8db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtAssetID&quot;)</value>
      <webElementGuid>5816d46d-1ba6-476b-86b4-997a5f60b339</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtAssetID']</value>
      <webElementGuid>71202078-7221-4b16-8122-c40900866e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='AssetID']/input</value>
      <webElementGuid>23163b28-bfa4-45f5-ab0b-a833dadafc7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[7]/input</value>
      <webElementGuid>783a3fa8-f364-4bb5-aab3-99cc9a7e4d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtAssetID']</value>
      <webElementGuid>ee0b73d2-d47a-4825-aa40-fed7abf6b679</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
