<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Watermark_drpWatermark</name>
   <tag></tag>
   <elementGuidId>e607a9e4-3f68-41ba-9aff-7fecd67452ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drpWatermark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='drpWatermark']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#drpWatermark</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ed182c2c-351a-4f60-8ef0-7d7eb5186919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_select</value>
      <webElementGuid>9a6ffa89-89aa-4713-ac60-4f17cef4d776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drpWatermark</value>
      <webElementGuid>59bc94e4-f36a-4efe-915f-2b12254ec1a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-SELECT-123</value>
      <webElementGuid>a779d850-0aeb-4d50-b58a-f0a2778057fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drpWatermark&quot;)</value>
      <webElementGuid>9c46fc2a-6c88-412d-bc1f-9ce29de0bdf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='drpWatermark']</value>
      <webElementGuid>52df2163-3b09-4c36-b9db-33f14b4edd05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-2']/p[15]/select</value>
      <webElementGuid>8d3a697e-3751-4a29-9802-98cf23aed3e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Watermark'])[1]/following::select[1]</value>
      <webElementGuid>5c254820-1387-47c7-bdf3-98cbd0151cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort By'])[1]/following::select[1]</value>
      <webElementGuid>b1db779b-7cbf-4d67-99f8-785c96b5c7a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Callout'])[1]/preceding::select[1]</value>
      <webElementGuid>b555c32c-34ba-44a8-9b8e-7d8c05b0ddde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset Dimension and Description'])[1]/preceding::select[2]</value>
      <webElementGuid>f2edeb20-0c58-416a-b038-2da981e92248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[15]/select</value>
      <webElementGuid>72f47414-d2d5-4250-9454-9fcdf90eb12e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'drpWatermark' and (text() = '-SELECT-123' or . = '-SELECT-123')]</value>
      <webElementGuid>15cfab02-cd1a-4015-a012-1948e3e6314d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
