<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Color Mode_drpColorCode</name>
   <tag></tag>
   <elementGuidId>905b0322-704c-40a3-9941-ae4a78b841bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drpColorCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='drpColorCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#drpColorCode</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2f9da407-00ed-4437-a379-4d85973e992b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_select</value>
      <webElementGuid>4d634ab4-abad-4e3a-aef9-b9794447e1d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drpColorCode</value>
      <webElementGuid>7c6f20fe-73ed-4820-bd00-cea8c8c9f365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-SELECT-BIT (BIT)CMY (CMY)GRA (GRA)OTH (OTH)RGB (RGB)WEB (WEB)VEC (VEC)</value>
      <webElementGuid>5173122d-2d5b-4d70-8ff5-b23caa30aad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drpColorCode&quot;)</value>
      <webElementGuid>51b8e2a9-e757-48a6-ba11-e7ba897907cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='drpColorCode']</value>
      <webElementGuid>26c333cc-a044-4423-a5eb-b75f19e2bb51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-2']/p[12]/select</value>
      <webElementGuid>3ff10585-b567-4713-befd-38b3f610b955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color Mode'])[1]/following::select[1]</value>
      <webElementGuid>26840bf1-f123-41a0-a8da-9a9aa3350e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Orientation View'])[1]/following::select[2]</value>
      <webElementGuid>49652633-29d1-4248-baf6-ef3b250db738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Background'])[1]/preceding::select[1]</value>
      <webElementGuid>4c5166bb-2adb-4018-b614-42e4c1290811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort By'])[1]/preceding::select[2]</value>
      <webElementGuid>42fb82b7-003f-4d34-a979-774f531d64dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[12]/select</value>
      <webElementGuid>153c1d98-6eaf-459b-85c3-510267458df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'drpColorCode' and (text() = '-SELECT-BIT (BIT)CMY (CMY)GRA (GRA)OTH (OTH)RGB (RGB)WEB (WEB)VEC (VEC)' or . = '-SELECT-BIT (BIT)CMY (CMY)GRA (GRA)OTH (OTH)RGB (RGB)WEB (WEB)VEC (VEC)')]</value>
      <webElementGuid>bea9c90e-177c-4612-8aa4-29156fff2c38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
