<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>0623194e-64dd-4b06-bfb5-84406f3508c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='piespages']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>6fe94c23-06a3-4355-91c3-ab5506b7a2cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../Parts/BuyersGuideEnginebase_New.aspx?PartID=330387&amp;Category=Testing_Pmt&amp;Subcategory=Testing_Pmt&amp;PartDescription=Testing_Pmt&amp;Partno=Testing_Automation&amp;PageTitle=Parts+Application Data &amp;Productdescid=1834&amp;qty=1</value>
      <webElementGuid>cabecd48-a06a-45b8-a35f-80d1e74bf704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;piespages&quot;)/iframe[1]</value>
      <webElementGuid>a85f94f1-5e59-4600-875c-cfb8f00a7ab7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/iframe</value>
      <webElementGuid>a3714050-2594-43b7-b20f-a6d635ddb25b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>446c3965-7007-443b-84b1-719852f705c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '../Parts/BuyersGuideEnginebase_New.aspx?PartID=330387&amp;Category=Testing_Pmt&amp;Subcategory=Testing_Pmt&amp;PartDescription=Testing_Pmt&amp;Partno=Testing_Automation&amp;PageTitle=Parts+Application Data &amp;Productdescid=1834&amp;qty=1']</value>
      <webElementGuid>3648890d-2646-4ebb-aad5-96e06bf75699</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
