<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_position_MainContent_dlDisplayColumnL_c8d079</name>
   <tag></tag>
   <elementGuidId>efebbf2e-f918-434c-81da-093d0cf05fda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MainContent_dlDisplayColumnList_chkselectAll1_40']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MainContent_dlDisplayColumnList_chkselectAll1_40</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;position All&quot;i] >> internal:label=&quot;All&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54a68aa3-97e5-4121-bfbb-7c26280c2323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainContent_dlDisplayColumnList_chkselectAll1_40</value>
      <webElementGuid>c5241dd6-7f5c-4753-bb65-5e86ceadca47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c7c31b31-a8fe-43a2-ad29-dc78e57ebd04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$dlDisplayColumnList$ctl40$chkselectAll1</value>
      <webElementGuid>68bb5c64-7313-48b1-9f42-a9fba336b044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CheckAllGrid(this);</value>
      <webElementGuid>ca49cc15-0b2d-46a1-b312-cac4f14bb90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_dlDisplayColumnList_chkselectAll1_40&quot;)</value>
      <webElementGuid>1c81dd23-bf51-41ed-9b17-212e0a3bd691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Parts segment/Application/With Enginee Select/Without Attribute/Add Application/Page_BDDemoPMT/iframe</value>
      <webElementGuid>ff771ad2-b961-485d-b599-e7c80e2f33a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MainContent_dlDisplayColumnList_chkselectAll1_40']</value>
      <webElementGuid>32532fdf-4882-47de-bcad-4e9405fb03fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_dlDisplayColumnList_UpdatePanel5_40']/h3/span/span/input</value>
      <webElementGuid>8141062d-83f8-44e8-94d3-caffac7bb514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[41]/div/h3/span/span/input</value>
      <webElementGuid>c2efe6e8-30a9-4119-8f18-6f06617d4f79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MainContent_dlDisplayColumnList_chkselectAll1_40' and @type = 'checkbox' and @name = 'ctl00$MainContent$dlDisplayColumnList$ctl40$chkselectAll1']</value>
      <webElementGuid>67a0a3b0-9beb-4f6f-8e5b-b880c05257fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
