<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sub Model_MainContent_dlDisplayColumn_303378</name>
   <tag></tag>
   <elementGuidId>5901bc81-268f-41fa-b7a2-8e1105efc092</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MainContent_dlDisplayColumnList_chkselectAll1_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MainContent_dlDisplayColumnList_chkselectAll1_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Sub Model All&quot;i] >> internal:label=&quot;All&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a9e12075-0135-462c-9966-33300a7e55dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainContent_dlDisplayColumnList_chkselectAll1_1</value>
      <webElementGuid>dc1b21c8-f5d1-43f4-8ef5-9e206913be40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>fe280c11-510f-45df-a560-6289f950e5b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$dlDisplayColumnList$ctl01$chkselectAll1</value>
      <webElementGuid>df254242-20a7-42d2-b370-699c474630db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CheckAllGrid(this);</value>
      <webElementGuid>1f8d5e68-025d-49e3-b040-23c7188cbcc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_dlDisplayColumnList_chkselectAll1_1&quot;)</value>
      <webElementGuid>84937e2a-071c-472d-b908-34f290c3bd03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Parts segment/Application/With Enginee Select/Without Attribute/Add Application/Page_BDDemoPMT/iframe</value>
      <webElementGuid>7c74bc1b-c115-4f75-9d03-71eae9ac0eeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MainContent_dlDisplayColumnList_chkselectAll1_1']</value>
      <webElementGuid>b0952a6f-b2d5-416c-80d3-dc61a484f91d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_dlDisplayColumnList_UpdatePanel5_1']/h3/span/span/input</value>
      <webElementGuid>694442d3-6a3c-4eef-b0a2-0edebd870673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h3/span/span/input</value>
      <webElementGuid>254b3a4d-448c-4784-8681-bf7804a91b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MainContent_dlDisplayColumnList_chkselectAll1_1' and @type = 'checkbox' and @name = 'ctl00$MainContent$dlDisplayColumnList$ctl01$chkselectAll1']</value>
      <webElementGuid>750c9d5e-902f-45ca-abad-e04406ae1d9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
