<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IncludeNonAces_MainContent_searchbtn</name>
   <tag></tag>
   <elementGuidId>956b7f20-feda-46b2-ba2f-0b8e195bd0e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MainContent_searchbtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MainContent_searchbtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;View Available Applications&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e578086-9970-442a-9a8d-878628ccdded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>38bfa51c-e24b-4383-a652-bc071b58033b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$searchbtn</value>
      <webElementGuid>57f165b5-2cdf-44af-b41d-5a1fe049850b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>View Available Applications</value>
      <webElementGuid>9f90e032-f597-422e-a157-594e7c276657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return validate();</value>
      <webElementGuid>8bf68323-37d1-469a-8707-4f4d25c0b94d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainContent_searchbtn</value>
      <webElementGuid>2baaed60-2f7c-4534-87f5-87abb60d6e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button_search m_t_20</value>
      <webElementGuid>66ccb183-08fe-4da3-aa2f-28dcd924057c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_searchbtn&quot;)</value>
      <webElementGuid>aef69869-4c67-4ad7-af72-db0f10b689b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Parts segment/Application/With Enginee Select/Without Attribute/Add Application/Page_BDDemoPMT/iframe</value>
      <webElementGuid>2afa0c64-39c3-45a6-a710-4787a4376222</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MainContent_searchbtn']</value>
      <webElementGuid>71ffbe35-43d0-4066-927b-26aa919827fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_div_filter']/b/span[2]/input</value>
      <webElementGuid>46920d19-77b2-407d-878f-b5e5f5e4bd8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b/span[2]/input</value>
      <webElementGuid>a706ba0d-968f-419f-9ae8-2b0d465cfa9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$MainContent$searchbtn' and @id = 'MainContent_searchbtn']</value>
      <webElementGuid>d4f2e000-8f7f-4171-ad05-0c25f8bd0142</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
