<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__MainContent_drpModel</name>
   <tag></tag>
   <elementGuidId>d47d067c-f20e-442a-a455-6342c45de9ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='MainContent_drpModel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MainContent_drpModel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#MainContent_drpModel</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bd531085-cf68-4a41-9e14-7efb00136e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$drpModel</value>
      <webElementGuid>7122bdf3-4a16-4a91-9273-bb45d22c0b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$MainContent$drpModel\',\'\')', 0)</value>
      <webElementGuid>5b7c0842-ce35-4a70-bf43-625870aeadc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainContent_drpModel</value>
      <webElementGuid>86bc8bbf-7f28-42fa-8215-116afe010237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	Select
	1000
	1150
	1300
	1600
	2000
	204
	205
	750
	850
	Simca

</value>
      <webElementGuid>b37b756b-2db0-48c2-80ee-ef4113fce47b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_drpModel&quot;)</value>
      <webElementGuid>448a4953-641b-4afd-9883-905f7dbf4617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Parts segment/Application/With Enginee Select/Without Attribute/Add Application/Page_BDDemoPMT/iframe</value>
      <webElementGuid>a40b446a-181e-481d-8afe-ed93a35cbd24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='MainContent_drpModel']</value>
      <webElementGuid>e34ac25c-1c8d-4d48-b70b-bddedafbcde4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_div_filter']/span[3]/select</value>
      <webElementGuid>414fd9f5-a2c1-4a44-bcc4-252559105e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[1]</value>
      <webElementGuid>32bebd97-4473-421b-9bc6-caea77ab00d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Model'])[1]/following::select[1]</value>
      <webElementGuid>c83af44e-6b58-4489-8bd5-15ba522ec6bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enginebase'])[1]/preceding::select[1]</value>
      <webElementGuid>4e4a5ea9-96ba-405a-b2ec-14ec0fa03e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You can choose either specific engine base(s) or Engine Not Required option.'])[1]/preceding::select[1]</value>
      <webElementGuid>c8fa35d5-e632-4b93-8720-b66024dc7712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/select</value>
      <webElementGuid>ac6e432a-bc07-405c-a979-c45a56152035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ctl00$MainContent$drpModel' and @id = 'MainContent_drpModel' and (text() = '
	Select
	1000
	1150
	1300
	1600
	2000
	204
	205
	750
	850
	Simca

' or . = '
	Select
	1000
	1150
	1300
	1600
	2000
	204
	205
	750
	850
	Simca

')]</value>
      <webElementGuid>bc54cfad-404c-44e8-9be5-8966fa4f076a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
