<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_L4 982CC 60CID 1.0L 2.56 65.0 2.91_ccf76b</name>
   <tag></tag>
   <elementGuidId>e5c58d59-202d-4758-b757-360583060f26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='MainContent_GvApplications_txtapppartsnotes_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MainContent_GvApplications_txtapppartsnotes_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#MainContent_GvApplications_txtapppartsnotes_0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ee84cfbf-65e7-4070-9ecb-bcb6ccf23e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$GvApplications$ctl02$txtapppartsnotes</value>
      <webElementGuid>ab83a5ff-fd1c-441f-9914-248ef141cf83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>d596047c-224e-44c2-8bb4-acd6f802e65d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>5e3df821-62eb-4b22-aca1-9eb37a98caa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainContent_GvApplications_txtapppartsnotes_0</value>
      <webElementGuid>df6ff67c-e15a-44e4-86d6-a8743947ac73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_GvApplications_txtapppartsnotes_0&quot;)</value>
      <webElementGuid>1ffb6971-b37e-4e35-8eb4-c7babeeb2071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Parts segment/Application/With Enginee Select/Without Attribute/Add Application/Page_BDDemoPMT/iframe</value>
      <webElementGuid>90aaacf2-681b-4aea-9c42-856797ee97fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='MainContent_GvApplications_txtapppartsnotes_0']</value>
      <webElementGuid>d824f48f-458f-4d81-9d3a-dc8843e88f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='MainContent_GvApplications']/tbody/tr[2]/td[4]/textarea</value>
      <webElementGuid>f75e9418-d8e9-4f7b-a633-9c2520e86b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>8349606d-02dc-4753-9406-c9b65ae943d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$MainContent$GvApplications$ctl02$txtapppartsnotes' and @id = 'MainContent_GvApplications_txtapppartsnotes_0']</value>
      <webElementGuid>9cd42611-5cfa-48ed-a2e1-423f06af4491</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
