<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>22b69dc5-1b53-4f1f-83c2-ad0d047fbf48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BuyersGuid1 > img</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = '//bddemo.apapmt.com/Images/New_design_img/part_buyer_guide.png']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='BuyersGuid1']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#BuyersGuid1 >> internal:role=img >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>900e514f-a849-4b00-95ea-8f18cca6d7ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//bddemo.apapmt.com/Images/New_design_img/part_buyer_guide.png</value>
      <webElementGuid>43698518-6c55-455e-aa11-4a9df744855e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BuyersGuid1&quot;)/img[1]</value>
      <webElementGuid>4a44ad6c-4de7-440f-b85e-f249b6bf2970</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BuyersGuid1']/img</value>
      <webElementGuid>c96bc0e0-bc92-45e3-83f4-811c5cdd7d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>35d5857f-ae80-4480-9f36-a759e4f7a64f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//bddemo.apapmt.com/Images/New_design_img/part_buyer_guide.png']</value>
      <webElementGuid>113a1e4d-f446-44db-937e-d89d34710ebb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
