<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Validate_chk_appparts</name>
   <tag></tag>
   <elementGuidId>131be6dc-3298-4db6-87e1-ced7c4fd8c81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chk_appparts</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='chk_appparts']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#chk_appparts</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b3f35029-e2cf-4d06-9923-4d701ffd2bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0c0cab6d-2327-47ee-b73c-5aa1881d4cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chk_appparts</value>
      <webElementGuid>8aa5ba7a-a9af-46c1-a044-6b19e2a74296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$checkbox2</value>
      <webElementGuid>ea1052f5-de07-4e32-b8a4-c3f874f7bcc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chkAccId</value>
      <webElementGuid>478589a5-ddeb-4bb1-94e9-685d014bba28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4744826</value>
      <webElementGuid>f9fc78f0-71a1-4c21-8178-513d8cff7b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chk_appparts&quot;)</value>
      <webElementGuid>95b9bb2e-f495-4bff-935f-1e8b3ecc65ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Parts segment/Application/Without Enginee Select/Without Attribute/Delete Application/Page_BDDemoPMT/iframe</value>
      <webElementGuid>00d9b071-27be-41cb-963d-1a7868efdfe3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='chk_appparts']</value>
      <webElementGuid>31fa164f-f0a8-40ec-9171-5354783b22bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr_0']/td[15]/input</value>
      <webElementGuid>cc98177c-49e8-4575-9046-0f83ae0b0f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[15]/input</value>
      <webElementGuid>38d9bec5-8635-4377-89fb-ef1ecd3004e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'chk_appparts' and @name = 'ctl00$MainContent$checkbox2']</value>
      <webElementGuid>5475ad4f-c9d4-46ff-b524-244bfcdefe10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
