<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Edit_glowing-border</name>
   <tag></tag>
   <elementGuidId>5f368b2b-98c6-465c-a004-0a3392fb1204</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.glowing-border</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Vehicle Type&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>888e6016-a125-4efe-a935-b46a4a3d9ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glowing-border</value>
      <webElementGuid>1d3d2233-69c8-43d1-bfca-36ff664d1ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>05dcfc48-1e95-4730-8d42-c7ee1b97a194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Vehicle Type</value>
      <webElementGuid>837cadbb-ce56-43ad-b3fd-f7e0fb16df43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbl_apppartstable_wrapper&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;dataTables_scroll&quot;]/div[@class=&quot;dataTables_scrollFoot&quot;]/div[@class=&quot;dataTables_scrollFootInner&quot;]/table[@class=&quot;table table-striped table-bordered display nowrap dataTable&quot;]/tfoot[1]/tr[1]/th[1]/input[@class=&quot;glowing-border&quot;]</value>
      <webElementGuid>bc3dd7eb-9a3a-42a8-a383-a31afd066185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Parts segment/Application/Without Enginee Select/Without Attribute/Delete Application/Page_BDDemoPMT/iframe</value>
      <webElementGuid>acfee20c-8f64-4878-9899-f4f4ec28494e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[8]</value>
      <webElementGuid>12bf86ec-bbf0-4741-9556-d2cb3a63c534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tbl_apppartstable_wrapper']/div[2]/div/div/div[2]/div/table/tfoot/tr/th/input</value>
      <webElementGuid>f5f1c971-ae68-436e-a57a-bbfb842da539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tfoot/tr/th/input</value>
      <webElementGuid>45076961-3a3a-4c76-8c49-d47fec3341a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Vehicle Type']</value>
      <webElementGuid>6d15ddf6-41c1-44f5-9604-66886d3a2ae8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
