<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Edit_apppartdelete</name>
   <tag></tag>
   <elementGuidId>fbe4f027-214c-438b-a48c-cb3255082969</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='apppartdelete']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th.sorting_disabled > #apppartdelete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Submit&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f6a71ef-0823-4ff2-a18e-4a5b1c4c4b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>14290726-7fae-414e-86d0-22cfec2413a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apppartdelete</value>
      <webElementGuid>f5d8295c-d563-4f6e-85a1-d9b32bbeb8ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//bddemo.apapmt.com/Images/delete_red.png</value>
      <webElementGuid>e63073f7-4407-44fb-93aa-27c2244d1780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbl_apppartstable_wrapper&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;dataTables_scroll&quot;]/div[@class=&quot;dataTables_scrollHead&quot;]/div[@class=&quot;dataTables_scrollHeadInner&quot;]/table[@class=&quot;table table-striped table-bordered display nowrap dataTable&quot;]/thead[1]/tr[1]/th[@class=&quot;sorting_disabled&quot;]/input[@id=&quot;apppartdelete&quot;]</value>
      <webElementGuid>df3bd1bc-0ec7-4604-9c5f-548db1f58c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Parts segment/Application/With Enginee Select/Without Attribute/Delete Application/Page_BDDemoPMT/iframe</value>
      <webElementGuid>cb818056-594e-4ca4-8b5f-580c8169a2f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='apppartdelete']</value>
      <webElementGuid>a8a36cef-803b-43d0-b579-666aee7523ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tbl_apppartstable_wrapper']/div[2]/div/div/div/div/table/thead/tr/th[15]/input</value>
      <webElementGuid>0b08ff67-bf11-48dc-ae16-9a9eff56f47d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[15]/input</value>
      <webElementGuid>c7454815-0419-49d4-a354-50f92d392e3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @id = 'apppartdelete' and @src = '//bddemo.apapmt.com/Images/delete_red.png']</value>
      <webElementGuid>1921cc42-6794-49f7-96ce-da7c26662ac3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
