<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>319778e3-03d2-4e54-b440-03cbfc53ff79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='piespages']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>c2bf716e-7838-44b2-9b79-df5a16ee5383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../Parts/Notes.aspx?PartID=329579&amp;Category=Testing_Pmt&amp;Subcategory=Testing_Ecat&amp;PartDescription=Testing_Ecat&amp;Part=Testing_Automation</value>
      <webElementGuid>c9ae897d-92e8-4821-abe2-12dc5fdea388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;piespages&quot;)/iframe[1]</value>
      <webElementGuid>6eb68870-9b3f-4b98-be5a-97367f054c82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/iframe</value>
      <webElementGuid>7dbfe946-3c10-424e-b698-54336b3164d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>4522fb22-78da-4c71-a3c7-f0457ffaa08f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '../Parts/Notes.aspx?PartID=329579&amp;Category=Testing_Pmt&amp;Subcategory=Testing_Ecat&amp;PartDescription=Testing_Ecat&amp;Part=Testing_Automation']</value>
      <webElementGuid>3ece968f-4d52-4e93-a5bf-eaf9ce9e5f86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
