<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_image</name>
   <tag></tag>
   <elementGuidId>c2829457-83c2-4cc9-a60a-432bbb9389c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'image' and @src = '//bddemo.apapmt.com/Images/delete_black.png' and @ref_element = 'Object Repository/Parts segment/Notes/Delete Notes/Page_BDDemoPMT/iframe']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='blkdeletenotes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Submit&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9fff56d-be11-4f4e-a9be-55993f046a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>7321c076-fe0d-4aa5-a743-334c09aee40c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//bddemo.apapmt.com/Images/delete_black.png</value>
      <webElementGuid>3138ac50-1965-4be7-abb1-6c44b8d3ced5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return DeleteNotes(329579,'Testing_Automation');</value>
      <webElementGuid>cdd1df4f-03c3-4268-aefb-73f4b277fbdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTableViewer&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[3]/div[1]/input[2]</value>
      <webElementGuid>6ed0cd87-7dfb-4409-97a3-9b15bde53604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Parts segment/Notes/Delete Notes/Page_BDDemoPMT/iframe</value>
      <webElementGuid>3dc54991-c1f8-4c46-81d8-e4b960df1548</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='image'])[2]</value>
      <webElementGuid>5ea3ae31-41cf-480b-9ede-89c22489a097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTableViewer']/tbody/tr/td[3]/div/input[2]</value>
      <webElementGuid>95c93910-f595-4cd5-b4ed-bc573c781b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/input[2]</value>
      <webElementGuid>88a3f185-15c1-4fd1-b78c-b5dc7d8536f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @src = '//bddemo.apapmt.com/Images/delete_black.png']</value>
      <webElementGuid>1b047e6a-21b5-492b-961c-07170367c48b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
