<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>1ce883e0-0299-4ed0-bdf9-41c9b56c476d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Interchange']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Interchange > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Interchange >> internal:role=img >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e170bb0f-3344-4a95-ac1f-3e9567fee08e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//bddemo.apapmt.com/Images/New_design_img/parts_interchange1.png</value>
      <webElementGuid>716c9ea4-bf0e-43f3-839f-db642c9bcb75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Interchange&quot;)/img[1]</value>
      <webElementGuid>6a5ae2a4-964b-4393-98af-5cd64bdc9527</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Interchange']/img</value>
      <webElementGuid>f2cf346c-fe1f-44a7-9b80-5abc73d2ad46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/img</value>
      <webElementGuid>87a8fc30-1af2-4ab1-b228-5438f0d09905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//bddemo.apapmt.com/Images/New_design_img/parts_interchange1.png']</value>
      <webElementGuid>e6d27307-ac02-410b-a2a0-a2f96d6d1ace</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
