<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Defragment Index_posi_abs_back</name>
   <tag></tag>
   <elementGuidId>5b8e58bb-6591-4e3f-956b-6af50222d6aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.posi_abs_back</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;Form1&quot;)/div[@class=&quot;loader_main_spin&quot;]/div[@class=&quot;posi_abs_back&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='Form1']/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.posi_abs_back</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5ac2ab75-3085-4ff7-8301-309a053c8a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>posi_abs_back</value>
      <webElementGuid>cd746f4f-7bcf-4681-9605-2f2f441e21dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Form1&quot;)/div[@class=&quot;loader_main_spin&quot;]/div[@class=&quot;posi_abs_back&quot;]</value>
      <webElementGuid>39e00a10-9571-4518-a6f9-920f52e3b395</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='Form1']/div[3]/div</value>
      <webElementGuid>996a9084-79c0-4a9a-a716-6b26503d2cd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]/div</value>
      <webElementGuid>ba356633-a13e-4a50-bc16-c9faa9425060</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
