<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__DocumentTitle</name>
   <tag></tag>
   <elementGuidId>5d802e67-59fc-4da1-93ac-c16f6aa91757</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DocumentTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DocumentTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#DocumentTitle</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf21cabd-6ab7-4454-9b35-5a3e09a71a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_input</value>
      <webElementGuid>f3e526db-1d1c-4104-b97c-c6708ebbd99e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return specificspecialchar(event); </value>
      <webElementGuid>8b83ee37-dd36-4740-8ad0-df28c88249b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>return handlePaste(event)</value>
      <webElementGuid>6aa32ca8-245f-43a9-8312-53c2d46ba4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b685d615-38f3-4dcc-9001-5525d145e192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DocumentTitle</value>
      <webElementGuid>3a1d8ddb-0f75-4bb4-b0cd-12b5940258e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DocumentTitle&quot;)</value>
      <webElementGuid>b0b1bd8b-987f-43b3-87c8-027de9e79f07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DocumentTitle']</value>
      <webElementGuid>07e9eaaf-f0bf-4785-a639-6e5404ae8fe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divExportFormat']/div[2]/p[5]/input</value>
      <webElementGuid>87fdc7d2-a505-4b81-92f5-e21bf4eb9eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[5]/input</value>
      <webElementGuid>12108455-cc43-4d73-9166-4dbffe8eae59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'DocumentTitle']</value>
      <webElementGuid>4a0b5919-e66d-41b3-8847-106e48abd857</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
