<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Edit_glowing-border</name>
   <tag></tag>
   <elementGuidId>704e0a7e-a16d-44a2-99f2-2359b31fe24f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th:nth-of-type(7) > input.glowing-border</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[14]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Notes&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>08b9dfbe-8e9c-41c0-af43-1c4c0cbadff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glowing-border</value>
      <webElementGuid>a97ba541-5092-45b9-9a74-edb06e0ca4ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ba43430a-ce64-4f4e-a954-d4083ed12c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Notes</value>
      <webElementGuid>2beab438-2fb4-466f-9dfd-dd1ac9b42356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbl_apppartstable_wrapper&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;dataTables_scroll&quot;]/div[@class=&quot;dataTables_scrollFoot&quot;]/div[@class=&quot;dataTables_scrollFootInner&quot;]/table[@class=&quot;table table-striped table-bordered display nowrap dataTable&quot;]/tfoot[1]/tr[1]/th[7]/input[@class=&quot;glowing-border&quot;]</value>
      <webElementGuid>d9aa9319-4f53-4ddd-80b5-8f266fc771a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Parts segment/Application/Without Enginee Select/With Attribute/Edit Application/Page_BDDemoPMT/iframe</value>
      <webElementGuid>fa772c82-20d4-410d-ae31-a0de8f7ac896</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[14]</value>
      <webElementGuid>b217f606-3580-49fe-9350-d8600db084fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tbl_apppartstable_wrapper']/div[2]/div/div/div[2]/div/table/tfoot/tr/th[7]/input</value>
      <webElementGuid>18b63152-ca8b-4530-962f-33e46db3301f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[7]/input</value>
      <webElementGuid>eb26ab30-2aa3-4db8-99ee-7e8cedad01bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Notes']</value>
      <webElementGuid>a5e61164-e21f-416f-b3cc-1bfc39274661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[8]</value>
      <webElementGuid>62e9021b-b9a0-4c2a-8e72-ab4c1b4976e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tbl_apppartstable_wrapper']/div[2]/div/div/div[2]/div/table/tfoot/tr/th/input</value>
      <webElementGuid>8f4d1fad-805d-454e-825c-eb33c4c46742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tfoot/tr/th/input</value>
      <webElementGuid>4271f37b-cda7-4882-89d7-9f0cb2c2319d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Vehicle Type']</value>
      <webElementGuid>6e81ecc5-68c3-44b2-83ae-fd36032a8df4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
