<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Validate_appartsedit_btn</name>
   <tag></tag>
   <elementGuidId>df848430-d4a0-4244-bc11-e503de721988</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#appartsedit_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='appartsedit_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#appartsedit_btn</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef7a04d0-6576-4ee2-ab24-d54b651bf6f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>5b40fb8d-6d35-4f53-92c1-036be2236192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>appartsedit_btn</value>
      <webElementGuid>4f4cdb39-8dba-4843-bca8-db9bb02e806d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//bddemo.apapmt.com/Images/edit_black.png</value>
      <webElementGuid>13636fe5-2406-4922-9205-4e3f8cef36c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>appartsedit_Click(4744871,3347922)</value>
      <webElementGuid>60786cf0-722e-4299-bef2-c43247fed5b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chkAccId_edit</value>
      <webElementGuid>0704dd6b-6299-478a-88d5-1cb9887c048f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vehicletypename</name>
      <type>Main</type>
      <value>Car</value>
      <webElementGuid>5d180e7f-96d6-4cac-9239-75d8390c53fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enginecode</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>26264cc7-a418-49c2-9896-8cbb16862c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-makename</name>
      <type>Main</type>
      <value>Abarth</value>
      <webElementGuid>6b297a26-3708-4f65-8aeb-e9a62071bfdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelname</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>9396fd13-7a24-4ec0-867f-118bc111d241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3347922</value>
      <webElementGuid>204cd3fd-3079-45b3-bfb2-1908a9a27bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appartsedit_btn&quot;)</value>
      <webElementGuid>39bcf43d-8bcc-4442-8448-bd4c1702a053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Parts segment/Application/Without Enginee Select/With Attribute/Edit Application/Page_BDDemoPMT/iframe</value>
      <webElementGuid>d99f2b02-a566-4995-ace4-b1baab2e1ff9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='appartsedit_btn']</value>
      <webElementGuid>10d1060f-fd4c-4415-9071-369408e1217b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr_1']/td[12]/input</value>
      <webElementGuid>952f40c6-1e5a-422f-96f0-ae91b02146f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[12]/input</value>
      <webElementGuid>260d11ba-55ab-4801-b1ac-8967402528a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @id = 'appartsedit_btn' and @src = '//bddemo.apapmt.com/Images/edit_black.png']</value>
      <webElementGuid>dc662c77-68a7-4add-8ef5-16068d6702c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr_0']/td[12]/input</value>
      <webElementGuid>61a0707a-bd57-475b-9fa2-a42b8e969eb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
