<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Recommended_txtBarCode</name>
   <tag></tag>
   <elementGuidId>01d91770-d18f-416f-ac92-a0034c5210f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtBarCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtBarCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtBarCode</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b7c9d95-95ef-42c0-98c3-110cf9ae218b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9741f5d5-5cf5-4b76-a74d-b53294f3de67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtBarCode</value>
      <webElementGuid>c50b607d-8cdb-4981-bc61-eaf416c4f3c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_input</value>
      <webElementGuid>2b26600c-5413-42b6-89fe-bb2ae0328f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>4286f04b-d381-46b6-8110-f575ee2d0c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>PartnoValidate(this)</value>
      <webElementGuid>301dec31-bd5c-45cc-bb0b-8778455c53f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtBarCode&quot;)</value>
      <webElementGuid>0f4abde5-b550-4ab8-86be-658f75eb553e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtBarCode']</value>
      <webElementGuid>3c3eaa66-d392-4bdb-ad72-0191da59b4d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div/div[2]/div[3]/div[5]/input</value>
      <webElementGuid>3a3abae1-f231-474b-acd3-5adfa67ed32e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[5]/input</value>
      <webElementGuid>dfea4b25-b694-4b7a-a96c-2b5fef7e110e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtBarCode']</value>
      <webElementGuid>438f3fd1-83a9-4ac6-b2bc-52a9a1ed671b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
