<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Recommended_txtPackageGTIN</name>
   <tag></tag>
   <elementGuidId>88ce32f9-03c6-4539-9815-2ed04bbc6fc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtPackageGTIN</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtPackageGTIN']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtPackageGTIN</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b43fd035-4641-4f7e-8810-750efe46992b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7c9a71f5-25a1-4309-88bb-67f92c2df4a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtPackageGTIN</value>
      <webElementGuid>1d7262bd-c608-4e2e-93d6-0e3c8057eafd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_input</value>
      <webElementGuid>4765544a-bd8f-400b-8b4e-d14b01c9a18f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>14507d4e-f706-4739-be23-aa098aa8c9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return NumberOnly()</value>
      <webElementGuid>7bf57231-fcb1-40f3-9783-f0b175fee56b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtPackageGTIN&quot;)</value>
      <webElementGuid>e442a4bf-b7b3-4f8d-89bf-872ab225a949</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtPackageGTIN']</value>
      <webElementGuid>74406da4-c87a-45fc-926e-4a61197b1fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div/div[2]/div[3]/div[3]/input</value>
      <webElementGuid>f7db74aa-d73c-49b5-836e-cd249fc054bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[3]/input</value>
      <webElementGuid>e38acd56-a4df-4826-b6df-3d4ec085a1d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtPackageGTIN']</value>
      <webElementGuid>723a1830-a09b-47ec-a850-0c566697b4ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
