<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_UOM Of Dimension_drpUomDimension</name>
   <tag></tag>
   <elementGuidId>19c5464f-2d24-4fd0-aaa6-8b9acb5008ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drpUomDimension</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='drpUomDimension']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#drpUomDimension</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>675dfe49-01bd-4c8d-9829-f3c0d453951b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drpUomDimension</value>
      <webElementGuid>d4b61fd4-7bcb-4cd1-9de1-58814d37fdf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_input</value>
      <webElementGuid>411cfb71-9dee-4479-b8c3-c02c1aa09d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;----Select---->CentimetersInchesMillimeterPixelSquare FeetYards</value>
      <webElementGuid>7a87469d-1827-4d01-899a-31453d4c43df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drpUomDimension&quot;)</value>
      <webElementGuid>0d1d28d2-7261-4d4b-b29e-0e3b8d7f4235</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='drpUomDimension']</value>
      <webElementGuid>c938926f-0e1d-43a5-ab56-89a86116452d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div/div[2]/div[3]/div[19]/select</value>
      <webElementGuid>817c5d85-213d-4648-ad3c-e61a8a1df83a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UOM Of Dimension'])[1]/following::select[1]</value>
      <webElementGuid>6dac3887-2d3b-4a3c-a491-f78408503630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipping Length'])[1]/following::select[1]</value>
      <webElementGuid>0b337b4e-9480-4369-b7bd-66340e163d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UOM for Weight'])[1]/preceding::select[1]</value>
      <webElementGuid>8c0bb225-1ac7-4db0-8a60-b0f4bff77218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Weight Per Package'])[1]/preceding::select[2]</value>
      <webElementGuid>d474ef34-80f1-4095-a2b7-71f92fb47855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/select</value>
      <webElementGuid>5a167c55-0ddf-447e-81b8-d4771e12f7f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'drpUomDimension' and (text() = '&lt;----Select---->CentimetersInchesMillimeterPixelSquare FeetYards' or . = '&lt;----Select---->CentimetersInchesMillimeterPixelSquare FeetYards')]</value>
      <webElementGuid>80f9c3a5-ab34-4c01-a942-3eaebd04e671</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
