<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_ALL ENGINES_MainContent_GvApplicat_b57c46</name>
   <tag></tag>
   <elementGuidId>2c45b2a8-ddc5-4b09-b5b0-5e098b62d629</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MainContent_GvApplications_txtapppartsnotes_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='MainContent_GvApplications_txtapppartsnotes_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#MainContent_GvApplications_txtapppartsnotes_0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d7c14fec-db35-4737-822d-9351e840d165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$GvApplications$ctl02$txtapppartsnotes</value>
      <webElementGuid>5667f613-17c6-4515-85af-fbc51dfc3001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>45409e7f-9398-46c9-a438-9aef9ef56004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>7324c432-5887-4dad-8c66-713a48ae6eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainContent_GvApplications_txtapppartsnotes_0</value>
      <webElementGuid>7bc0b43d-62e2-4844-9f78-23b8ddf6e60a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Testing_Automation</value>
      <webElementGuid>a370590c-1ed3-49da-8bef-4c62a264a6cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_GvApplications_txtapppartsnotes_0&quot;)</value>
      <webElementGuid>6e235410-dbde-4661-b802-b818e6e35c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Parts segment/Application/Without Enginee Select/Without Attribute/Edit Application/Page_BDDemoPMT/iframe</value>
      <webElementGuid>60421e80-ec8c-430d-b316-900ee4fcd22c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='MainContent_GvApplications_txtapppartsnotes_0']</value>
      <webElementGuid>451a40ba-85fb-4800-823b-82d341abaf53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='MainContent_GvApplications']/tbody/tr[2]/td[4]/textarea</value>
      <webElementGuid>e0029394-49ff-4fcb-a78a-56346f0db779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALL ENGINES'])[1]/following::textarea[1]</value>
      <webElementGuid>0bb6e874-9bac-4420-854b-b2bfa4208364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More Info'])[1]/following::textarea[1]</value>
      <webElementGuid>a8904390-33d3-4a60-a1a7-42199350545f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACES'])[1]/preceding::textarea[1]</value>
      <webElementGuid>681ae341-d042-4f39-9c96-0d7fe27c1e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALL ENGINES'])[2]/preceding::textarea[2]</value>
      <webElementGuid>662c62e5-639e-492c-8bc7-3425bfe23794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Testing_Automation']/parent::*</value>
      <webElementGuid>0c544a60-9f73-4c75-929c-a29a14149f44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>ea51f388-7e46-4ee0-bed0-094248b1dffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$MainContent$GvApplications$ctl02$txtapppartsnotes' and @id = 'MainContent_GvApplications_txtapppartsnotes_0' and (text() = 'Testing_Automation' or . = 'Testing_Automation')]</value>
      <webElementGuid>4cf2242f-7ea5-4120-b52b-ea9b91132975</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
