<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VehicleType_checkAllVehicleType</name>
   <tag></tag>
   <elementGuidId>4c30a1f2-1743-42be-bf5f-adde6488bd3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'checkbox' and @checked = 'checked' and @id = 'checkAllVehicleType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkAllVehicleType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkAllVehicleType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#checkAllVehicleType</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de625a29-bdfc-443d-867a-4f544b7e1a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>25d2fa2b-4db2-49d0-9638-bec9cd150bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>f75d124c-2546-4507-b633-3c51342ffb59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkAllVehicleType</value>
      <webElementGuid>345f9520-b312-4c19-9820-1efafdac0e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkAllVehicleType&quot;)</value>
      <webElementGuid>97f27ff7-d5a9-493a-b038-df359aca556f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkAllVehicleType']</value>
      <webElementGuid>a8270815-8247-4df6-b2da-59cb7d9758e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='VTalllist']/input</value>
      <webElementGuid>bfb5f47c-bcc5-4cd0-b5bd-40f31111194b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[5]/div/input</value>
      <webElementGuid>dc6ac549-7f1b-4a20-800a-6d4dc5c63eeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @checked = 'checked' and @id = 'checkAllVehicleType']</value>
      <webElementGuid>aa0e7b2c-41f9-4583-8411-6466f86f1180</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
