<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_You can select only one Part Descript_824252</name>
   <tag></tag>
   <elementGuidId>74aba155-61e4-43b7-8c8f-d8df5280fa46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#91808</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='91808']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;TestingAutomation&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a08fb27d-739b-4084-95fd-6641357e15e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filterinp PartTypechk</value>
      <webElementGuid>b0e3a925-ed81-49a5-b98b-2c413e990a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>63399d0e-7511-41c1-9798-a5046722df12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>91808</value>
      <webElementGuid>8c5a4284-57b4-4f36-90a2-db1f04863717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>66bedf50-5d19-4da2-a094-fbd607836df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rbCategories</value>
      <webElementGuid>c82f81e6-e8fd-4f29-9815-053c828fcb0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TestingAutomation</value>
      <webElementGuid>db910fe3-83d6-4798-bc2e-7ffdb603acb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;91808&quot;)</value>
      <webElementGuid>48c28281-a825-4454-8cda-44c9ea59be2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='91808']</value>
      <webElementGuid>7538d56f-fce5-4b38-bb01-67438f9c5bc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chkPartTypelist']/li/input</value>
      <webElementGuid>3f42491e-9ad7-4bec-801d-ab406a48dd5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/li/input</value>
      <webElementGuid>c36169b7-a2d3-49a0-9b57-347e0547235f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@checked = 'checked' and @id = '91808' and @type = 'checkbox' and @name = 'rbCategories']</value>
      <webElementGuid>9507021c-8fdf-43b4-9f24-9007d39e3d1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
