<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__checkAllbrand</name>
   <tag></tag>
   <elementGuidId>8a38f674-6819-4006-861e-f99997faa1bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkAllbrand</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkAllbrand']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#checkAllbrand</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f42ac2d-e920-4111-8d85-e54213018114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9168f26f-9acb-4c8f-821e-2fc395a5078f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>d6b07973-c255-4e79-81dd-116c3f895e55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkAllbrand</value>
      <webElementGuid>73bf0fc7-03d8-4dd4-84ca-371048ecfb83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkAllbrand&quot;)</value>
      <webElementGuid>691ec63e-ed72-44dd-95e8-b250999348bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkAllbrand']</value>
      <webElementGuid>dadbf92c-f3aa-4b7c-8d66-5482c4a0c168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Balllist']/input</value>
      <webElementGuid>e99c47ae-e17d-4e09-82ad-5a6313c484f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/div/div/div/input</value>
      <webElementGuid>f0364b30-7ece-4b1c-9db4-033f4bb89a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @checked = 'checked' and @id = 'checkAllbrand']</value>
      <webElementGuid>3fb9f583-4e25-42c6-b4d8-47e3dfd8a6d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
