<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__DrpLine</name>
   <tag></tag>
   <elementGuidId>79a63cc1-bd9e-4a4e-b802-ccf12e1e5d8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DrpLine</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DrpLine']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Line *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2d6e8be3-4154-4c5e-91d8-3152bd72f406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DrpLine</value>
      <webElementGuid>0f964b52-ca6a-49a4-8361-6e6a960f6546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-SELECT-AGD | AGDASE | ASEATE | UniversalAuto | AutoAVN | AVNBBBB | 3MBDDM | GM Customer Care and AftersalesBDDR | Accu Industries IncBDFJ | Air Lift CompanyBDGB |  AGS CompanyBDGS | AP Exhaust TechnologiesBDHZ | AutoMeterBDLK | Gates CorporationBDLS | BorlaBDLV | Robert Bosch LLCBDML | BudgeBDMZ | CAE RemanufacturingBDPJ | CastrolBDRJ | Covercraft IndustriesBDSN | Dee ZeeBDVG | East Penn Manufacturing Company IncBDVK | EGRBDVS | Enginetech IncBDXF | FirestoneBDXW | Ford Motor CompanyBFBQ | GMBBFG | BFGBFGR | K&amp;N Engineering IncBFTR | BendixBFWM | Dorman ProductsBGLB | DRiV IncorporatedBGNQ | Westin AutomotiveBGWL | Dash DesignsBHWR | ARB USABJVK | Quick Fuel TechnologyBKBP | Fabtech MotorsportsBKEM | Lighthouse ProductsBKKG | Car ChemistryBKMM | Crown Automotive Sales CompanyBKRM | AutoZone IncBKSN | Borgeson UniversalBLVW | Holley Performance ProductsBMBG | ADP Distributors IncBQWN | BagshawBWT | Bayerische Motoren Werke AktiengesellschaftCAV | CAVCCAT | catalog syncCCGV | Daimler AGCDXT | DronningborgCHM | CHMCQXK | CRP Industries IncCQXS | Eaton CorporationCRA | CRACRNX | CRNXCTL | CTLCTXB | Smc JascoCustom | CustomCVLH | ThyssenKrupp Automotive GroupD007 | DU7DAI | DAIDCP | DCPDDD | DDDDKSP | Intro-Tech Automotive Inc.DRI | DRIDRO | DRODWKN | CYC EngineeringENK | ENKENW | ENWEOD | end productETE | ETERemanEXP | EXPExportTest | lineF52 | F52FAR | FARZIFAW | FAWFBJS | Eastern Industries IncFGTR | Truck Hero IncGNXP | GNXPGOR | GORGPJG | Husky SpringGRD | GRDGTIN | GTINGTQB |  KTM Sportmotorcycle GmbHGWBT | Ariens CompanyHaldex | PartTestHBLR | ACCU-Form Plastics IncHDPM | Auto Pro USA IncHDR | HDRHKKQ | InMotion PartsHouseHoldLine | House Hold Line 1HPD | HPDHPZN | Fiat Chrysler Automobiles NVHRLZ | American Automobile AssociationHWGW |  First Brands GroupHZJC | Calumet Specialty Products Partners LPICO | ICOKOW | KOWLIGHT | Lightlinecode | linecodeLLL | Line LineLOS | LOSLRG | LRGMAN | TestelineMEV1 | Mevotech LPTTXMKW | MKWMOT2 | MotoThermalMOT4 | Engine ManagementMOT5 | Oil CapsMRW | MRWMTP | MTPMTT | Market tittleNET | NET CHANGESNewLine | New LineNOR | NooverrideNPP | No of PartOPTI | OPTIOZR | OZRpartest | test33PARTS | PARTSPCO | PCOPMT | PMTPMTT | PMTTPOF | POFPTest | PTestRA8 | RA8RAC | RACRBP | RBPRTW | RTWSCH | SCHSDW | SDWSOT | SOTSSSS | SSSSSTD | STDSTG | Stagging TestSWW | SWWTAT | TATTEA | TEATest | Testtest03rk | rkprodtest0504 | testtest0604 | test0604test06042023 | teston06test1 | test1test1204 | testtest2401 | test2401test2501 | test25test2601 | test26Testdata | Linetesting | testingTestline | data Testlines | Testlinestesttest06 | tteessttTIS | TISTOW | TOWTRANS | New attributeTWG | TWGULR | ULRUNIT | UNITUNT | unassVIS | VISVOX | VOXWEL | WELWheel | WheelWPO | WPOXFO | XFOXXR | XXRYTH | YouTech</value>
      <webElementGuid>13b50ba5-cc8f-414b-b3c8-0d1a09b94313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DrpLine&quot;)</value>
      <webElementGuid>55dbbe78-c66a-4a8f-b114-0331c261dcdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DrpLine']</value>
      <webElementGuid>a40f9d3e-086e-45d4-aece-333268f87a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='Linelbldrp']/select</value>
      <webElementGuid>e792ee14-7e19-4576-a6ed-2209dda0648e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[1]</value>
      <webElementGuid>f1d3dc59-353a-4e50-8eac-8abad1b3c60b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ebay :'])[1]/preceding::select[1]</value>
      <webElementGuid>eae8d56c-28ef-4047-92cd-d6aa3b27b436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interchange :'])[1]/preceding::select[2]</value>
      <webElementGuid>55fb5e91-46cd-476c-820e-bb16fbc78e24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>632a1b00-9db3-4a98-bb07-96ba4bacae42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DrpLine' and (text() = '-SELECT-AGD | AGDASE | ASEATE | UniversalAuto | AutoAVN | AVNBBBB | 3MBDDM | GM Customer Care and AftersalesBDDR | Accu Industries IncBDFJ | Air Lift CompanyBDGB |  AGS CompanyBDGS | AP Exhaust TechnologiesBDHZ | AutoMeterBDLK | Gates CorporationBDLS | BorlaBDLV | Robert Bosch LLCBDML | BudgeBDMZ | CAE RemanufacturingBDPJ | CastrolBDRJ | Covercraft IndustriesBDSN | Dee ZeeBDVG | East Penn Manufacturing Company IncBDVK | EGRBDVS | Enginetech IncBDXF | FirestoneBDXW | Ford Motor CompanyBFBQ | GMBBFG | BFGBFGR | K&amp;N Engineering IncBFTR | BendixBFWM | Dorman ProductsBGLB | DRiV IncorporatedBGNQ | Westin AutomotiveBGWL | Dash DesignsBHWR | ARB USABJVK | Quick Fuel TechnologyBKBP | Fabtech MotorsportsBKEM | Lighthouse ProductsBKKG | Car ChemistryBKMM | Crown Automotive Sales CompanyBKRM | AutoZone IncBKSN | Borgeson UniversalBLVW | Holley Performance ProductsBMBG | ADP Distributors IncBQWN | BagshawBWT | Bayerische Motoren Werke AktiengesellschaftCAV | CAVCCAT | catalog syncCCGV | Daimler AGCDXT | DronningborgCHM | CHMCQXK | CRP Industries IncCQXS | Eaton CorporationCRA | CRACRNX | CRNXCTL | CTLCTXB | Smc JascoCustom | CustomCVLH | ThyssenKrupp Automotive GroupD007 | DU7DAI | DAIDCP | DCPDDD | DDDDKSP | Intro-Tech Automotive Inc.DRI | DRIDRO | DRODWKN | CYC EngineeringENK | ENKENW | ENWEOD | end productETE | ETERemanEXP | EXPExportTest | lineF52 | F52FAR | FARZIFAW | FAWFBJS | Eastern Industries IncFGTR | Truck Hero IncGNXP | GNXPGOR | GORGPJG | Husky SpringGRD | GRDGTIN | GTINGTQB |  KTM Sportmotorcycle GmbHGWBT | Ariens CompanyHaldex | PartTestHBLR | ACCU-Form Plastics IncHDPM | Auto Pro USA IncHDR | HDRHKKQ | InMotion PartsHouseHoldLine | House Hold Line 1HPD | HPDHPZN | Fiat Chrysler Automobiles NVHRLZ | American Automobile AssociationHWGW |  First Brands GroupHZJC | Calumet Specialty Products Partners LPICO | ICOKOW | KOWLIGHT | Lightlinecode | linecodeLLL | Line LineLOS | LOSLRG | LRGMAN | TestelineMEV1 | Mevotech LPTTXMKW | MKWMOT2 | MotoThermalMOT4 | Engine ManagementMOT5 | Oil CapsMRW | MRWMTP | MTPMTT | Market tittleNET | NET CHANGESNewLine | New LineNOR | NooverrideNPP | No of PartOPTI | OPTIOZR | OZRpartest | test33PARTS | PARTSPCO | PCOPMT | PMTPMTT | PMTTPOF | POFPTest | PTestRA8 | RA8RAC | RACRBP | RBPRTW | RTWSCH | SCHSDW | SDWSOT | SOTSSSS | SSSSSTD | STDSTG | Stagging TestSWW | SWWTAT | TATTEA | TEATest | Testtest03rk | rkprodtest0504 | testtest0604 | test0604test06042023 | teston06test1 | test1test1204 | testtest2401 | test2401test2501 | test25test2601 | test26Testdata | Linetesting | testingTestline | data Testlines | Testlinestesttest06 | tteessttTIS | TISTOW | TOWTRANS | New attributeTWG | TWGULR | ULRUNIT | UNITUNT | unassVIS | VISVOX | VOXWEL | WELWheel | WheelWPO | WPOXFO | XFOXXR | XXRYTH | YouTech' or . = '-SELECT-AGD | AGDASE | ASEATE | UniversalAuto | AutoAVN | AVNBBBB | 3MBDDM | GM Customer Care and AftersalesBDDR | Accu Industries IncBDFJ | Air Lift CompanyBDGB |  AGS CompanyBDGS | AP Exhaust TechnologiesBDHZ | AutoMeterBDLK | Gates CorporationBDLS | BorlaBDLV | Robert Bosch LLCBDML | BudgeBDMZ | CAE RemanufacturingBDPJ | CastrolBDRJ | Covercraft IndustriesBDSN | Dee ZeeBDVG | East Penn Manufacturing Company IncBDVK | EGRBDVS | Enginetech IncBDXF | FirestoneBDXW | Ford Motor CompanyBFBQ | GMBBFG | BFGBFGR | K&amp;N Engineering IncBFTR | BendixBFWM | Dorman ProductsBGLB | DRiV IncorporatedBGNQ | Westin AutomotiveBGWL | Dash DesignsBHWR | ARB USABJVK | Quick Fuel TechnologyBKBP | Fabtech MotorsportsBKEM | Lighthouse ProductsBKKG | Car ChemistryBKMM | Crown Automotive Sales CompanyBKRM | AutoZone IncBKSN | Borgeson UniversalBLVW | Holley Performance ProductsBMBG | ADP Distributors IncBQWN | BagshawBWT | Bayerische Motoren Werke AktiengesellschaftCAV | CAVCCAT | catalog syncCCGV | Daimler AGCDXT | DronningborgCHM | CHMCQXK | CRP Industries IncCQXS | Eaton CorporationCRA | CRACRNX | CRNXCTL | CTLCTXB | Smc JascoCustom | CustomCVLH | ThyssenKrupp Automotive GroupD007 | DU7DAI | DAIDCP | DCPDDD | DDDDKSP | Intro-Tech Automotive Inc.DRI | DRIDRO | DRODWKN | CYC EngineeringENK | ENKENW | ENWEOD | end productETE | ETERemanEXP | EXPExportTest | lineF52 | F52FAR | FARZIFAW | FAWFBJS | Eastern Industries IncFGTR | Truck Hero IncGNXP | GNXPGOR | GORGPJG | Husky SpringGRD | GRDGTIN | GTINGTQB |  KTM Sportmotorcycle GmbHGWBT | Ariens CompanyHaldex | PartTestHBLR | ACCU-Form Plastics IncHDPM | Auto Pro USA IncHDR | HDRHKKQ | InMotion PartsHouseHoldLine | House Hold Line 1HPD | HPDHPZN | Fiat Chrysler Automobiles NVHRLZ | American Automobile AssociationHWGW |  First Brands GroupHZJC | Calumet Specialty Products Partners LPICO | ICOKOW | KOWLIGHT | Lightlinecode | linecodeLLL | Line LineLOS | LOSLRG | LRGMAN | TestelineMEV1 | Mevotech LPTTXMKW | MKWMOT2 | MotoThermalMOT4 | Engine ManagementMOT5 | Oil CapsMRW | MRWMTP | MTPMTT | Market tittleNET | NET CHANGESNewLine | New LineNOR | NooverrideNPP | No of PartOPTI | OPTIOZR | OZRpartest | test33PARTS | PARTSPCO | PCOPMT | PMTPMTT | PMTTPOF | POFPTest | PTestRA8 | RA8RAC | RACRBP | RBPRTW | RTWSCH | SCHSDW | SDWSOT | SOTSSSS | SSSSSTD | STDSTG | Stagging TestSWW | SWWTAT | TATTEA | TEATest | Testtest03rk | rkprodtest0504 | testtest0604 | test0604test06042023 | teston06test1 | test1test1204 | testtest2401 | test2401test2501 | test25test2601 | test26Testdata | Linetesting | testingTestline | data Testlines | Testlinestesttest06 | tteessttTIS | TISTOW | TOWTRANS | New attributeTWG | TWGULR | ULRUNIT | UNITUNT | unassVIS | VISVOX | VOXWEL | WELWheel | WheelWPO | WPOXFO | XFOXXR | XXRYTH | YouTech')]</value>
      <webElementGuid>28179114-efd8-4d35-82ce-f83ef3e44f14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
