<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_If you have more than 1,048,576 rows_517df0</name>
   <tag></tag>
   <elementGuidId>10c6b490-4810-45a7-80da-a32ba810d0c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ExcelExport']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ExcelExport</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Generate Excel&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5fae070b-a0c5-4e15-80be-2d7d49760cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ExcelExport</value>
      <webElementGuid>3b5275cd-ffaa-4537-b915-953513620663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Exportbutton</value>
      <webElementGuid>b1e47424-8f1e-48fe-9612-75d8bb252a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2729975f-7c52-4564-b226-3ef6196ecdf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>getExcel()</value>
      <webElementGuid>5581e659-0d38-4ad9-b605-26b6775f6aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generate Excel</value>
      <webElementGuid>44b01854-e9d6-4ac7-9136-3381bf15a97a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExcelExport&quot;)</value>
      <webElementGuid>99005e99-4dfe-4a72-9ab4-59eaf55e02c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ExcelExport']</value>
      <webElementGuid>eaa7ebbe-417e-4f14-8ddb-3e8b58dbe819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Bottomdata']/div[3]/button</value>
      <webElementGuid>ac78d4da-593e-4bd0-81d6-fd0db9053fc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='If you have more than 1,048,576 rows, use CSV to export.'])[1]/following::button[1]</value>
      <webElementGuid>c4cba25d-be6b-4fc4-870d-547e3ad1b4ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable this field to exclude the overlapping records in the export you want to generate'])[1]/following::button[1]</value>
      <webElementGuid>055af914-251c-48c1-9bc7-228fe8ba5ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate CSV'])[1]/preceding::button[1]</value>
      <webElementGuid>2b552d30-8196-4e46-ab1f-1cd973a1ac55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate XML'])[1]/preceding::button[7]</value>
      <webElementGuid>eabedd5a-cf11-4ae3-aa69-9580a69c3763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Generate Excel']/parent::*</value>
      <webElementGuid>5e147c7a-1784-44e9-8b59-01896ab529a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>bc80ed47-e361-4b6f-9955-8e28b9c12e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ExcelExport' and @type = 'button' and (text() = 'Generate Excel' or . = 'Generate Excel')]</value>
      <webElementGuid>b5c7b45c-161a-46b1-9110-30ec47e2d568</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
