<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Generate Excel_CSVExport</name>
   <tag></tag>
   <elementGuidId>d5256cd7-7e3c-496e-a717-fd1fd5cc16db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='CSVExport']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CSVExport</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Generate CSV&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>42f011a8-91fe-486a-bd4c-f77b3f636b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CSVExport</value>
      <webElementGuid>04ecfb0c-3529-4cef-bcfd-c7e9d7535331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Exportbutton</value>
      <webElementGuid>0e2c9f74-f732-4c14-97e2-8c68e5430940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5357d682-6eb9-4bd0-9b18-c2ee5c701fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>getcsv()</value>
      <webElementGuid>21def1b5-06f2-4253-ac86-86775bc5ab99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generate CSV</value>
      <webElementGuid>94d96a3f-1e3f-4cb1-ab42-fafa29ab66d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CSVExport&quot;)</value>
      <webElementGuid>5743f163-fa2d-4d85-9aa9-01ff767c1bef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='CSVExport']</value>
      <webElementGuid>2b8ad13f-479f-4333-b056-0b4869d6f195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Bottomdata']/div[3]/button[2]</value>
      <webElementGuid>ed84fc23-eaf7-461e-ae77-01ffd550d811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate Excel'])[1]/following::button[1]</value>
      <webElementGuid>d9d5e776-d9a8-4e88-8d4b-795acd143165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='If you have more than 1,048,576 rows, use CSV to export.'])[1]/following::button[2]</value>
      <webElementGuid>90eef0da-119a-47b7-93f9-b4357d0cfa12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate XML'])[1]/preceding::button[6]</value>
      <webElementGuid>5183afc3-503e-4655-8c33-88c4bcf93517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Would you like to save the settings selected for this export for future use?'])[1]/preceding::button[10]</value>
      <webElementGuid>5413034f-6f7a-4b8d-852b-13cecd484001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Generate CSV']/parent::*</value>
      <webElementGuid>57a261ac-8ebd-4c5e-9d41-54adcf668f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button[2]</value>
      <webElementGuid>d99f7dd6-6ca8-424f-9aeb-4f34149058de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'CSVExport' and @type = 'button' and (text() = 'Generate CSV' or . = 'Generate CSV')]</value>
      <webElementGuid>d534a631-e874-4980-a38f-a23e6ede6dd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
