<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BBCW_save_btn_new_add</name>
   <tag></tag>
   <elementGuidId>202e870f-f6f9-45be-b7a4-cbff506bf21e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#save_btn_new_add</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='save_btn_new_add']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#save_btn_new_add</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a1c87405-4ab2-4da3-8115-62bc234f2546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>save_btn_new_add</value>
      <webElementGuid>24fac843-5762-4738-9bd2-c44eec2b9c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>btnaddSave_Click()</value>
      <webElementGuid>5921f0e1-fe55-4849-be50-88637565db88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>save display_inline_notimp</value>
      <webElementGuid>9c3dd5a6-5b73-4e7a-b05c-1e6d142dce91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>c2ec555f-60b0-4c82-bedd-55258c1a9237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;save_btn_new_add&quot;)</value>
      <webElementGuid>8ddefc1c-e359-4d3d-a235-0f2b1c7c82e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='save_btn_new_add']</value>
      <webElementGuid>1be19b1d-c5d3-4078-8c98-2c9db36d4f81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='saveandresettr']/td/div</value>
      <webElementGuid>dd9d38bd-d0ca-4ed6-8918-3c6dc7086925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BBCW'])[1]/following::div[1]</value>
      <webElementGuid>b95a4cfd-bc16-4a90-860a-2b636d22979f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand AAIA ID'])[1]/following::div[1]</value>
      <webElementGuid>7dcf97da-a2bb-46ee-8075-3a09ceca48f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[2]/preceding::div[1]</value>
      <webElementGuid>ed50abf1-1d0a-4191-8d20-e249a8b97721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/preceding::div[2]</value>
      <webElementGuid>915654c3-71c7-4530-87e9-bcb75cffed8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>b81c8caa-3a32-4520-b69a-9f4797dae211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td/div</value>
      <webElementGuid>4a650b06-8f18-4344-84f6-de4d6359470f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'save_btn_new_add' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>0a0a83e2-a8b0-4b41-852e-6d4788737b56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
