<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>feb4720c-a393-4811-a475-6ccb4e012c89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Interchange > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Interchange']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Interchange >> internal:role=img >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a48dfe99-167a-48e0-9342-b1ab5036696d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//bddemo.apapmt.com/Images/New_design_img/parts_interchange1.png</value>
      <webElementGuid>de96763b-a2b9-46c7-89da-10bbbeef59f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Interchange&quot;)/img[1]</value>
      <webElementGuid>d8bc17ca-c4e4-4886-80c6-6e7004f2fe3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Interchange']/img</value>
      <webElementGuid>2d0863fd-c576-4dfd-86d2-bf6b9eccafc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/img</value>
      <webElementGuid>51716520-30c5-4633-b740-75c16bb61344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//bddemo.apapmt.com/Images/New_design_img/parts_interchange1.png']</value>
      <webElementGuid>f99b300d-a5c0-43a1-bef5-c8f4d4a45ddc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
