<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search By_txtsearchpartno</name>
   <tag></tag>
   <elementGuidId>6a18aef5-8d4a-4d4d-9d8b-7d6e6bdfb6c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtsearchpartno']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtsearchpartno</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Enter your part number&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>55b368d9-abfe-48ea-87a9-dee9d368ec0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a8958016-125e-4685-bbd6-42ba7da030b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtsearchpartno</value>
      <webElementGuid>28cd122c-d0d2-4d64-9e76-c99724629868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>8a0e0627-5686-4e2d-974e-91454f273e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input</value>
      <webElementGuid>fdc86b92-680a-4a77-9f2b-1f787663ca18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>LoadSearchByPartNo(this)</value>
      <webElementGuid>282ecacf-4f17-40e9-bac9-162a1f0ea02b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>LoadCompNo(this)</value>
      <webElementGuid>6fed1a15-fcfc-4ea5-b0c8-5b5f45c53fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your part number</value>
      <webElementGuid>884a35c1-cd12-462d-ade9-e276ae0d09b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9672e4c2-d7b5-40ba-9009-6b389e797c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtsearchpartno&quot;)</value>
      <webElementGuid>125e9380-0a32-4666-9356-bc1e6bc2ee51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtsearchpartno']</value>
      <webElementGuid>02fd8e7f-d937-4fde-9e97-b913bfd7ff7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_upAttribute']/div[2]/div/div/div[3]/div/div[2]/input</value>
      <webElementGuid>f39786aa-ddfa-48a4-aea8-e8e4cee589e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/div[2]/input</value>
      <webElementGuid>9d8723eb-72a2-49f2-b858-6d0be17cb071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtsearchpartno' and @placeholder = 'Enter your part number']</value>
      <webElementGuid>8cfb65ce-8369-4a27-9bf5-2690ca9091bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
