<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Forgot Password_btnLogin</name>
   <tag></tag>
   <elementGuidId>9cdf06d5-6109-4a27-b2bd-21e6efdd263e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnLogin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnLogin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Submit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>317050fd-7997-42b1-a75c-ba5e8633e13b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ebfc9259-8ba4-4b7f-9660-b3f49788f697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnLogin</value>
      <webElementGuid>505bd687-c452-47c5-9bae-dfcf04d1a279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>ddfa5c11-1123-4ebf-a428-04832146406c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnLogin</value>
      <webElementGuid>2cd0a6fe-0bf2-4b96-9ce8-5cb946d734bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-button</value>
      <webElementGuid>cef983c0-23bc-4bb1-b28b-f23065ee77e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnLogin&quot;)</value>
      <webElementGuid>c60524b7-5c6c-4cfa-a3d2-4463ad9adc5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnLogin']</value>
      <webElementGuid>4270042c-29c5-4cc8-a129-33fb587ea0bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admin_login_main']/div[6]/input</value>
      <webElementGuid>3e60e141-802b-4c4e-b8f0-acfa6ef6cdfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>922b4d74-f403-4f08-996a-6a6942a4a13d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'btnLogin' and @id = 'btnLogin']</value>
      <webElementGuid>b33b08f0-7219-4018-a274-4148b71c736b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
