<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Component Brand ID_drpCbrandID</name>
   <tag></tag>
   <elementGuidId>fd22a8a3-7310-4e04-a004-448d3e20bb52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drpCbrandID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='drpCbrandID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter your Component Brand ID&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9fea3d9b-7779-47b8-9941-4bfee210bff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8eb4690e-a564-426a-9c54-7d0be0c7c525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drpCbrandID</value>
      <webElementGuid>7cc4fb08-547b-4e97-bfe1-ad35a3943d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input field_input</value>
      <webElementGuid>0c2152f9-8485-41ac-b2b6-5225166f03e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your Component Brand ID</value>
      <webElementGuid>88d029e4-2f6a-4130-a8d2-98d3fc2dfb7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>ComponentBrandID(this);</value>
      <webElementGuid>84bcc6d3-a213-4bd3-b4fa-72467237a0d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e9e19ded-d70e-410b-b7cf-9773af7fdfc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drpCbrandID&quot;)</value>
      <webElementGuid>7c2bda14-6ced-4243-a8bf-ae9b35d22fc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='drpCbrandID']</value>
      <webElementGuid>1830b548-b053-4140-b2e8-da4011abaa2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div[2]/div[2]/div[3]/div[8]/input</value>
      <webElementGuid>76699efc-53b5-4696-ade3-214cfc488e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>c0b005b1-f11c-4bdb-89f4-325690131cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'drpCbrandID' and @placeholder = 'Enter your Component Brand ID']</value>
      <webElementGuid>5194e24b-9aff-45ba-9809-45b9616ad4f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
