<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Component Brand ID_drpCbrandID</name>
   <tag></tag>
   <elementGuidId>fd22a8a3-7310-4e04-a004-448d3e20bb52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drpCbrandID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@placeholder = 'Enter your Component Brand ID']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@placeholder = 'Enter your Component Brand ID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter your Component Brand ID&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>053ffa32-afce-4487-a56a-bd7ab469fac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0ab7874d-f02d-4b6e-bdaa-c43b8c8732fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drpCbrandID</value>
      <webElementGuid>4234eb47-6939-4397-9013-059c248aee80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input field_input</value>
      <webElementGuid>4761f7e6-6d0e-422d-9c47-898ca0d92d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your Component Brand ID</value>
      <webElementGuid>d3dc8f97-42b2-42a6-9ec4-b345cac42d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>ComponentBrandID(this);</value>
      <webElementGuid>c2b3f8be-2260-49ae-a7de-8a7a4c49541e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1c6010d5-98ac-4232-bd23-bb461a234d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drpCbrandID&quot;)</value>
      <webElementGuid>656673e2-24d0-4452-ace5-57d647c7dd72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='drpCbrandID']</value>
      <webElementGuid>bf7d0129-ee10-4237-a89d-464e3bf3b48f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div[2]/div[2]/div[3]/div[8]/input</value>
      <webElementGuid>90d9996f-da53-4379-b0cd-b30d87b00dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>a1012023-f019-41ae-8b15-2ebe125fca95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'drpCbrandID' and @placeholder = 'Enter your Component Brand ID']</value>
      <webElementGuid>b7ac1b20-c3f0-4160-bc45-d79eff590c94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
