<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__drpSoldSeperately</name>
   <tag></tag>
   <elementGuidId>bdb409e3-2e74-4c4b-87e2-9f13a7ce4eee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drpSoldSeperately</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='drpSoldSeperately']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#drpSoldSeperately</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>49e54414-ac39-4c5e-bb94-0412956ec4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drpSoldSeperately</value>
      <webElementGuid>a780ed6b-a21a-46cd-bae6-7899b2b4bf57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_select</value>
      <webElementGuid>9944226d-4956-4a64-9277-0012eda706eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    &lt;----Select---->
                    YES
                    NO
                </value>
      <webElementGuid>eeefd407-fbf6-4d8e-8352-cf05c2deaebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drpSoldSeperately&quot;)</value>
      <webElementGuid>b9e05e8b-1caa-4c49-876f-28331f2cc7da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='drpSoldSeperately']</value>
      <webElementGuid>bb36c5b9-65b6-460f-aec6-203bbaebb4f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div[2]/div[2]/div[3]/div[13]/select</value>
      <webElementGuid>f0959b2e-42ef-4a14-90b9-3bee489363f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[13]/following::select[1]</value>
      <webElementGuid>1add5712-e3f3-482f-ac88-5542d2f063c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Component Part Terminology ID'])[1]/preceding::select[1]</value>
      <webElementGuid>cfdec418-aa7f-4383-afb8-0edcf9c9bc49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/select</value>
      <webElementGuid>bf7ebf1e-098e-4d99-ae76-11e184e349d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'drpSoldSeperately' and (text() = '
                    &lt;----Select---->
                    YES
                    NO
                ' or . = '
                    &lt;----Select---->
                    YES
                    NO
                ')]</value>
      <webElementGuid>660c57b2-24c8-4419-a243-1e01f2c1d29e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
