<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Required_txt_CompetitorPartno</name>
   <tag></tag>
   <elementGuidId>0e3cd10c-0538-442e-aa3e-4a5db65bc281</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_CompetitorPartno</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_CompetitorPartno']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txt_CompetitorPartno</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34d0c5b0-69b8-4a29-8f02-3d19dc6fb0aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>37c070e4-bfef-4fc1-9811-6d5a79044831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_CompetitorPartno</value>
      <webElementGuid>d027e98f-5f15-4fae-9fb1-3a92fae12f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-validation field_input</value>
      <webElementGuid>66937bbe-7b89-42c5-8357-61c0f62cf86a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>IchangePartnoValidate(this)</value>
      <webElementGuid>983c72aa-5d5a-40de-a123-6c6dabda98ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_CompetitorPartno&quot;)</value>
      <webElementGuid>c4e662a3-3c18-4068-a5f0-00ef73da9bcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_CompetitorPartno']</value>
      <webElementGuid>8e9798e8-de53-42c1-8791-f7cb157af53a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DataCorner']/div/div[2]/input</value>
      <webElementGuid>ddc620dc-ced8-485a-b10d-de2302f3b712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/input</value>
      <webElementGuid>8e0a9265-d673-4eec-ba1a-8cf20844896b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txt_CompetitorPartno']</value>
      <webElementGuid>4e68c06e-0d48-4cc3-91f2-025db104d1f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
