<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Action_glowing-border_1</name>
   <tag></tag>
   <elementGuidId>337365e3-3991-4c4e-b49c-1004636667b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th:nth-of-type(6) > input.glowing-border</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[30]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Price UOM&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad4d7c74-ee7c-4517-b9d1-2e7b6881c8b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glowing-border</value>
      <webElementGuid>b39a136e-ee8c-4912-8974-e8da84eeb6f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>58086e4b-e8a2-4ffc-95ad-8a0940890e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Price UOM</value>
      <webElementGuid>1272ef0d-87f0-4f1a-b486-1deda6e43972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTableViewer&quot;)/tfoot[1]/tr[1]/th[6]/input[@class=&quot;glowing-border&quot;]</value>
      <webElementGuid>d6778ba0-74be-427f-a663-1036bcfdd894</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[30]</value>
      <webElementGuid>b08d146f-f607-47db-82db-98d658a34be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTableViewer']/tfoot/tr/th[6]/input</value>
      <webElementGuid>f2030a8c-abd7-4587-85e4-d83a174226e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[6]/input</value>
      <webElementGuid>57b1e594-b5c7-4823-a518-82d4096cc0a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Price UOM']</value>
      <webElementGuid>cf353e12-a08f-49e3-a462-71ed7e18311d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
