<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Equipment_ucMenu_rptLevel1_lnkLink1_3</name>
   <tag></tag>
   <elementGuidId>143bb510-db49-4b8d-8af4-51e8000ddb74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucMenu_rptLevel1_lnkLink1_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucMenu_rptLevel1_lnkLink1_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Parts&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a00a9435-006f-4fa2-9d47-e2de9bdbc3cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucMenu_rptLevel1_lnkLink1_3</value>
      <webElementGuid>b30e7ae0-e26b-4a81-8fb5-70fbc22f4f2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main_menu parts_icon active</value>
      <webElementGuid>96116681-ab49-4242-b868-3aeb485a57f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../Parts/parts.aspx?PageTitle=Parts Data</value>
      <webElementGuid>5692b87d-3501-4372-b16b-fd0ed4217e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Parts</value>
      <webElementGuid>94333c2a-a45e-46c6-92d4-710ab14dfacc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucMenu_rptLevel1_lnkLink1_3&quot;)</value>
      <webElementGuid>ece9743d-3275-419d-ad9e-103eb4a7851e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucMenu_rptLevel1_lnkLink1_3']</value>
      <webElementGuid>a35efae9-fe2b-4643-ae39-fa852ef60404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='ucMenu_rptLevel1_l1_3']/a</value>
      <webElementGuid>ac541ca3-be6a-46d3-b06e-5997aa51a600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Parts')]</value>
      <webElementGuid>485a6005-776f-4a6a-b18d-2fae0f0e1254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Equipment'])[1]/following::a[1]</value>
      <webElementGuid>2ddfef0e-7eab-4af3-8452-5db0b2a10f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle'])[1]/following::a[2]</value>
      <webElementGuid>50623fa6-7a8b-4684-9b4f-371183e2073d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export Data'])[1]/preceding::a[1]</value>
      <webElementGuid>91a50e11-aa1f-4a88-97ec-6ba1b011d43c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Catalogs'])[1]/preceding::a[2]</value>
      <webElementGuid>0c20f385-a603-46a7-a9c5-8aec29cf0087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Parts']/parent::*</value>
      <webElementGuid>a4f04fac-4996-4c03-a590-b0d0df6b6543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '../Parts/parts.aspx?PageTitle=Parts Data')]</value>
      <webElementGuid>7ecf4173-2df4-4eeb-9096-3ed59521db09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>42779c9b-4795-48c2-a87a-a3a096f87804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucMenu_rptLevel1_lnkLink1_3' and @href = '../Parts/parts.aspx?PageTitle=Parts Data' and (text() = 'Parts' or . = 'Parts')]</value>
      <webElementGuid>efbe4234-b5c6-4640-9e75-e446117dfcf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
