<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>3fff945f-3da6-4b53-8731-b6e3bf54d9b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='piespages']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>35176708-b7fd-492b-8d36-5814a2cce69f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../Parts/BuyersGuideEnginebase_New.aspx?PartID=191&amp;Category=Electrical%2C%20Lighting%20and%20Body&amp;Subcategory=Lighting%20-%20Instrumentation&amp;PartDescription=Check%20Engine%20Light&amp;Partno=Test%20part-6&amp;PageTitle=Parts+Application Data &amp;Productdescid=3&amp;qty=1</value>
      <webElementGuid>e3fdca27-13aa-403d-aa75-b85770a5aeec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;piespages&quot;)/iframe[1]</value>
      <webElementGuid>1baa1f10-e357-4eb2-9c3b-1e5c1209a59a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/iframe</value>
      <webElementGuid>0d83a4c5-ed94-4614-81d1-c11ad08512f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>bd832c5d-ef15-4acb-9781-b853aecf188b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '../Parts/BuyersGuideEnginebase_New.aspx?PartID=191&amp;Category=Electrical%2C%20Lighting%20and%20Body&amp;Subcategory=Lighting%20-%20Instrumentation&amp;PartDescription=Check%20Engine%20Light&amp;Partno=Test%20part-6&amp;PageTitle=Parts+Application Data &amp;Productdescid=3&amp;qty=1']</value>
      <webElementGuid>5cc1f5b4-81cd-4ffe-ae07-47de28fd38f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
