<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_View QDB_chk_appparts Katalon</name>
   <tag></tag>
   <elementGuidId>0656c090-84fa-4061-ac08-04983d976e7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chk_appparts</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>( //tr[td[contains(text(), 'Katalon')]]//input[@type='checkbox'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8cd46e8c-deb3-4850-855a-1e652c8a1e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1a1a2631-87e6-4d0f-a16f-437debcd4a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chk_appparts</value>
      <webElementGuid>d6d14498-7488-41a4-9b18-ddeeae1f02e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$checkbox2</value>
      <webElementGuid>442cc5fc-2692-4586-b6ab-ccc9212495e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chkAccId</value>
      <webElementGuid>1faa8af7-3378-49c1-a720-fd34482fe7b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1378987</value>
      <webElementGuid>7a215e57-c689-4f3d-b5ce-b3e72f8e7d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chk_appparts&quot;)</value>
      <webElementGuid>c15f609b-ef1e-4235-aa7e-7e782347d950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Parts segment/Application/delete new application/Page_DemoPMT/iframe</value>
      <webElementGuid>50c748fe-5930-4653-9168-fe27063e2d39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='chk_appparts']</value>
      <webElementGuid>50e034d7-6ad2-467b-93b1-18b53bc9cdfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr_0']/td[14]/input</value>
      <webElementGuid>855d46bd-3ce5-4678-8387-8f17fd4f0007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[14]/input</value>
      <webElementGuid>8904e16c-1b68-4d3a-bd9b-d4f0d3ab46e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'chk_appparts' and @name = 'ctl00$MainContent$checkbox2']</value>
      <webElementGuid>e0104667-f80c-45cf-a100-c98d5598dbf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
