<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_View QDB_chk_appparts Attribute remove</name>
   <tag></tag>
   <elementGuidId>40ad5d90-509f-420e-bfcc-49a2ca4d9d7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chk_appparts</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>( //tr[td[contains(text(), 'Attribute remove')]]//input[@type='checkbox'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89e687d7-0b5a-4e25-bee8-1ee1ff297b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>58b761c5-2696-42be-9d9c-c475a0f1e33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chk_appparts</value>
      <webElementGuid>55862ce4-505a-491f-9f2e-458f2f9b505f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$checkbox2</value>
      <webElementGuid>f35df17c-e96a-4405-b70a-6b9712f07f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chkAccId</value>
      <webElementGuid>3f09eb8c-21ad-4f74-8f50-31c408281faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1378987</value>
      <webElementGuid>f6b2d32f-ecc6-4c0c-a79e-abf66e6bf6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chk_appparts&quot;)</value>
      <webElementGuid>2e058442-b74a-45ac-aa5f-1331d6138d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Parts segment/Application/delete new application/Page_DemoPMT/iframe</value>
      <webElementGuid>e7a109d8-88ba-4e70-b27d-f82fa3900c11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='chk_appparts']</value>
      <webElementGuid>6684e124-3c00-4e69-a0e8-f725f864bca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr_0']/td[14]/input</value>
      <webElementGuid>a6b7add7-7d0b-45d5-9aa5-5d93cc5a59b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[14]/input</value>
      <webElementGuid>0791b5b8-62b3-448c-b7db-67805da57ea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'chk_appparts' and @name = 'ctl00$MainContent$checkbox2']</value>
      <webElementGuid>86f058d3-97e1-45c3-8a24-ad26ed06a85b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
