<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Edit_apppartdelete</name>
   <tag></tag>
   <elementGuidId>db286da0-4c0d-4f54-9c14-455087dfc6a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th.sorting_disabled > #apppartdelete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='apppartdelete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e50238e4-6d7f-43a3-b8e5-61dcb2e10a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>2b5070cd-c733-457e-9e35-01d797a59af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apppartdelete</value>
      <webElementGuid>a35c0d67-351c-48d6-99c0-906f67aba9da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//newdemo.apapmt.com/Images/delete_red.png</value>
      <webElementGuid>e5f2b7e8-5569-4dfd-8018-8171d2d3093e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbl_apppartstable_wrapper&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;dataTables_scroll&quot;]/div[@class=&quot;dataTables_scrollHead&quot;]/div[@class=&quot;dataTables_scrollHeadInner&quot;]/table[@class=&quot;table table-striped table-bordered display nowrap dataTable&quot;]/thead[1]/tr[1]/th[@class=&quot;sorting_disabled&quot;]/input[@id=&quot;apppartdelete&quot;]</value>
      <webElementGuid>d31f059c-7edf-4d92-9124-240ca8a3fa55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Parts segment/Application/delete new application/Page_DemoPMT/iframe</value>
      <webElementGuid>f31e221d-7948-46c8-aa39-1339a9f31f2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='apppartdelete']</value>
      <webElementGuid>9eb9c0bc-858a-41d1-a5df-b11c2ce52cff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tbl_apppartstable_wrapper']/div[2]/div/div/div/div/table/thead/tr/th[14]/input</value>
      <webElementGuid>94884c3d-fb7e-42be-977d-6fe7b09bbca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[14]/input</value>
      <webElementGuid>092321ea-5f0e-4de3-a7a3-36d5a14ac516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @id = 'apppartdelete' and @src = '//newdemo.apapmt.com/Images/delete_red.png']</value>
      <webElementGuid>4dd73d4d-ba15-4d62-be27-46b9206cd055</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
