<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Delete_glowing-border</name>
   <tag></tag>
   <elementGuidId>9427f1d8-112d-4d1d-af45-8588c5eb0fff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th:nth-of-type(3) > input.glowing-border</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[29]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Sub Brand Name&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28632452-dc95-4645-9017-e81319b4baa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glowing-border</value>
      <webElementGuid>c00928a1-aa68-4757-9cca-4eee7e525833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>854958ec-5db1-43a1-bc53-92c93234055f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Sub Brand Name</value>
      <webElementGuid>723997f9-0b03-4ca1-835d-506a019f5282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTableViewer&quot;)/tfoot[1]/tr[1]/th[3]/input[@class=&quot;glowing-border&quot;]</value>
      <webElementGuid>2333a544-21cd-4321-80f1-1d074afd618c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[29]</value>
      <webElementGuid>4fa6a2ed-3cdf-4880-ac7e-083793430e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTableViewer']/tfoot/tr/th[3]/input</value>
      <webElementGuid>40732f1b-8103-45fc-9d52-432b6fdd86be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/input</value>
      <webElementGuid>f3904730-6a18-4d65-bae8-000ac9457345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Sub Brand Name']</value>
      <webElementGuid>b7ce9a2b-ee6b-48f3-8d1f-a03500165e21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
