<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_image</name>
   <tag></tag>
   <elementGuidId>ddbfbe73-44b5-48b8-ad4b-8be7fb3855ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(6) > div > input[type=&quot;image&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//*[@style='text-align:center;width:100px;']//input[@type='image'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Submit&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>38c81878-aa23-47e2-9f44-aa31e5a24e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>db9343c4-90ef-4439-b5cb-5aecbf1bd36b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//bddemo.apapmt.com/Images/edit_black.png</value>
      <webElementGuid>b53f77f1-842f-4c9b-a57b-c63282ba498b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return EditBrand('352893','BBCW','AGS','FBHS','NiCopp');</value>
      <webElementGuid>b782c42a-0155-4f0e-a3f5-68a195720aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTableViewer&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[6]/div[1]/input[1]</value>
      <webElementGuid>f3cbc257-40e2-4e4a-9a26-efe96dde6f7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='image'])[3]</value>
      <webElementGuid>11c499ae-279f-4426-ad19-57f90ff522d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTableViewer']/tbody/tr/td[6]/div/input</value>
      <webElementGuid>ab79f6fa-ea2b-482a-b03c-1c2d3d192d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/input</value>
      <webElementGuid>41abc51c-b98a-41af-9dac-4d7eb6e0e5a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @src = '//bddemo.apapmt.com/Images/edit_black.png']</value>
      <webElementGuid>bc31ff8a-b52c-4b38-910c-f7279e66ab3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
