<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Generate Excel_CSVExport</name>
   <tag></tag>
   <elementGuidId>70efccc5-7896-4e78-a1c9-b4d9b3b45584</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CSVExport</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='CSVExport']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Generate CSV&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>405d0d18-7cb0-4870-982f-8d1624fa8906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CSVExport</value>
      <webElementGuid>0c8bf858-adb3-4ef9-98b0-be87251253bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Exportbutton</value>
      <webElementGuid>d96544c3-aa35-401a-b986-2664908a72dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>67980623-f1e4-4102-a468-555041aced3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>getcsv()</value>
      <webElementGuid>5a45d996-fe65-4891-8405-6a679f331f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generate CSV</value>
      <webElementGuid>1d583081-1829-4656-88b5-e6af1a7b40ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CSVExport&quot;)</value>
      <webElementGuid>ae4cf2c4-6efd-403c-bad0-db6b63b4cc2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='CSVExport']</value>
      <webElementGuid>8c2ba9a0-6a90-4297-84a7-bcb576e2208d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Bottomdata']/div[3]/button[2]</value>
      <webElementGuid>517cabed-8457-4e80-b411-fda3ec37326d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate Excel'])[1]/following::button[1]</value>
      <webElementGuid>4cb388f1-39c5-4e20-b9fd-1a0aa0c91b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='If you have more than 1,048,576 rows, use CSV to export.'])[1]/following::button[2]</value>
      <webElementGuid>99f2b08a-fff5-419a-a6b2-a58f1d58b67a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate XML'])[1]/preceding::button[6]</value>
      <webElementGuid>878e0850-7bd6-4486-9b87-f053d192fbc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Would you like to save the settings selected for this export for future use?'])[1]/preceding::button[10]</value>
      <webElementGuid>f64007c3-0654-49d7-9847-a4d10424004d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Generate CSV']/parent::*</value>
      <webElementGuid>705493c0-acbd-4129-be6b-961ab3f9c7c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button[2]</value>
      <webElementGuid>523bc8b9-d9c3-41cb-a769-37e9a1bb6863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'CSVExport' and @type = 'button' and (text() = 'Generate CSV' or . = 'Generate CSV')]</value>
      <webElementGuid>fadebb22-8b61-4054-8c68-2cb357fc80e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
