<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Generate CSV_XMLExport</name>
   <tag></tag>
   <elementGuidId>e5302c3a-d43b-4a9d-b1dd-1ee52d6defd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#XMLExport</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='XMLExport']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Generate XML&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3973381e-0fd7-4357-97a7-5263c740e034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>XMLExport</value>
      <webElementGuid>87026635-7b37-4faf-a5d6-5ae9a23c822c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Exportbutton</value>
      <webElementGuid>a47daa19-004d-426e-ae85-f7869d004d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e7b6b6e4-74bf-4118-bb91-9823dd618052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>customizedflag='0'; getxml();</value>
      <webElementGuid>9d433236-dca3-48ef-af73-32c3a5617d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generate XML</value>
      <webElementGuid>cf83d6eb-aa9e-4904-ac7b-70a0faf5f2c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;XMLExport&quot;)</value>
      <webElementGuid>b49e2aee-3642-4e48-807a-67fc1b2813cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='XMLExport']</value>
      <webElementGuid>17e65bbc-1843-42f3-940a-7a86c4df5489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Bottomdata']/div[3]/button[8]</value>
      <webElementGuid>5576fde9-3c23-490b-a0b0-67152d753118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate CSV'])[1]/following::button[6]</value>
      <webElementGuid>aaca7a23-d845-4e06-86dc-947524f80955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate Excel'])[1]/following::button[7]</value>
      <webElementGuid>fc5c60e1-8251-4184-99cc-a3deb5d00d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Would you like to save the settings selected for this export for future use?'])[1]/preceding::button[4]</value>
      <webElementGuid>2b480662-06a3-49d3-abaf-450abe68b6ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(You can download the records with overlaps from the Downloads page.)'])[1]/preceding::button[4]</value>
      <webElementGuid>d1fefadf-5135-402c-ad60-8c6889c32ece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Generate XML']/parent::*</value>
      <webElementGuid>de16d5ea-f4fe-4bc9-8e55-b900613ef5ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button[8]</value>
      <webElementGuid>14540d5c-0fad-4c82-9117-647bca4f4ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'XMLExport' and @type = 'button' and (text() = 'Generate XML' or . = 'Generate XML')]</value>
      <webElementGuid>9544e183-d322-4164-99b7-cf7f1f315c1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
