<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Defragment Index_posi_abs_back</name>
   <tag></tag>
   <elementGuidId>bcc32ddd-2ee7-4357-b20f-d85f8db5e03c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.posi_abs_back</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='Form1']/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.posi_abs_back</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aada7027-ad6b-43c5-9ad3-1229b44e3a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>posi_abs_back</value>
      <webElementGuid>b87b7928-509a-4d71-9cbb-aa8b87658548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Form1&quot;)/div[@class=&quot;loader_main_spin&quot;]/div[@class=&quot;posi_abs_back&quot;]</value>
      <webElementGuid>16b756c9-921e-4e27-80bb-22cfd354dd98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='Form1']/div[3]/div</value>
      <webElementGuid>fa02239e-05f8-4333-bc97-91b0369702f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>edb217ba-303e-4172-b090-972eb7484d6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
