<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__checkAllbrand</name>
   <tag></tag>
   <elementGuidId>ee2bbb24-82da-4ee2-957c-b67b618a17d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkAllbrand</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'checkbox' and @checked = 'checked' and @id = 'checkAllbrand']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkAllbrand']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#checkAllbrand</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>898f4843-d68f-4ed0-a21c-04547f0f1281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f7803d95-08cc-430c-9a2b-619cd92c5681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>cc867e38-29b1-4c65-bdc1-af2177194e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkAllbrand</value>
      <webElementGuid>7dca4743-cb9c-4cf9-a072-e24bf3b53aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkAllbrand&quot;)</value>
      <webElementGuid>95b9393d-fc18-4828-953a-07da972c3327</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkAllbrand']</value>
      <webElementGuid>f1ba421b-903a-4ff3-b665-63bc31626fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Balllist']/input</value>
      <webElementGuid>3dbddf9e-3339-4ffc-aeab-0d57edd3b25d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/div/div/div/input</value>
      <webElementGuid>3f76cf53-75c9-40c5-98ca-5af35fa2ee65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @checked = 'checked' and @id = 'checkAllbrand']</value>
      <webElementGuid>d50a5f66-40ad-4a96-ac2f-f36fa9dc278e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
