<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_You can select only one Part Descript_d81630</name>
   <tag></tag>
   <elementGuidId>843091c9-3137-46b1-9f0e-9834a747faeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#2020</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='2020']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;ExportTesting002&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1132224d-19e9-4b65-9d25-463c2d23097b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filterinp PartTypechk</value>
      <webElementGuid>4e19a496-abc4-4d94-bf98-2fe6c123e60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>98dd3b3e-ebf3-4d22-a436-96c27ef2ab87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>2020</value>
      <webElementGuid>b9667cb3-6656-499e-91f2-d20c53176763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>996b0307-c52b-4003-9579-7e8d131bb1e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rbCategories</value>
      <webElementGuid>c224bae3-73d8-464f-8f23-4d52d490fc84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ExportTesting002</value>
      <webElementGuid>f06355ed-8986-48bd-9185-5655047d6a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2020&quot;)</value>
      <webElementGuid>d2c2eb64-c258-41f4-8059-7b61dba7f360</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='2020']</value>
      <webElementGuid>a873a946-c3df-4436-9aa5-474f601b15c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chkPartTypelist']/li/input</value>
      <webElementGuid>66181349-20db-4fd9-9875-d941eaf4cb16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/li/input</value>
      <webElementGuid>4332a5ab-82de-4051-80a9-0eddfbeda497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@checked = 'checked' and @id = '2020' and @type = 'checkbox' and @name = 'rbCategories']</value>
      <webElementGuid>6cff3c7a-76f4-46fb-867d-3cdb97de7420</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
