<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__DrpLine</name>
   <tag></tag>
   <elementGuidId>51507f34-be8b-4047-9aef-b1d70eb1ab6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DrpLine</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DrpLine']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Line *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c9835219-49e1-426f-a01e-9a4dad86a03b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DrpLine</value>
      <webElementGuid>d16e4c51-78de-4909-a2e6-027cc9f241f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-SELECT-APEX | AP ExhaustAuto | AutoBBBB | 3MBDMJ | BruteBEC | BeckArnleyBFNK | Motorcar Parts of America IncBKRM | AutoZone IncCARD | Cardone RemanCDXT | DronningborgCPCM | MRCDPGF | Newell Rubbermaid IncDWDK | Nippon Oil CorporationFDCC | Ride Control LLCGGBF | Evolution DrivelineGTQB | KTM Sportmotorcycle GmbHHLYF | Sensata TechnologiesHSSQ | Arrowhead Electrical Products IncJLYQ | Pevisa Auto Parts SAJOD | JonDonKYYF | JN ElectricRCI | Reach CoolingREV | RevolutionRole MfrLine | Rolemanagement mfrLineRULE | BussinessRulesSandF | SandFSandQ | SandQSandS | SandSSandX | SandXSID | SIDEMTES | TESTUSA | USA CleanZZZZ | Others</value>
      <webElementGuid>0fe69321-5519-45de-b1b3-de4d8bc44a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DrpLine&quot;)</value>
      <webElementGuid>ccef78f3-e5c3-4b02-8810-192f3c2c7355</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DrpLine']</value>
      <webElementGuid>b75f148c-5c10-47ae-9f97-2d0ef08e0df7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='Linelbldrp']/select</value>
      <webElementGuid>5a512f2e-7f4b-4b46-bf96-a9b11a4a8be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[1]</value>
      <webElementGuid>adc27b09-20d2-4f0b-914f-c6e743941ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ebay :'])[1]/preceding::select[1]</value>
      <webElementGuid>1198db07-c442-4119-bccc-1e1532545a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interchange :'])[1]/preceding::select[2]</value>
      <webElementGuid>b32a2ff9-02e8-4fb4-846c-befb9edaa821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>308066b1-d182-4430-bf35-3290ccaa8c3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DrpLine' and (text() = '-SELECT-APEX | AP ExhaustAuto | AutoBBBB | 3MBDMJ | BruteBEC | BeckArnleyBFNK | Motorcar Parts of America IncBKRM | AutoZone IncCARD | Cardone RemanCDXT | DronningborgCPCM | MRCDPGF | Newell Rubbermaid IncDWDK | Nippon Oil CorporationFDCC | Ride Control LLCGGBF | Evolution DrivelineGTQB | KTM Sportmotorcycle GmbHHLYF | Sensata TechnologiesHSSQ | Arrowhead Electrical Products IncJLYQ | Pevisa Auto Parts SAJOD | JonDonKYYF | JN ElectricRCI | Reach CoolingREV | RevolutionRole MfrLine | Rolemanagement mfrLineRULE | BussinessRulesSandF | SandFSandQ | SandQSandS | SandSSandX | SandXSID | SIDEMTES | TESTUSA | USA CleanZZZZ | Others' or . = '-SELECT-APEX | AP ExhaustAuto | AutoBBBB | 3MBDMJ | BruteBEC | BeckArnleyBFNK | Motorcar Parts of America IncBKRM | AutoZone IncCARD | Cardone RemanCDXT | DronningborgCPCM | MRCDPGF | Newell Rubbermaid IncDWDK | Nippon Oil CorporationFDCC | Ride Control LLCGGBF | Evolution DrivelineGTQB | KTM Sportmotorcycle GmbHHLYF | Sensata TechnologiesHSSQ | Arrowhead Electrical Products IncJLYQ | Pevisa Auto Parts SAJOD | JonDonKYYF | JN ElectricRCI | Reach CoolingREV | RevolutionRole MfrLine | Rolemanagement mfrLineRULE | BussinessRulesSandF | SandFSandQ | SandQSandS | SandSSandX | SandXSID | SIDEMTES | TESTUSA | USA CleanZZZZ | Others')]</value>
      <webElementGuid>2448ec54-cf1c-41e5-a54b-bb9bf71b8f29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
