<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select All_196</name>
   <tag></tag>
   <elementGuidId>3b15d017-f4b3-4908-8a70-8a69933ef247</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'checkbox' and @value = 'Abarth']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#196</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='196']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Abarth&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5eed1592-f1aa-4d51-974b-19efe0bd23eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filterinp Makechk</value>
      <webElementGuid>99b21b6a-ca5d-497d-b094-368589436066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>299fbe20-6c15-44ec-b3d8-8e838448f0ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>196</value>
      <webElementGuid>24074cf4-4cfc-4bd7-8d4d-77c1cca62cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6956ca46-6577-4c4f-a580-4d3393168cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rbCategories</value>
      <webElementGuid>7d302bed-ea5a-4a5f-9fbf-0609b7d28c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Abarth</value>
      <webElementGuid>24b5df13-f19c-4bc9-94a9-e95320663f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;196&quot;)</value>
      <webElementGuid>b8d7cc0b-facf-49c3-bed3-a750235f288b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='196']</value>
      <webElementGuid>33142cdc-4f3f-4775-a5b6-8b7196dc6088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chkMakelist']/li/input</value>
      <webElementGuid>91e4359a-2f43-43c2-ad1c-7c7011408e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/li/input</value>
      <webElementGuid>25ef6b57-659f-417a-83be-0c5119c3f89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@checked = 'checked' and @id = '196' and @type = 'checkbox' and @name = 'rbCategories']</value>
      <webElementGuid>de4da71c-f676-4a6d-ab72-24641ee9df0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
