<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Validate_appartsedit_btn</name>
   <tag></tag>
   <elementGuidId>bead86e5-4b9f-4d68-b686-2c6656a62ec0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#appartsedit_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='appartsedit_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#appartsedit_btn</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d8ffa4b-2147-4f1f-b7d7-118775314acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>a26573f1-b4c9-437c-a6f5-9f130c896e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>appartsedit_btn</value>
      <webElementGuid>f4cc96e8-18b1-4874-aa9a-4ec764fe780c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//bddemo.apapmt.com/Images/edit_black.png</value>
      <webElementGuid>a1d3b2c0-06d2-4f6a-9c66-e941e7974f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>appartsedit_Click(4744871,3347922)</value>
      <webElementGuid>022e5e76-e61d-4a5e-a206-722eb5566cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chkAccId_edit</value>
      <webElementGuid>f16087a0-75c0-4815-88e0-209c652e5718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vehicletypename</name>
      <type>Main</type>
      <value>Car</value>
      <webElementGuid>fb9050ec-5aee-4e8c-820b-13342455fb4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enginecode</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>7c5500ba-db45-4f4e-9e5b-2f21cf53203d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-makename</name>
      <type>Main</type>
      <value>Abarth</value>
      <webElementGuid>51222337-367a-4230-9266-3d2e438c433d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelname</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>fc69786a-b70c-4bf6-8aba-a8d8d21e070a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3347922</value>
      <webElementGuid>c3795f92-2cd4-44ad-9dd7-d0c1553d377b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appartsedit_btn&quot;)</value>
      <webElementGuid>2bd11de3-51a7-49c8-bb16-646b503f8437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Parts segment/Application/Without Enginee Select/With Attribute/Edit Application/Page_BDDemoPMT/iframe</value>
      <webElementGuid>b97596e0-aa2b-4990-a0c6-bf7cc595bb51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='appartsedit_btn']</value>
      <webElementGuid>1aa7727b-b9ca-4722-8553-6a8a1d503b7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr_1']/td[12]/input</value>
      <webElementGuid>db967e35-78e6-41c1-8aa0-ddb759cd7fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[12]/input</value>
      <webElementGuid>3fe951b4-cd63-4b8a-9bcf-ec640ebabffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @id = 'appartsedit_btn' and @src = '//bddemo.apapmt.com/Images/edit_black.png']</value>
      <webElementGuid>3c63def6-f26d-4216-980e-a01a719ce8c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr_0']/td[12]/input</value>
      <webElementGuid>06c7288e-dfb8-4f4f-925e-7f1dd64f9366</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
