<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__drpPriceType</name>
   <tag></tag>
   <elementGuidId>daad0f80-665b-4b3e-bab0-bf37f9d1e893</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drpPriceType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='drpPriceType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#drpPriceType</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>540a7e7b-495f-4935-a328-1b3ee913d600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_select</value>
      <webElementGuid>aa654a7d-eccc-4acd-a578-b44de8d2db9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drpPriceType</value>
      <webElementGuid>a839c583-a227-457e-90fb-3b26fa550823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Conf-Jobber-JBCCore 1-CR1Core 10-CRACore 11-CRBCore 12-CRCCore 13-CRDCore 14-CRECore 15-CRFCore 2-CR2Core 3-CR3Core 4-CR4Core 5-CR5Core 6-CR6Core 7-CR7Core 8-CR8Core 9-CR9Core Cost-CC1Dealer-DLRDistributor-WD1Fleet-FLTGood Core-CRGInstaller Preferred-INPJobber Core-CRJJobber-JBRList-LSTMaster Installer-INMMaster Wholesale Distributor Price-WDPMechanic-MECNon-Stock Dealer-DLNNS Installer-INNNS Jobber-JBNPack Level 1 Price-PP1Pack Level 2 Price-PP2Pack Level 3 Price-PP3Pack Level 4 Price-PP4Pack Level 5 Price-PP5Pack Level 6 Price-PP6Pack Level 7 Price-PP7Pack Level 8 Price-PP8Pickup-PKPQuantity Price Break-QPBQuote-QOTRacer-RACRetail MAP-RMPRetail-RETSpecial Additional Cost 1-AC1Special Additional Cost 2-AC2Special Promo-PROStocking Installer-INSTrade-TRDUnilateral Price-UNLUser Defined-ZZ1User Defined-ZZ2User Defined-ZZ3User Defined-ZZ4User Defined-ZZ5User Defined-ZZ6User Defined-ZZ7User Defined-ZZ8User Defined-ZZ9User Defined-ZZAUser Defined-ZZBUser Defined-ZZCUser Defined-ZZDUser Defined-ZZEUser Defined-ZZFUser-USRVolume Dealer-DLVWD Core-CRWWD Cost-CWDWholesale MAP-WMPWholesale Unilateral Price-WVPWholesaler-WLS</value>
      <webElementGuid>36154f8e-298e-4e65-8d50-bf4612653682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drpPriceType&quot;)</value>
      <webElementGuid>8df6ee3b-d253-4c2a-8ae2-bab0ea32bd84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='drpPriceType']</value>
      <webElementGuid>d39d6ad0-dd63-4673-9267-20eb68c68bfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div[2]/div/div[3]/div[2]/select</value>
      <webElementGuid>8999e98b-a609-4cbf-98d2-c713ba0ef329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::select[1]</value>
      <webElementGuid>7ab8fe7b-0691-40d7-a260-d0034e4a91f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Effective Date'])[2]/preceding::select[1]</value>
      <webElementGuid>c22033a2-8d26-40a3-be54-80221dc8bc4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expiration Date'])[1]/preceding::select[1]</value>
      <webElementGuid>ada83386-01b2-4daa-9130-968f6ddcbd10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>7e8411b0-2432-4e9c-9405-0263ed5ca973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'drpPriceType' and (text() = '--Select--Conf-Jobber-JBCCore 1-CR1Core 10-CRACore 11-CRBCore 12-CRCCore 13-CRDCore 14-CRECore 15-CRFCore 2-CR2Core 3-CR3Core 4-CR4Core 5-CR5Core 6-CR6Core 7-CR7Core 8-CR8Core 9-CR9Core Cost-CC1Dealer-DLRDistributor-WD1Fleet-FLTGood Core-CRGInstaller Preferred-INPJobber Core-CRJJobber-JBRList-LSTMaster Installer-INMMaster Wholesale Distributor Price-WDPMechanic-MECNon-Stock Dealer-DLNNS Installer-INNNS Jobber-JBNPack Level 1 Price-PP1Pack Level 2 Price-PP2Pack Level 3 Price-PP3Pack Level 4 Price-PP4Pack Level 5 Price-PP5Pack Level 6 Price-PP6Pack Level 7 Price-PP7Pack Level 8 Price-PP8Pickup-PKPQuantity Price Break-QPBQuote-QOTRacer-RACRetail MAP-RMPRetail-RETSpecial Additional Cost 1-AC1Special Additional Cost 2-AC2Special Promo-PROStocking Installer-INSTrade-TRDUnilateral Price-UNLUser Defined-ZZ1User Defined-ZZ2User Defined-ZZ3User Defined-ZZ4User Defined-ZZ5User Defined-ZZ6User Defined-ZZ7User Defined-ZZ8User Defined-ZZ9User Defined-ZZAUser Defined-ZZBUser Defined-ZZCUser Defined-ZZDUser Defined-ZZEUser Defined-ZZFUser-USRVolume Dealer-DLVWD Core-CRWWD Cost-CWDWholesale MAP-WMPWholesale Unilateral Price-WVPWholesaler-WLS' or . = '--Select--Conf-Jobber-JBCCore 1-CR1Core 10-CRACore 11-CRBCore 12-CRCCore 13-CRDCore 14-CRECore 15-CRFCore 2-CR2Core 3-CR3Core 4-CR4Core 5-CR5Core 6-CR6Core 7-CR7Core 8-CR8Core 9-CR9Core Cost-CC1Dealer-DLRDistributor-WD1Fleet-FLTGood Core-CRGInstaller Preferred-INPJobber Core-CRJJobber-JBRList-LSTMaster Installer-INMMaster Wholesale Distributor Price-WDPMechanic-MECNon-Stock Dealer-DLNNS Installer-INNNS Jobber-JBNPack Level 1 Price-PP1Pack Level 2 Price-PP2Pack Level 3 Price-PP3Pack Level 4 Price-PP4Pack Level 5 Price-PP5Pack Level 6 Price-PP6Pack Level 7 Price-PP7Pack Level 8 Price-PP8Pickup-PKPQuantity Price Break-QPBQuote-QOTRacer-RACRetail MAP-RMPRetail-RETSpecial Additional Cost 1-AC1Special Additional Cost 2-AC2Special Promo-PROStocking Installer-INSTrade-TRDUnilateral Price-UNLUser Defined-ZZ1User Defined-ZZ2User Defined-ZZ3User Defined-ZZ4User Defined-ZZ5User Defined-ZZ6User Defined-ZZ7User Defined-ZZ8User Defined-ZZ9User Defined-ZZAUser Defined-ZZBUser Defined-ZZCUser Defined-ZZDUser Defined-ZZEUser Defined-ZZFUser-USRVolume Dealer-DLVWD Core-CRWWD Cost-CWDWholesale MAP-WMPWholesale Unilateral Price-WVPWholesaler-WLS')]</value>
      <webElementGuid>a207c391-03c4-4ba9-99f3-351334e71bb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
