<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>eb4cd342-26d3-49dc-8ea5-bcee2c291e89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Brand > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Brand']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Brand >> internal:role=img >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2edb7288-3ba8-4b54-b8e5-b17cd287c7a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//bddemo.apapmt.com/Images/New_design_img/parts_manufacture.jpg</value>
      <webElementGuid>70399ba8-781a-4bfd-be5c-4c67e9c69ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Brand&quot;)/img[1]</value>
      <webElementGuid>74ecca20-2b09-404f-97ca-0b73d32deca9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Brand']/img</value>
      <webElementGuid>c3bc20a1-61b0-4557-a358-0ecf9c27d0da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/img</value>
      <webElementGuid>dca5157b-16d5-433f-aaea-401b71883a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//bddemo.apapmt.com/Images/New_design_img/parts_manufacture.jpg']</value>
      <webElementGuid>0ca6f369-0ce9-44d4-b357-40521809fa08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
