<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>5ac42d07-3ec3-46c8-b635-0266a358c0e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='piespages']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>82fd22c4-7524-4b4c-8916-df026b6df260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../Parts/BuyersGuideEnginebase_New.aspx?PartID=330384&amp;Category=Testing_Pmt&amp;Subcategory=Testing_Pmt&amp;PartDescription=Testing_Ecat&amp;Partno=Testing_Automation&amp;PageTitle=Parts+Application Data &amp;Productdescid=1832&amp;qty=1</value>
      <webElementGuid>0ec58063-1f86-4011-8fdf-39ea3892e622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;piespages&quot;)/iframe[1]</value>
      <webElementGuid>c184b6b8-0c4f-4fae-9211-e0e326a8bd01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/iframe</value>
      <webElementGuid>297cce70-111e-4c27-b150-9f3cb1116959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>5e1d6c7f-d910-436c-b37d-a78cda0308a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '../Parts/BuyersGuideEnginebase_New.aspx?PartID=330384&amp;Category=Testing_Pmt&amp;Subcategory=Testing_Pmt&amp;PartDescription=Testing_Ecat&amp;Partno=Testing_Automation&amp;PageTitle=Parts+Application Data &amp;Productdescid=1832&amp;qty=1']</value>
      <webElementGuid>5b021343-287a-4996-990a-bb0d6df1efa8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
