<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Engine Not Required (All Engines)_chk9_0</name>
   <tag></tag>
   <elementGuidId>2e8ee673-f064-46d0-85cd-6a2b13c6e278</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chk9_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'checkbox' and @value = 'L4 982CC 60CID 1.0L 2.56 65.0 2.91 74.0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ref_element = 'Object Repository/Parts segment/Application/With Enginee Select/With Attribute/Add Application/Page_BDDemoPMT/iframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;L4 982CC 60CID 1.0L 2.56 65.0 2.91 74.0&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa04cbe1-1483-4d86-9972-c8d4d6805491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>eab05c6e-e618-4f0d-a98f-e8c3a65b873c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chklistitem10</value>
      <webElementGuid>8abba154-949d-42c5-ae56-b9292b2f31e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chkothers</value>
      <webElementGuid>a491aece-94e5-4159-a233-fb8a7d63ed40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>L4 982CC 60CID 1.0L 2.56 65.0 2.91 74.0</value>
      <webElementGuid>626ae984-c37c-4978-95f0-3d59372ca33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chk9_0</value>
      <webElementGuid>51004d60-f4c3-46d1-a56c-4cf25310204f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setenginebase()</value>
      <webElementGuid>58c6fd7f-c7d0-4405-a29c-a97258e0cd4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chk9_0&quot;)</value>
      <webElementGuid>ce0bf3b6-d551-4ae3-9eb8-10394023eddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Parts segment/Application/With Enginee Select/With Attribute/Add Application/Page_BDDemoPMT/iframe</value>
      <webElementGuid>a90af4e1-b769-4cf6-9f89-42903edf7653</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='chk9_0']</value>
      <webElementGuid>09a5b72b-e5c5-4f60-8e4a-314d372fe608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divenginebase']/span[2]/input</value>
      <webElementGuid>b5ea3481-c4cc-4a59-9434-0a448c69869e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span[2]/input</value>
      <webElementGuid>5a8b67ae-e5d0-43af-8a05-cede20d51fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'chklistitem10' and @id = 'chk9_0']</value>
      <webElementGuid>6993fd06-c61c-4c66-a81f-6a9c8e785068</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
