<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Region_MainContent_dlDisplayColumnLis_a29b34</name>
   <tag></tag>
   <elementGuidId>06b5b286-3636-437e-ba44-07057c2b8841</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MainContent_dlDisplayColumnList_chkselectAll1_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MainContent_dlDisplayColumnList_chkselectAll1_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Region All&quot;i] >> internal:label=&quot;All&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ebc38ecf-14f7-407f-a036-9b0ed48f02e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainContent_dlDisplayColumnList_chkselectAll1_0</value>
      <webElementGuid>8fb55473-132a-4d66-a66a-fca84cf988de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>25141a79-6b1b-4391-8703-9013a032aa8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$dlDisplayColumnList$ctl00$chkselectAll1</value>
      <webElementGuid>99f4f373-33c1-4936-b9f8-dec323c4a46b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CheckAllGrid(this);</value>
      <webElementGuid>13b78d1b-b8e9-4c48-b8a0-4fcba3fe14ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_dlDisplayColumnList_chkselectAll1_0&quot;)</value>
      <webElementGuid>d799b636-696b-4a3d-9a7c-70341a472893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Parts segment/Application/With Enginee Select/With Attribute/Add Application/Page_BDDemoPMT/iframe</value>
      <webElementGuid>eba0e7eb-5b20-4e11-9c43-863a84f50e12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MainContent_dlDisplayColumnList_chkselectAll1_0']</value>
      <webElementGuid>1b432b56-8ebb-4abf-9727-89e3f69b4101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_dlDisplayColumnList_UpdatePanel5_0']/h3/span/span/input</value>
      <webElementGuid>e355b03a-da12-4e96-aff3-22b5588d639c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/span/span/input</value>
      <webElementGuid>3d0358e3-8b11-4eda-927a-c99affbbe3b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MainContent_dlDisplayColumnList_chkselectAll1_0' and @type = 'checkbox' and @name = 'ctl00$MainContent$dlDisplayColumnList$ctl00$chkselectAll1']</value>
      <webElementGuid>969ff93c-0e87-4a29-94d9-62f3ed736672</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
