<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sub Model_MainContent_dlDisplayColumn_303378</name>
   <tag></tag>
   <elementGuidId>53e165a4-d7d5-434e-8cef-803176b8cd39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MainContent_dlDisplayColumnList_chkselectAll1_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MainContent_dlDisplayColumnList_chkselectAll1_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Sub Model All&quot;i] >> internal:label=&quot;All&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21b8ef6a-506c-4fd5-b3df-d142a7930f98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainContent_dlDisplayColumnList_chkselectAll1_1</value>
      <webElementGuid>afe25180-5160-4270-af75-1634e379b81b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>81a9541d-4fe4-43b1-9adf-27787e7caac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$dlDisplayColumnList$ctl01$chkselectAll1</value>
      <webElementGuid>78ef344e-bae4-4c6c-881d-1089bb5ef9cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CheckAllGrid(this);</value>
      <webElementGuid>85b30adc-ae3f-49e4-9e70-a1e6a3ab9bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_dlDisplayColumnList_chkselectAll1_1&quot;)</value>
      <webElementGuid>efa3d956-3ef0-434c-9e28-5360f808e6a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Parts segment/Application/With Enginee Select/With Attribute/Add Application/Page_BDDemoPMT/iframe</value>
      <webElementGuid>0200652e-9d3b-4f9a-a211-e9e62d4b1a79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MainContent_dlDisplayColumnList_chkselectAll1_1']</value>
      <webElementGuid>c3ad08c1-a77d-4263-8367-6fafc9c488de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_dlDisplayColumnList_UpdatePanel5_1']/h3/span/span/input</value>
      <webElementGuid>ca6fe5bc-73e9-466d-a6cb-218ca056fab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h3/span/span/input</value>
      <webElementGuid>f05064a1-3d49-4697-9eec-32dbf8b79a4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MainContent_dlDisplayColumnList_chkselectAll1_1' and @type = 'checkbox' and @name = 'ctl00$MainContent$dlDisplayColumnList$ctl01$chkselectAll1']</value>
      <webElementGuid>f2788ebb-a883-4f4e-9303-7db300b9ccab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
