<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_More Info_MainContent_GvApplications__613d0d</name>
   <tag></tag>
   <elementGuidId>029dfd4a-de6b-436d-b2cd-5604a4d3f58b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MainContent_GvApplications_chkActivee1_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MainContent_GvApplications_chkActivee1_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#MainContent_GvApplications_chkActivee1_0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>024cae2d-b3d8-4a95-b97c-e10caa56ff43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainContent_GvApplications_chkActivee1_0</value>
      <webElementGuid>fef96b1b-7460-42bc-a39b-bd03c9965ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2cb314e4-57d6-4a21-bdb1-e471cbd911f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$GvApplications$ctl02$chkActivee1</value>
      <webElementGuid>7a113601-1b28-4b19-92e0-ff0b06205948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_GvApplications_chkActivee1_0&quot;)</value>
      <webElementGuid>eff81143-f96c-4d9e-82b2-7e55624bbb69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Parts segment/Application/With Enginee Select/With Attribute/Add Application/Page_BDDemoPMT/iframe</value>
      <webElementGuid>4bbc793c-d4a6-434c-b1b8-686dde402d17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MainContent_GvApplications_chkActivee1_0']</value>
      <webElementGuid>997a15a9-3664-4b88-90fb-2b6d39893dfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='MainContent_GvApplications']/tbody/tr[2]/td/span/input</value>
      <webElementGuid>e4017166-9fa8-4e06-bdfa-c45626f4da8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span/input</value>
      <webElementGuid>3808fbd3-7a02-4381-bbe1-5cb34c369c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MainContent_GvApplications_chkActivee1_0' and @type = 'checkbox' and @name = 'ctl00$MainContent$GvApplications$ctl02$chkActivee1']</value>
      <webElementGuid>08b62f6d-e874-4d3e-896c-b9890b943647</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
