<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__MainContent_drpModel</name>
   <tag></tag>
   <elementGuidId>0e5b49ca-e9af-4d58-9259-9a1b3f856d65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MainContent_drpModel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='MainContent_drpModel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#MainContent_drpModel</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>55a7b4bd-03b0-454b-bddf-03a81ab35cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$drpModel</value>
      <webElementGuid>38c6f212-0aee-4fff-b08d-015e8c7ff956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$MainContent$drpModel\',\'\')', 0)</value>
      <webElementGuid>a30461d5-5fe4-49c9-a398-a37ed6d35df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainContent_drpModel</value>
      <webElementGuid>011d1aa7-33f8-4694-9fab-ff971d4ebf57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	Select
	1000
	1150
	1300
	1600
	2000
	204
	205
	750
	850
	Simca

</value>
      <webElementGuid>37f0a9d4-b4d7-4d78-8959-6bd71583b1ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_drpModel&quot;)</value>
      <webElementGuid>a458b8da-bd19-4217-951d-4e93133c8be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Parts segment/Application/With Enginee Select/With Attribute/Add Application/Page_BDDemoPMT/iframe</value>
      <webElementGuid>19b993be-db00-4ca0-a118-c48a4a950dd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='MainContent_drpModel']</value>
      <webElementGuid>e932f1ff-5f48-419a-a64e-040578d4ccb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_div_filter']/span[3]/select</value>
      <webElementGuid>b0085ae2-928a-4973-a21b-65e6b3acb337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[1]</value>
      <webElementGuid>91e218fc-671f-4507-a865-82b52beb609e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Model'])[1]/following::select[1]</value>
      <webElementGuid>092a46a6-0a2f-474c-add3-74021e51fc5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enginebase'])[1]/preceding::select[1]</value>
      <webElementGuid>220a4972-aae0-49d6-8c17-1d210f379d55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You can choose either specific engine base(s) or Engine Not Required option.'])[1]/preceding::select[1]</value>
      <webElementGuid>0a3ba954-7003-4d32-855f-e633c462254b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/select</value>
      <webElementGuid>a02fb2e6-94f3-4a55-a5ef-cf6cd7249b11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ctl00$MainContent$drpModel' and @id = 'MainContent_drpModel' and (text() = '
	Select
	1000
	1150
	1300
	1600
	2000
	204
	205
	750
	850
	Simca

' or . = '
	Select
	1000
	1150
	1300
	1600
	2000
	204
	205
	750
	850
	Simca

')]</value>
      <webElementGuid>d22929c0-b156-4dbc-9d82-101e4838aa56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
