<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PMT_edit_ImageButton35855</name>
   <tag></tag>
   <elementGuidId>b565dc27-9ea0-4425-81f6-435aea0d5fb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='edit_ImageButton35855']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit_ImageButton35855</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'ctl00$MainContent$ImageButton1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#edit_ImageButton35855</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0f7407a-bc98-409b-b4bb-09b1a8d57252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>cf0bf613-7d6c-4711-bfb6-a44ef2d6fcd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$ImageButton1</value>
      <webElementGuid>0e6655bc-0e96-4c6e-b2c8-f9eb2fadf2fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon_edit_del</value>
      <webElementGuid>9d62bb14-67f3-4533-98ed-f3815795f7f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit_ImageButton35855</value>
      <webElementGuid>a91ec837-23a5-4907-83c0-edd2feac7981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../Images/New_design_img/edit_icon.png</value>
      <webElementGuid>398a8634-1679-48cd-a2cb-d4f9582f3d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>edit_row(35855);</value>
      <webElementGuid>079c48cf-36bb-4baf-8c38-01b7c4be8629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit_ImageButton35855&quot;)</value>
      <webElementGuid>db77de62-69fb-490a-afe8-7e359feadd23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit_ImageButton35855']</value>
      <webElementGuid>ba7f1bbe-2bd3-47a3-b652-23820f94cfdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='sortorder_val35855']/td[14]/div/span/input</value>
      <webElementGuid>7ab6ba03-64af-4f43-ade0-3e0661624ab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[14]/div/span/input</value>
      <webElementGuid>b347846d-3308-4dc1-8917-a2152ee9366c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$MainContent$ImageButton1' and @id = 'edit_ImageButton35855' and @src = '../Images/New_design_img/edit_icon.png']</value>
      <webElementGuid>ec3e434e-62af-46af-9473-e7404547b0d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
