<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PMT_save_ImageButton35855</name>
   <tag></tag>
   <elementGuidId>134d7143-1a06-49a6-9fff-e7f8847a8b1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='save_ImageButton35855']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#save_ImageButton35855</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'ctl00$MainContent$ImageButton3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#save_ImageButton35855</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ce3486d-5e34-47cc-b736-bd91d6a95847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>3ce4b306-1beb-4e30-9ce4-c7273c5f837e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$ImageButton3</value>
      <webElementGuid>1816bfc5-133f-43d0-a162-5b415e0f2929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon_save_cancel</value>
      <webElementGuid>0e939ea2-df07-4e6b-85b9-1890bae6c624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>save_ImageButton35855</value>
      <webElementGuid>f84a669d-6cdb-4093-8cdc-e65e5365135b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../Images/New_design_img/update_edit_new.png</value>
      <webElementGuid>669a3113-fb77-454f-b931-963074f4bf93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>this.disabled = true; Edit_save_record(35855); this.disabled = false;</value>
      <webElementGuid>c16b4dc8-033c-4d88-984d-f88cc8efcb5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;save_ImageButton35855&quot;)</value>
      <webElementGuid>44c447f5-8d45-42d8-8705-e94bf28df6f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='save_ImageButton35855']</value>
      <webElementGuid>e287b5d8-122e-491c-b4a3-03fc28f85dc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='sortorder_val35855']/td[14]/div/span[3]/input</value>
      <webElementGuid>2bc27ff1-d880-4135-a5e0-cbc87e275736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[14]/div/span[3]/input</value>
      <webElementGuid>8e99017d-e94d-4095-8610-c9fd7d1bd4bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$MainContent$ImageButton3' and @id = 'save_ImageButton35855' and @src = '../Images/New_design_img/update_edit_new.png']</value>
      <webElementGuid>2675f836-d904-422a-a739-9c802e809ffb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
