<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lead Time_txtLeadTime</name>
   <tag></tag>
   <elementGuidId>c740e512-bee9-497f-baac-a6620a6a7687</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtLeadTime</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtLeadTime']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab44c491-c1ad-4118-ab28-f05299141f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_input</value>
      <webElementGuid>a334841c-8b9f-4c7f-a8c7-64f41530024d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtLeadTime</value>
      <webElementGuid>bce1e6b8-33f3-4f96-9b02-2c2fb62cf98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>c64253a5-feb6-4a1a-89e8-c51131b0cde2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6cac5ecf-909a-45c5-b67f-98e35248566f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return NoDecimal(event)</value>
      <webElementGuid>bb4dc6d9-6307-4def-b006-3d1e4efacb4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtLeadTime&quot;)</value>
      <webElementGuid>82e664dc-439e-443a-b532-3d43f3d5ceef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtLeadTime']</value>
      <webElementGuid>03b9eed7-6beb-4258-ace7-7837b15991e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div[2]/div/div[3]/div[10]/input</value>
      <webElementGuid>590e7723-e67a-4f78-9be7-9e9f6f2b9bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/input</value>
      <webElementGuid>49db1930-19eb-4808-b689-5889d6b5f2cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtLeadTime']</value>
      <webElementGuid>ad4c4e5d-5393-4157-b9e0-b97c33da6619</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
