<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_WareHouse Location_drpWarehouse</name>
   <tag></tag>
   <elementGuidId>0e237a88-cc81-45c3-82ef-27cee017c964</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drpWarehouse</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='drpWarehouse']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0aec4594-47ca-4d86-8ee9-88547dc91c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_select</value>
      <webElementGuid>3fa28786-669e-4cf7-9b8a-d6991af6cfa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drpWarehouse</value>
      <webElementGuid>61dff599-791e-4ad9-b41c-45bdfde9202b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--CACHENaIDefaultFLNVPATES-1710</value>
      <webElementGuid>1a6b1201-2b06-47e8-ad35-f972e29d23c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drpWarehouse&quot;)</value>
      <webElementGuid>6e467471-76c2-4fb8-9546-f6a0206b5837</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='drpWarehouse']</value>
      <webElementGuid>553875c8-6936-4460-91d1-4d3e166ebf50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='WareHouseContainer']/select</value>
      <webElementGuid>cee75575-77f9-4658-9fe4-6c9507ccdecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WareHouse Location'])[1]/following::select[1]</value>
      <webElementGuid>e5bc3042-8353-4324-b56e-8f2134b67e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field represents the cumulative QOH for the Vendor SKU from all applicable warehouses.'])[1]/following::select[1]</value>
      <webElementGuid>56dffef7-4209-47dc-9ecd-993b01e69d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WareHouse QOH'])[1]/preceding::select[1]</value>
      <webElementGuid>4b158fca-4161-4f01-9563-18868ed36401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field represents the individual warehouse QOH'])[1]/preceding::select[1]</value>
      <webElementGuid>2694eec6-12bf-462e-92e0-25f192246e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/select</value>
      <webElementGuid>70b11090-e8db-4777-964c-1532c8c0e63c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'drpWarehouse' and (text() = '--Select--CACHENaIDefaultFLNVPATES-1710' or . = '--Select--CACHENaIDefaultFLNVPATES-1710')]</value>
      <webElementGuid>adee67c1-c426-45c4-8e75-af39956cf79f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
