<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ReferenceItem_txtReferenceItem</name>
   <tag></tag>
   <elementGuidId>030fc031-032a-48e8-a70b-cedca596165a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtReferenceItem</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtReferenceItem']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtReferenceItem</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52a7dc3c-0d96-4c2a-81ad-9d7701fe73f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_input</value>
      <webElementGuid>ec5a475d-c550-49ec-b7fe-950f7d5543b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtReferenceItem</value>
      <webElementGuid>05b8dd63-bba2-4b1b-81db-8ae04ed38de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>83b6cd54-786f-4bd5-b702-55f4feb45e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>8938c423-72db-4e85-9ad9-359ac757fe37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtReferenceItem&quot;)</value>
      <webElementGuid>aeb5366d-91dc-4c39-a56a-2cf79a69f7c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtReferenceItem']</value>
      <webElementGuid>ed0bc2f5-5dfb-412b-b03b-268005cc97d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p']/div[2]/div[2]/div[9]/input</value>
      <webElementGuid>b67e025e-66c2-40e9-abd1-4098508f7966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/input</value>
      <webElementGuid>6bd6d847-f3f2-4909-b724-2fc47cd9b18a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtReferenceItem']</value>
      <webElementGuid>54e8350a-e7ed-44d5-81cf-4528202091c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
