<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Internal Notes_txtInternalNotes</name>
   <tag></tag>
   <elementGuidId>cd8c7cfa-7498-4c52-b0a8-1c3bfa1cdc3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtInternalNotes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtInternalNotes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtInternalNotes</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>410b20e3-7bc4-44d4-92c9-1fb5b113cabb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_input</value>
      <webElementGuid>fd3f242c-2a8d-4fe0-ac82-72cfffd79d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtInternalNotes</value>
      <webElementGuid>c71159cf-5ad9-41ed-899c-820ae037685c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>240</value>
      <webElementGuid>b29ff577-9910-465d-9230-98351e21ccd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>9aadc625-559c-4c0d-a355-1a89ff0cd808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtInternalNotes&quot;)</value>
      <webElementGuid>a002aef5-f045-42ee-939b-8f534c8d94aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtInternalNotes']</value>
      <webElementGuid>51649b39-45aa-45f1-ad9a-d850f8157a76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p']/div[2]/div[2]/div[4]/input</value>
      <webElementGuid>9aa5c87d-59da-4052-8911-e0d621e17c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/input</value>
      <webElementGuid>79755057-a69f-4b3a-aa10-5ff6808098c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtInternalNotes']</value>
      <webElementGuid>979846a7-efab-49aa-96ec-a89cb3474001</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
