<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>39ac98f1-e9f1-49d2-b7a2-7f59f2f5fbce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;delete&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[4]/div/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;delete&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5d347e7f-7ee7-4a5d-929c-a0d2e1950c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//ecat.apapmt.com/Images/New_design_img/delete_icon.png</value>
      <webElementGuid>5472a3c9-f230-4f5c-b838-5265aea3a7a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>delete</value>
      <webElementGuid>661d81aa-ffaf-4fe5-b054-a2a30d31f502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divdeletebtn_'84'&quot;)/img[1]</value>
      <webElementGuid>43fa0493-72c0-4a9c-bee4-8f5c9ffe9192</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=&quot;divdeletebtn_'84'&quot;]/img</value>
      <webElementGuid>c02b04d2-be60-4e04-97c8-f516f18893fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='delete']</value>
      <webElementGuid>21590ab4-210c-48db-91f7-00739fb1cf00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/div[2]/img</value>
      <webElementGuid>198749eb-6c6b-4614-9e41-884dc8680b77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//ecat.apapmt.com/Images/New_design_img/delete_icon.png' and @alt = 'delete']</value>
      <webElementGuid>0c3c632a-fa5d-460a-800b-81e499297a31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
