<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>67556e98-2a1b-4a98-bef5-662ea80e2ef7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='piespages']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4ecbeed2-a929-44f3-8cec-990aecff770e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../Parts/BuyersGuideEnginebase_New.aspx?PartID=330369&amp;Category=Testing_Pmt&amp;Subcategory=Testing_Pmt&amp;PartDescription=Testing_Ecat&amp;Partno=Testing_Automation&amp;PageTitle=Parts+Application Data &amp;Productdescid=1823&amp;qty=1</value>
      <webElementGuid>2bdb735a-3e92-4f52-b1f9-05ad6cf8538e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;piespages&quot;)/iframe[1]</value>
      <webElementGuid>45981e8e-103c-46fb-aaf5-219eda72cdc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/iframe</value>
      <webElementGuid>2f84fcfc-aeb0-4e1b-a0f3-d1e163c51c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>348c79ac-4cec-4313-a181-150f39883696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '../Parts/BuyersGuideEnginebase_New.aspx?PartID=330369&amp;Category=Testing_Pmt&amp;Subcategory=Testing_Pmt&amp;PartDescription=Testing_Ecat&amp;Partno=Testing_Automation&amp;PageTitle=Parts+Application Data &amp;Productdescid=1823&amp;qty=1']</value>
      <webElementGuid>5db82419-712f-4ab3-ae14-d69c4991dfa4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
