<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>cbb1e55d-603f-45ea-89fb-6e8f03cfb13c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BuyersGuid1 > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='BuyersGuid1']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#BuyersGuid1 >> internal:role=img >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e092cad8-ff08-4151-9d56-a256d86228a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//bddemo.apapmt.com/Images/New_design_img/part_buyer_guide.png</value>
      <webElementGuid>5f20de7a-fc50-4ab8-84e0-5269db709074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BuyersGuid1&quot;)/img[1]</value>
      <webElementGuid>345070c4-e50d-47e1-9255-d72b80cf0ff0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BuyersGuid1']/img</value>
      <webElementGuid>06f54e68-b09e-4354-a4ec-8e237b1e7f40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>21842e48-00b9-427d-855e-6f5b6be0c2b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//bddemo.apapmt.com/Images/New_design_img/part_buyer_guide.png']</value>
      <webElementGuid>f40159ce-8a6b-4b88-a7ac-a43d97e7cf69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
