<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Edit_apppartdelete</name>
   <tag></tag>
   <elementGuidId>80a5a00a-39c1-48c0-b1a1-6c9643e4bcda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th.sorting_disabled > #apppartdelete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='apppartdelete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Submit&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>61c51a7f-ce43-4eef-bec9-c97beddda570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>29f903f6-7704-451d-9eae-66d03d23591a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apppartdelete</value>
      <webElementGuid>8e3fd768-8be4-4b99-8c54-5930f4e7c15e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//bddemo.apapmt.com/Images/delete_red.png</value>
      <webElementGuid>83fd5021-5620-4428-aa39-8063ac9811ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbl_apppartstable_wrapper&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;dataTables_scroll&quot;]/div[@class=&quot;dataTables_scrollHead&quot;]/div[@class=&quot;dataTables_scrollHeadInner&quot;]/table[@class=&quot;table table-striped table-bordered display nowrap dataTable&quot;]/thead[1]/tr[1]/th[@class=&quot;sorting_disabled&quot;]/input[@id=&quot;apppartdelete&quot;]</value>
      <webElementGuid>b4acac46-b0fa-40d5-9e98-b3eacea5d3e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Parts segment/Application/Without Enginee Select/With Attribute/Delete Application/Page_BDDemoPMT/iframe</value>
      <webElementGuid>af96712f-f35f-4463-a738-410ada50a8fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='apppartdelete']</value>
      <webElementGuid>2651891e-6814-432f-81c2-3e77cfdcdddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tbl_apppartstable_wrapper']/div[2]/div/div/div/div/table/thead/tr/th[15]/input</value>
      <webElementGuid>630bc465-6ede-4d7f-ab6b-94e384c18b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[15]/input</value>
      <webElementGuid>89d3a55b-44b8-4ab5-baec-0fbc715dd63a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @id = 'apppartdelete' and @src = '//bddemo.apapmt.com/Images/delete_red.png']</value>
      <webElementGuid>09d7faf0-b649-4ab7-9a36-55f4e94d688d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
