<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ACES_MainContent_btnacesattibues</name>
   <tag></tag>
   <elementGuidId>2cc5e229-1633-4b52-a3e6-e090578bd241</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='MainContent_btnacesattibues']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MainContent_btnacesattibues</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Show Attributes&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>27082f2e-47cb-4494-97e5-8828df822b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>__doPostBack('ctl00$MainContent$btnacesattibues','')</value>
      <webElementGuid>fc89dcdd-bb17-46d5-a4dc-24137ea8972e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainContent_btnacesattibues</value>
      <webElementGuid>c377d27f-c1b6-410c-ac55-410ccd10c3da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button_list_new</value>
      <webElementGuid>87d78716-09c5-4f8e-8f38-f4188d306f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Show Attributes</value>
      <webElementGuid>4b947ba7-a35d-4f78-a814-403671e427c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_btnacesattibues&quot;)</value>
      <webElementGuid>fb70f28b-8b60-4d16-b04b-728fe7967de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Parts segment/Application/With Enginee Select/Without Attribute/Edit Application/Page_BDDemoPMT/iframe</value>
      <webElementGuid>5db823c5-1707-4c52-b549-06942f1e32c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='MainContent_btnacesattibues']</value>
      <webElementGuid>6241178f-1ca7-4947-8d5b-5261075df439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_div_applnlist1']/span/button</value>
      <webElementGuid>fd7e0da4-09e4-460e-bf91-b3eb10a10ad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACES'])[8]/following::button[1]</value>
      <webElementGuid>5dbfc994-6e31-44af-8dde-e54e1b90e59a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='L4 982CC 60CID 1.0L 2.56 65.0 2.91 74.0'])[8]/following::button[1]</value>
      <webElementGuid>2bf97944-6d08-481c-b4c8-d351554f4669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Non AcesAttributes'])[1]/preceding::button[1]</value>
      <webElementGuid>d0314592-c8c7-4010-a204-a0b597a38ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[2]</value>
      <webElementGuid>e3c99c34-490b-47dd-beb9-b6c5a8eae7ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Show Attributes']/parent::*</value>
      <webElementGuid>66066ad8-0acb-4fdf-be86-dbe1d761ac88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>2bda1209-d5df-45ee-85bc-ce8dda794e92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'MainContent_btnacesattibues' and (text() = 'Show Attributes' or . = 'Show Attributes')]</value>
      <webElementGuid>b12974c3-2165-4e33-b0ec-21093424d93a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
