<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Equipment_ucMenu_rptLevel1_lnkLink1_3</name>
   <tag></tag>
   <elementGuidId>b23e2cf3-1bd2-415d-9c7a-a626b9daff4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucMenu_rptLevel1_lnkLink1_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Parts')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Parts&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>faadaf66-2fb8-441c-8515-8a7ba134c635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucMenu_rptLevel1_lnkLink1_3</value>
      <webElementGuid>44697b3d-69a1-4de1-84dd-ad04f9eb1795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main_menu parts_icon active</value>
      <webElementGuid>c50f40bd-e25d-453b-ab32-37f6fe47298e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../Parts/parts.aspx?PageTitle=Parts Data</value>
      <webElementGuid>0559e837-478f-4487-9d69-7b67138083c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Parts</value>
      <webElementGuid>2bbdb628-ff14-4195-95d2-26e64237ad63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucMenu_rptLevel1_lnkLink1_3&quot;)</value>
      <webElementGuid>5a8e1502-13fc-4b84-841c-94195b54da8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucMenu_rptLevel1_lnkLink1_3']</value>
      <webElementGuid>bd10611d-a216-4d10-a023-6d931f62b112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='ucMenu_rptLevel1_l1_3']/a</value>
      <webElementGuid>d6e2f055-7287-4861-8c7a-ea4f3d33c70d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Parts')]</value>
      <webElementGuid>7b1eabe0-7117-4718-8de9-1bd64fc27ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Equipment'])[1]/following::a[1]</value>
      <webElementGuid>7debe5fd-3837-4f8c-ba45-9259f4fccff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle'])[1]/following::a[2]</value>
      <webElementGuid>55348d9c-89d0-4487-a3c3-c4583fb70ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export Data'])[1]/preceding::a[1]</value>
      <webElementGuid>8f314e08-d018-4d48-b8c0-fe41d63ceb8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Catalogs'])[1]/preceding::a[2]</value>
      <webElementGuid>7ec0ca87-adef-4979-8acc-c24adf146480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Parts']/parent::*</value>
      <webElementGuid>c1e2df0d-c9b5-431b-85ed-f971fd86af54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '../Parts/parts.aspx?PageTitle=Parts Data')]</value>
      <webElementGuid>6ca5c035-ad4e-4e20-b0cd-834f28226e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>509c2684-55f0-4ff2-bd62-20654217c347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucMenu_rptLevel1_lnkLink1_3' and @href = '../Parts/parts.aspx?PageTitle=Parts Data' and (text() = 'Parts' or . = 'Parts')]</value>
      <webElementGuid>814876d2-4d15-47ab-a460-59d0020817df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
