<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No-Override_piesbtnSave</name>
   <tag></tag>
   <elementGuidId>1fdfd365-0643-404b-9e21-d153e357d837</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#piesbtnSave</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='piesbtnSave']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Save&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>20a68c5a-b6e7-4049-8675-60c27022fd68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>79082f75-a840-49b6-86d4-a7f6f1f0a704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>piesbtnSave</value>
      <webElementGuid>2dfc8e26-3bdf-4b32-b705-627822196284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>ac6cb044-dd15-43c8-bbd5-ff3382ca04bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button_save</value>
      <webElementGuid>657b51bf-c03d-4003-b056-b26522ff695e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return checkModifyDatePIES();</value>
      <webElementGuid>55c979ce-9b6e-48db-90eb-3e8e5ab32be6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;piesbtnSave&quot;)</value>
      <webElementGuid>cdd87478-00fe-4e8e-87f0-0fec4e120850</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='piesbtnSave']</value>
      <webElementGuid>ce4ba06e-9f08-4e26-9ad9-38e0b5cd9d6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div[2]/div[2]/div[3]/div[6]/div/input</value>
      <webElementGuid>9da9302e-83f3-45ed-8571-6d82617410ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>356ad42a-b97b-4397-b6b1-d521b93a95bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'piesbtnSave']</value>
      <webElementGuid>12d74805-e24e-4335-94c2-b8029ecfab5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
