<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Select_note-codable</name>
   <tag></tag>
   <elementGuidId>25530cfe-1bfc-4778-867d-56f520afb315</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.note-codable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='piespages']/div[2]/div[2]/div[4]/div/div[3]/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>textarea >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>321a7ed2-002f-4210-b9b4-de376354ead3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>note-codable</value>
      <webElementGuid>3395c284-82e8-49cc-a152-0e7e00b0f5dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d4dfc070-6229-4051-8dd4-f898830d7cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;piespages&quot;)/div[@class=&quot;parts_main_div&quot;]/div[@class=&quot;dvSearchPart&quot;]/div[@class=&quot;field_label_full mar_bottom_0&quot;]/div[@class=&quot;note-editor note-frame codeview&quot;]/div[@class=&quot;note-editing-area&quot;]/textarea[@class=&quot;note-codable&quot;]</value>
      <webElementGuid>de96d526-3ddc-4c1b-bb44-7858830ee236</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div[2]/div[2]/div[4]/div/div[3]/textarea</value>
      <webElementGuid>ed9dd239-315a-4deb-857b-a381504d9e20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/textarea</value>
      <webElementGuid>23369aac-275c-4526-92ff-1c79cb222c8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
