<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>778eb623-86cc-441d-869f-37efda739c07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='piespages']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ad62534f-6ae7-4838-a29c-dcae2a6c0e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../Parts/BuyersGuideEnginebase_New.aspx?PartID=330384&amp;Category=Testing_Pmt&amp;Subcategory=Testing_Pmt&amp;PartDescription=Testing_Ecat&amp;Partno=Testing_Automation&amp;PageTitle=Parts+Application Data &amp;Productdescid=1832&amp;qty=1</value>
      <webElementGuid>d772d48a-fcda-4eba-a4d2-9f1a209f958b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;piespages&quot;)/iframe[1]</value>
      <webElementGuid>4a64efc2-aafc-4bbd-b693-49ac739d0fb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/iframe</value>
      <webElementGuid>020f8845-7716-48bd-a5ac-5cad50d08159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>46cb26de-0e1d-4431-b99a-6e3afb9bf125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '../Parts/BuyersGuideEnginebase_New.aspx?PartID=330384&amp;Category=Testing_Pmt&amp;Subcategory=Testing_Pmt&amp;PartDescription=Testing_Ecat&amp;Partno=Testing_Automation&amp;PageTitle=Parts+Application Data &amp;Productdescid=1832&amp;qty=1']</value>
      <webElementGuid>bf16f817-608f-447f-ae41-3ea79ae43fb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
