<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_It is a capital mistake to theorize b_843a1d</name>
   <tag></tag>
   <elementGuidId>5c56b2b8-a106-4f53-b671-69567188d175</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtPassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Password&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3eeb008f-4b8b-4124-98a0-fd5187749220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtPassword</value>
      <webElementGuid>b2ddb553-6d56-40cd-aec5-62993e65fa7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>770cb0ae-c7f1-46e3-afb9-b3b34865f60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>8d863ca7-701d-40ef-9b9d-d4746897c0d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtPassword</value>
      <webElementGuid>f1774db3-c742-4726-b953-d43e5f9508d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>f6b7b4a5-0922-4ecb-ade5-e0a8c891a61b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-input password-input</value>
      <webElementGuid>989cad68-ce1e-48a7-85c3-ba721ab6814e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtPassword&quot;)</value>
      <webElementGuid>78ff5ac2-eeaa-48e6-aaae-78e1556f7470</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtPassword']</value>
      <webElementGuid>4cb5a707-817d-4dec-8a3d-676b8007bb06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admin_login_main']/div[2]/label/input</value>
      <webElementGuid>a42839fc-e5c7-4b23-ad38-ec9f1b1af384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/input</value>
      <webElementGuid>a1964340-c4ab-4c2b-9c59-bc95dc98de46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtPassword' and @type = 'password' and @id = 'txtPassword' and @placeholder = 'Password']</value>
      <webElementGuid>9765b513-5fd2-448c-99da-24aab7b7094e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
