<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>9a8fc8c3-15e4-452f-b925-39d76ca18ad1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#KitInfo > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='KitInfo']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#KitInfo >> internal:role=img >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4515b285-a075-448e-bdbd-bce22f1796f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//bddemo.apapmt.com/Images/New_design_img/part_description.png</value>
      <webElementGuid>3550bebf-75b5-49a1-8afa-4753e208441b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;KitInfo&quot;)/img[1]</value>
      <webElementGuid>9d47e75b-3d85-4218-b548-61c32df18869</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='KitInfo']/img</value>
      <webElementGuid>06c7e883-39ee-45b3-bfd6-25adca351a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/img</value>
      <webElementGuid>36136dc5-0a71-40ba-890b-3fafa87a4cae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//bddemo.apapmt.com/Images/New_design_img/part_description.png']</value>
      <webElementGuid>6979339f-0259-4f71-86cd-2c4f9a669021</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
