<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Recommended_drpGTINQualifier</name>
   <tag></tag>
   <elementGuidId>ce9b9c5b-6b06-42e8-a7ca-e6cd6bf1ebfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drpGTINQualifier</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='drpGTINQualifier']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#drpGTINQualifier</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>afb6d4ae-9737-4f6d-a4a6-b48365d071a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drpGTINQualifier</value>
      <webElementGuid>f60ef706-44e9-4af9-8054-e3194111be09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>9c691fda-4b3a-4d3b-a656-8c93d60e0768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-SELECT-European Article Number (EAN) (2-5-5-1)U.P.C./EAN Consumer Package Code (1-5-5-1)</value>
      <webElementGuid>68728822-77e6-48c7-857e-c36d178f4622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drpGTINQualifier&quot;)</value>
      <webElementGuid>27370eb7-3bbe-487d-a661-f4b8f071fae0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='drpGTINQualifier']</value>
      <webElementGuid>b6a72101-49e5-4220-8143-f48088342a1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divData']/table/tbody/tr/td/table/tbody/tr/td[4]/select</value>
      <webElementGuid>ff521b0a-fe21-469d-ab5a-b8d4681a7c94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recommended.'])[1]/following::select[1]</value>
      <webElementGuid>5770d191-dc80-4f75-a818-630534607a94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Category'])[2]/preceding::select[1]</value>
      <webElementGuid>4518140e-27b1-4f50-bd4b-0e6a924ebb0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::select[1]</value>
      <webElementGuid>3a20e878-08db-4b6f-8b3c-cbf642315305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/select</value>
      <webElementGuid>7d1956b6-c55c-42c9-bfbf-1b63f731dec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'drpGTINQualifier' and (text() = '-SELECT-European Article Number (EAN) (2-5-5-1)U.P.C./EAN Consumer Package Code (1-5-5-1)' or . = '-SELECT-European Article Number (EAN) (2-5-5-1)U.P.C./EAN Consumer Package Code (1-5-5-1)')]</value>
      <webElementGuid>065361e6-b203-43de-9477-0ec69e981688</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
