<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Recommended_drpMinQtyUOM</name>
   <tag></tag>
   <elementGuidId>50c71a02-baab-45b5-97ee-5f58a7dac410</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drpMinQtyUOM</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='drpMinQtyUOM']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Status Min Qty UOM  Recommended . If this is filled up, Minimum Order Quantity also need to be provided.&quot;s] >> internal:role=combobox >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3f90353d-b9cc-447f-8dca-07dd6e7a7ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drpMinQtyUOM</value>
      <webElementGuid>fd99e2cc-652a-4cc0-b96d-6a23af65c0af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>169abffb-9798-4d6b-bfaa-62f399768fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-SELECT-AssortmentBagBookBottleBoxBucketBundleCanCardCartonCartridgeCaseClamshellCoilContainerCrateDozenDrumEachEnvelopeFootGallonHundredHundred CountJarKegKilogramKitLiterMeterPack (PAK)PackagePailPairPalletPallet Unit LoadPiecePintPoundQuartReelRodRollSetSheetSleeveSpoolStickThousandTrayTubeTwo Pack</value>
      <webElementGuid>50ee3ffd-693c-4cfd-b13d-5fdf19dec9c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drpMinQtyUOM&quot;)</value>
      <webElementGuid>88ec97a6-3daf-4440-8f3e-e7a21f0b7e8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='drpMinQtyUOM']</value>
      <webElementGuid>2e77d64e-e4c5-4b37-baab-8eada6d96cc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divData']/table/tbody/tr/td/table/tbody/tr[8]/td[4]/select</value>
      <webElementGuid>3570ee5a-9f23-495f-846e-1cd5cd45d3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recommended .'])[1]/following::select[1]</value>
      <webElementGuid>c451ef5a-9920-4d5e-af32-bcc8bd88c150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Effective Date'])[1]/preceding::select[1]</value>
      <webElementGuid>94e5d87e-c20b-45a4-b884-f71c5f06aae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inventory'])[1]/preceding::select[1]</value>
      <webElementGuid>9f18aefd-ec58-4904-8dce-b4dea5debc51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[4]/select</value>
      <webElementGuid>804bc292-f2fe-4184-ac35-3af00f20dbf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'drpMinQtyUOM' and (text() = '-SELECT-AssortmentBagBookBottleBoxBucketBundleCanCardCartonCartridgeCaseClamshellCoilContainerCrateDozenDrumEachEnvelopeFootGallonHundredHundred CountJarKegKilogramKitLiterMeterPack (PAK)PackagePailPairPalletPallet Unit LoadPiecePintPoundQuartReelRodRollSetSheetSleeveSpoolStickThousandTrayTubeTwo Pack' or . = '-SELECT-AssortmentBagBookBottleBoxBucketBundleCanCardCartonCartridgeCaseClamshellCoilContainerCrateDozenDrumEachEnvelopeFootGallonHundredHundred CountJarKegKilogramKitLiterMeterPack (PAK)PackagePailPairPalletPallet Unit LoadPiecePintPoundQuartReelRodRollSetSheetSleeveSpoolStickThousandTrayTubeTwo Pack')]</value>
      <webElementGuid>03c6f958-ae45-4631-a469-63cf878795ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
