<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__MainContent_txtPart</name>
   <tag></tag>
   <elementGuidId>0f2eb8cf-3bb5-445c-b5f5-b51d900e026d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MainContent_txtPart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='MainContent_txtPart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#MainContent_txtPart</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>72337b46-e28c-418d-bc07-72f227075c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$txtPart</value>
      <webElementGuid>b946ed7d-9ae5-4928-bd3e-24492d9551f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>ea47b780-96e9-4c00-9ed6-a68e3ae47de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>4c198ef9-9e3e-4788-b22e-8df8003ebebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainContent_txtPart</value>
      <webElementGuid>a3f4d0a2-4515-4d55-a86a-586860d17d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>numericValidation(); </value>
      <webElementGuid>4a78d306-980e-4b3e-8dad-f3eddf693a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>txtPartnoValidate(this)</value>
      <webElementGuid>fa34d461-82f9-483f-b403-91b43b327e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_txtPart&quot;)</value>
      <webElementGuid>3bdbf4c7-bf2b-4bc5-8a85-f64e18b5f8ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='MainContent_txtPart']</value>
      <webElementGuid>70ab0cd3-d24f-483c-a900-5bbae70f2d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divData']/table/tbody/tr/td/table/tbody/tr[6]/td[2]/textarea</value>
      <webElementGuid>90109856-93c2-4c5e-b028-38cc5d9cfdb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>b8a91937-d9d8-4c46-b674-7bfd6ef430f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$MainContent$txtPart' and @id = 'MainContent_txtPart']</value>
      <webElementGuid>257897d6-20d7-4e07-acfc-6e62b2dfa8b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
