<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__CompanyNamePIES</name>
   <tag></tag>
   <elementGuidId>dee2bd03-c397-453d-a488-f9f1d9ccf0ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CompanyNamePIES']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CompanyNamePIES</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#CompanyNamePIES</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ed1f3d8-b666-44de-8e4e-7e50f4493cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_input</value>
      <webElementGuid>51d45793-7480-4e7d-835a-0e25866139d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0892eaa7-8dcb-4127-b6f0-a50f704e874e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CompanyNamePIES</value>
      <webElementGuid>85d022e6-ba3d-42a2-a3b9-e07b2d15acca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CompanyNamePIES&quot;)</value>
      <webElementGuid>9221d762-8ad9-485a-81b8-6cdfc4a7edf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CompanyNamePIES']</value>
      <webElementGuid>e02c76fd-15bf-46f7-ac1b-92b4dfdd7222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divPIESExportFormat']/div/p/input</value>
      <webElementGuid>e4466ca9-aeaf-4c40-b6ac-90a3aa369b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/p/input</value>
      <webElementGuid>2e3fb6ca-9e22-4b84-95ed-98c63c2d6fdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'CompanyNamePIES']</value>
      <webElementGuid>aeecb2cf-3eb6-4bfb-8edb-33eba3c05ddd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
