<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PMT_delete_ImageButton35855</name>
   <tag></tag>
   <elementGuidId>0dd9cb4a-7115-4cfd-9e9a-b55c7aef0aed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='delete_ImageButton35855']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#delete_ImageButton35855</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'ctl00$MainContent$ImageButton2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#delete_ImageButton35855</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dbff0a2c-c83e-4530-95cf-aa70eaccded9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>30c19096-45d4-4680-a15a-5f19e46232e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$ImageButton2</value>
      <webElementGuid>90db3958-c954-4f0b-a428-f0b816549cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon_edit_del</value>
      <webElementGuid>d43f1265-4633-4315-b536-054c2cc7a926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delete_ImageButton35855</value>
      <webElementGuid>5ee4e202-16c8-45d7-89ea-ee594223a91f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../Images/New_design_img/delete_icon.png</value>
      <webElementGuid>a6884ec3-414c-4218-96c7-7fff3089d8ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>DeleteCatalog(35855);</value>
      <webElementGuid>7129716f-32b5-4cf0-b842-4434eb2eb380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delete_ImageButton35855&quot;)</value>
      <webElementGuid>110b53ba-c84a-43f0-b1c0-10d9b5a5e752</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='delete_ImageButton35855']</value>
      <webElementGuid>f5b85e86-02c3-4c18-90cd-0f90198df0b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='sortorder_val35855']/td[14]/div/span[2]/input</value>
      <webElementGuid>060514df-0dbc-424a-b794-95b483aef58f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[14]/div/span[2]/input</value>
      <webElementGuid>bba084e8-d83f-437b-bacc-f5a04e3fdb4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$MainContent$ImageButton2' and @id = 'delete_ImageButton35855' and @src = '../Images/New_design_img/delete_icon.png']</value>
      <webElementGuid>236f90f4-9e7d-4e56-8cf3-2d99d7fd40c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
