<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No-Override_piesbtnSave</name>
   <tag></tag>
   <elementGuidId>e2780636-e600-4a24-a709-18811d76e931</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#piesbtnSave</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='piesbtnSave']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Save&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18edb151-5e00-4828-97a2-73cc49536d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>45faf87b-f6c9-4d62-9514-72490241e135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>piesbtnSave</value>
      <webElementGuid>a38b6241-cad8-4cff-8584-2893d0ed606b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>96d385bb-b373-40d1-949a-3164d721ef2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button_save</value>
      <webElementGuid>0fc260f1-2ac1-4edd-ae7c-fd4893d03ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return checkModifyDatePIES();</value>
      <webElementGuid>b12be714-4af4-4530-b858-a0d10bad5405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;piesbtnSave&quot;)</value>
      <webElementGuid>c5a0b2b8-b293-4985-9b36-d1b7d6f8c511</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='piesbtnSave']</value>
      <webElementGuid>03c12184-4d18-4ab0-af67-b8f7e4d82544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div[2]/div[2]/div[3]/div[6]/div/input</value>
      <webElementGuid>3c2b7cd6-a366-4006-80c0-84c32ad11c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>87d9ee1e-7122-4f38-a245-08b15ef364d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'piesbtnSave']</value>
      <webElementGuid>f4822eb3-120f-45bb-a637-93193ec3bea3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
