<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>3b23c980-4ab9-4788-963e-b21c2c8d6f39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Package > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Package']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Package >> internal:role=img >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a685c5f5-ca6e-46eb-a977-e4c9c828a721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://qpmt-all.apapmt.com/Images/New_design_img/part_package.png</value>
      <webElementGuid>dc97a84e-f5bc-4c8f-8ccc-51708864a4b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Package&quot;)/img[1]</value>
      <webElementGuid>150470f3-0187-4995-bfba-47977f6ebf15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Package']/img</value>
      <webElementGuid>bd02dbb9-c825-4434-9665-d461e52d05b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://qpmt-all.apapmt.com/Images/New_design_img/part_package.png')]</value>
      <webElementGuid>8cacc478-31b9-425f-b77e-c1167627d43f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/img</value>
      <webElementGuid>544f2aa3-387e-4d03-8f1f-325fcfbb0566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://qpmt-all.apapmt.com/Images/New_design_img/part_package.png']</value>
      <webElementGuid>204ab2cb-7e81-4ee0-bc57-86dde3b73995</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
