<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>26abfee1-9d5c-491b-827d-7e9a4981d2de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#VendorDetails > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='VendorDetails']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ef6c0685-e2f4-44b8-b146-9c685e62ce36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//tealPartsdemo.apapmt.com/Images/New_design_img/inventory.png</value>
      <webElementGuid>36ff0146-f5dc-445d-8030-660ba2b709a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;VendorDetails&quot;)/img[1]</value>
      <webElementGuid>08d13142-f0cf-48c0-9c96-a2bbb558be8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='VendorDetails']/img</value>
      <webElementGuid>b4790753-186b-4ad2-98e7-ffcb7d6036a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[33]/img</value>
      <webElementGuid>675d8fea-696f-455c-b89e-39ccba2b520b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//tealPartsdemo.apapmt.com/Images/New_design_img/inventory.png']</value>
      <webElementGuid>1c877d1e-abb1-4ed3-91cd-22a11d5df66f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
