<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Low Stock_btnvenSave</name>
   <tag></tag>
   <elementGuidId>3f3c3c1f-9cf6-4894-9004-e46f22cd30aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnvenSave</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnvenSave']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bed01e55-749b-4bab-8552-54b3d63010cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>26443ad3-3c37-4406-945a-08c2f8f3fa2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnvenSave</value>
      <webElementGuid>68446aaf-c939-4e4b-b301-44fd07ed847f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>427f25cc-55dd-4000-8833-9ee4d710d8da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button_save</value>
      <webElementGuid>78cc4b6c-1923-4b74-8a33-642b6db3bf5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return checkModifyDatePartsVendor();</value>
      <webElementGuid>ce2116a6-a76c-4bc1-8dd9-8e6d3b67ff82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnvenSave&quot;)</value>
      <webElementGuid>5d90ffb8-5783-4b7c-9e88-06a610ce8833</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnvenSave']</value>
      <webElementGuid>34cc3e4f-eeae-4205-a8c2-fcb65bbffa53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div[2]/div/div[3]/div[13]/div/input[2]</value>
      <webElementGuid>730b88f9-fe66-4492-a642-79ef16f963f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/input[2]</value>
      <webElementGuid>d4bd152e-df43-49c7-b946-a0b9907da2f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnvenSave']</value>
      <webElementGuid>a86cf984-2d77-43b2-8eff-6f946fd683ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
