<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search By_txt_partno</name>
   <tag></tag>
   <elementGuidId>5a5b6b6c-9cb4-48e5-a285-9f840e646d40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_partno</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtsearchpartno']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Enter your part number&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>caeb3ff9-712f-45d9-8c57-89067fd97182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_partno</value>
      <webElementGuid>5c81cee4-c474-4f3e-a831-108e5daf87e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9e83e218-a3a1-49ee-9139-044f00541049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6c5c1f7b-f326-4df7-869f-00b0bf5946de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>71e8561d-a819-421c-b038-bdc7bd3e68dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>Javascript:if (event.keyCode==13) load_part_Details_popup();</value>
      <webElementGuid>71a57d3b-1163-4d4c-b3a6-d682d4c1a022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your part number</value>
      <webElementGuid>0e1ab0b2-1b75-4f98-ac17-3c166998e5ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>searchterm</value>
      <webElementGuid>fc1f00df-438b-48c1-bb38-8337740257c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_partno&quot;)</value>
      <webElementGuid>a3ae334e-0b47-47ad-ac56-3720288f1cf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_partno']</value>
      <webElementGuid>cfaadc1b-c770-43b2-be3f-4f5586473d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_upAttribute']/div[2]/div/div/div[3]/div/div[2]/input[6]</value>
      <webElementGuid>b64c0c99-9ff2-4d0c-aaee-e965f1d3bb39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input[6]</value>
      <webElementGuid>60c4d713-7c10-4cda-9162-19cd56ec8eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txt_partno' and @type = 'text' and @placeholder = 'Enter your part number']</value>
      <webElementGuid>15d4d3ee-3afd-4ee4-a13a-ce6cd3100e0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
