<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_image</name>
   <tag></tag>
   <elementGuidId>9805a203-4af4-4472-a8b3-9743a55d3a1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(9) > div > input[type=&quot;image&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='image'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Submit&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f79bb12c-45ef-418c-9457-bdcd5ccf58c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>a5b5a9f1-09c5-4af3-99d8-d9bb075ec971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://qpmt-all.apapmt.com/Images/edit_black.png</value>
      <webElementGuid>8bbad3fa-f081-4f1f-8d62-1996ad046bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>editAsset('7366', 'red.jpg');</value>
      <webElementGuid>3a8c3ac5-57a4-4f6b-85d8-d98325f2da45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTableViewer&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[9]/div[1]/input[1]</value>
      <webElementGuid>939010f6-134f-4e75-ab42-02240e4c5d5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='image'])[4]</value>
      <webElementGuid>f336f334-79d3-44bd-8f16-d40d7e0a500e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTableViewer']/tbody/tr/td[9]/div/input</value>
      <webElementGuid>bd95673b-9e39-43e0-a43e-8b9ef32ea0f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/div/input</value>
      <webElementGuid>e5903838-679a-4dd6-848e-e0eb0b8ee45b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @src = 'https://qpmt-all.apapmt.com/Images/edit_black.png']</value>
      <webElementGuid>6d7732e0-f5b6-4618-a36d-f77f9a8d90be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
