<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__drpAssetType</name>
   <tag></tag>
   <elementGuidId>5b9511f3-67e0-42e6-8157-463fc1ca8089</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='drpAssetType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#drpAssetType</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#drpAssetType</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b748f09d-668e-4e04-91c7-d999ca31fdd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_select</value>
      <webElementGuid>75273725-ddf9-4008-ad46-6c376cc3f4f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drpAssetType</value>
      <webElementGuid>705a684c-6e62-4e11-9778-46a124e0b384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-SELECT-360 Degree Image Set (360)Application Guide (APG)Audio File (AUD)Brochure (BRO)Buyers Guide (BUY)Case Study (CAS)Catalog (CAT)Certificate of Origin (CER)Datasheet (DAS)Ebook (EBK)Features and Benefits (FAB)Field Repair Guide (FRG)Full Engineering Drawing (FED)Hazardous Materials Info Sheet (HMS)Illustration Guide (ISG)Image Hotspotting (HOT)Installation Instructions (INS)Line Art (LIN)Link To Manufacturer Page (PAG)Logo Image (LGO)Material Safety Data Sheet (MSD)OEM Filename (OEM)Owner's Manual (OWN)Pallet Configuration Drawing (PAL)Photo - Close Up (P05)Photo - In Package (P02)Photo - Lifestyle View (P03)Photo - Mounted (P06)Photo - Out of Package (P01)Photo - Primary (P04)Photo - Unmounted (P07)Planogram Case Pack 1 (PP1)Planogram Case Pack 2 (PP2)Planogram Case Pack 3 (PP3)Planogram Consumer Pack 1 (PC1)Planogram Consumer Pack 2 (PC2)Planogram Consumer Pack 3 (PC3)Planogram Inner Pack 1 (PI1)Planogram Inner Pack 2 (PI2)Planogram Inner Pack 3 (PI3)Price Sheet (PST)Product Brochure  (PDB)Product Specifications Sheet (PSS)Quick Response Code (QR Code) (QRC)Regulatory Content Label (RGL)Research Bulletin (RES)Specification Sheet Filename  (SPE)Technical Bulletin (BUL)Technical Drawing (DRW)Thumbnail (THU)Tone Art (TON)User Defined (ZZ1)User Defined (ZZ2)User Defined (ZZ3)User Defined (ZZ4)User Defined (ZZ5)User Defined (ZZ6)User Defined (ZZ7)User Defined (ZZ8)User Defined (ZZ9)Video - General Information (VGL)Video - Installation (VIN)Video - Lifestyle (VLF)Video - Maintenance Care (VMC)Video - Primary (VID)Video - Technical Tips (VTT)Warranty (WAR)Whitepaper (WHP)</value>
      <webElementGuid>d58b8b89-2a96-4ccb-b85a-20b8d8274892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drpAssetType&quot;)</value>
      <webElementGuid>3240190d-b2e6-4966-8d1c-1880d304a047</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='drpAssetType']</value>
      <webElementGuid>95948802-5ff2-4048-b6b1-ecd2fc1fd6b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-2']/p[8]/select</value>
      <webElementGuid>aeb3407b-c658-4556-80dc-eac3530ffa64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/following::select[1]</value>
      <webElementGuid>a3661027-165c-4697-adbe-2994df5d337a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Representation'])[1]/preceding::select[1]</value>
      <webElementGuid>8cf0a7dc-dbdc-47fe-b2a9-fe3e5d2ba184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resolution'])[1]/preceding::select[2]</value>
      <webElementGuid>08d6316e-f8f3-4110-abb9-52f8e0d49bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[8]/select</value>
      <webElementGuid>6ddaf36c-26d6-412b-be88-51186c9115e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'drpAssetType' and (text() = concat(&quot;-SELECT-360 Degree Image Set (360)Application Guide (APG)Audio File (AUD)Brochure (BRO)Buyers Guide (BUY)Case Study (CAS)Catalog (CAT)Certificate of Origin (CER)Datasheet (DAS)Ebook (EBK)Features and Benefits (FAB)Field Repair Guide (FRG)Full Engineering Drawing (FED)Hazardous Materials Info Sheet (HMS)Illustration Guide (ISG)Image Hotspotting (HOT)Installation Instructions (INS)Line Art (LIN)Link To Manufacturer Page (PAG)Logo Image (LGO)Material Safety Data Sheet (MSD)OEM Filename (OEM)Owner&quot; , &quot;'&quot; , &quot;s Manual (OWN)Pallet Configuration Drawing (PAL)Photo - Close Up (P05)Photo - In Package (P02)Photo - Lifestyle View (P03)Photo - Mounted (P06)Photo - Out of Package (P01)Photo - Primary (P04)Photo - Unmounted (P07)Planogram Case Pack 1 (PP1)Planogram Case Pack 2 (PP2)Planogram Case Pack 3 (PP3)Planogram Consumer Pack 1 (PC1)Planogram Consumer Pack 2 (PC2)Planogram Consumer Pack 3 (PC3)Planogram Inner Pack 1 (PI1)Planogram Inner Pack 2 (PI2)Planogram Inner Pack 3 (PI3)Price Sheet (PST)Product Brochure  (PDB)Product Specifications Sheet (PSS)Quick Response Code (QR Code) (QRC)Regulatory Content Label (RGL)Research Bulletin (RES)Specification Sheet Filename  (SPE)Technical Bulletin (BUL)Technical Drawing (DRW)Thumbnail (THU)Tone Art (TON)User Defined (ZZ1)User Defined (ZZ2)User Defined (ZZ3)User Defined (ZZ4)User Defined (ZZ5)User Defined (ZZ6)User Defined (ZZ7)User Defined (ZZ8)User Defined (ZZ9)Video - General Information (VGL)Video - Installation (VIN)Video - Lifestyle (VLF)Video - Maintenance Care (VMC)Video - Primary (VID)Video - Technical Tips (VTT)Warranty (WAR)Whitepaper (WHP)&quot;) or . = concat(&quot;-SELECT-360 Degree Image Set (360)Application Guide (APG)Audio File (AUD)Brochure (BRO)Buyers Guide (BUY)Case Study (CAS)Catalog (CAT)Certificate of Origin (CER)Datasheet (DAS)Ebook (EBK)Features and Benefits (FAB)Field Repair Guide (FRG)Full Engineering Drawing (FED)Hazardous Materials Info Sheet (HMS)Illustration Guide (ISG)Image Hotspotting (HOT)Installation Instructions (INS)Line Art (LIN)Link To Manufacturer Page (PAG)Logo Image (LGO)Material Safety Data Sheet (MSD)OEM Filename (OEM)Owner&quot; , &quot;'&quot; , &quot;s Manual (OWN)Pallet Configuration Drawing (PAL)Photo - Close Up (P05)Photo - In Package (P02)Photo - Lifestyle View (P03)Photo - Mounted (P06)Photo - Out of Package (P01)Photo - Primary (P04)Photo - Unmounted (P07)Planogram Case Pack 1 (PP1)Planogram Case Pack 2 (PP2)Planogram Case Pack 3 (PP3)Planogram Consumer Pack 1 (PC1)Planogram Consumer Pack 2 (PC2)Planogram Consumer Pack 3 (PC3)Planogram Inner Pack 1 (PI1)Planogram Inner Pack 2 (PI2)Planogram Inner Pack 3 (PI3)Price Sheet (PST)Product Brochure  (PDB)Product Specifications Sheet (PSS)Quick Response Code (QR Code) (QRC)Regulatory Content Label (RGL)Research Bulletin (RES)Specification Sheet Filename  (SPE)Technical Bulletin (BUL)Technical Drawing (DRW)Thumbnail (THU)Tone Art (TON)User Defined (ZZ1)User Defined (ZZ2)User Defined (ZZ3)User Defined (ZZ4)User Defined (ZZ5)User Defined (ZZ6)User Defined (ZZ7)User Defined (ZZ8)User Defined (ZZ9)Video - General Information (VGL)Video - Installation (VIN)Video - Lifestyle (VLF)Video - Maintenance Care (VMC)Video - Primary (VID)Video - Technical Tips (VTT)Warranty (WAR)Whitepaper (WHP)&quot;))]</value>
      <webElementGuid>5fd58dd6-e7cd-4487-886c-eab748996a55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
