<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Wiper and Washer_save_btn_new_edit</name>
   <tag></tag>
   <elementGuidId>ddcde782-9f33-405d-8391-6dc61ff996a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#save_btn_new_edit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='save_btn_new_edit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#save_btn_new_edit</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4f25a5c6-8be3-44b6-a8b6-9aefe5df1c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>save_btn_new_edit</value>
      <webElementGuid>813bfa94-afd2-431c-b117-e713dcbcc85d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>btneditSave_Click()</value>
      <webElementGuid>5d8355e0-e08f-4e5f-b4df-d8f6f2a6dcc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>save display_inline_notimp</value>
      <webElementGuid>1a928902-7b34-4562-b173-ba1e4b07a2b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>16490a6a-6ff5-479e-97ca-d05cf7262eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;save_btn_new_edit&quot;)</value>
      <webElementGuid>951871e4-7aee-494a-9740-d9b2db25c843</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='save_btn_new_edit']</value>
      <webElementGuid>d0b735db-e9b0-4ad6-b32b-8492000096fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datacorner_new']/div[3]/div</value>
      <webElementGuid>1f276b56-19af-4afd-8f29-4b3aca625748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wiper and Washer'])[1]/following::div[2]</value>
      <webElementGuid>0f760587-1154-43cc-a0b4-7bb3d9bd28d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicles, Equipment, Tools, and Supplies'])[1]/following::div[2]</value>
      <webElementGuid>458065a3-db6c-4ced-968a-41b082f31041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[2]/preceding::div[1]</value>
      <webElementGuid>e2cba24b-ad25-462e-842d-807541303ca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Part Details'])[1]/preceding::div[13]</value>
      <webElementGuid>22efa0da-00a5-4cde-b19d-16536f497168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div</value>
      <webElementGuid>05f30a63-1a01-42d0-9098-5a4b4734ab25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'save_btn_new_edit' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>6afdee01-fcf6-44d8-9283-2b1aa5685cd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
