<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>8cb8a713-b89c-4d18-b722-ef265d832a2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='piespages']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>7337c254-9b83-40d4-a8ae-417af42f3ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../Parts/BuyersGuideEnginebase_New.aspx?PartID=330369&amp;Category=Testing_Pmt&amp;Subcategory=Testing_Pmt&amp;PartDescription=Testing_Ecat&amp;Partno=Testing_Automation&amp;PageTitle=Parts+Application Data &amp;Productdescid=1823&amp;qty=1</value>
      <webElementGuid>9fe056cd-803c-4ecf-a3c8-c3adfb0078f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;piespages&quot;)/iframe[1]</value>
      <webElementGuid>b211497f-6f75-402a-862c-9fd467e0731f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/iframe</value>
      <webElementGuid>f6f53ec6-4cd6-4526-ab6d-92ff8eb6b5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>74af8495-7a66-4af8-8ba3-878a42ac2399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '../Parts/BuyersGuideEnginebase_New.aspx?PartID=330369&amp;Category=Testing_Pmt&amp;Subcategory=Testing_Pmt&amp;PartDescription=Testing_Ecat&amp;Partno=Testing_Automation&amp;PageTitle=Parts+Application Data &amp;Productdescid=1823&amp;qty=1']</value>
      <webElementGuid>0e62d74b-17c7-4df8-aacc-5680cbc40841</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
