<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>f58f6606-bd0f-4dbd-9bd5-2a97eb1e6836</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BuyersGuid1 > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='BuyersGuid1']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#BuyersGuid1 >> internal:role=img >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a2c7b53f-1a0a-4454-8452-6b92e40cf83f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//bddemo.apapmt.com/Images/New_design_img/part_buyer_guide.png</value>
      <webElementGuid>3b6f2d87-5323-406c-a1a1-ae5e4a28cb37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BuyersGuid1&quot;)/img[1]</value>
      <webElementGuid>76fd7cbf-53cd-4770-855a-a81e17e049cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BuyersGuid1']/img</value>
      <webElementGuid>9593cba5-8140-4443-ac05-d76a40200a05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>d3cce9b7-80c1-43b8-802a-43363f1ad2f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//bddemo.apapmt.com/Images/New_design_img/part_buyer_guide.png']</value>
      <webElementGuid>c40b4120-89df-4504-a2fc-c7e2b6c72adf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
