<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_More Info_MainContent_GvApplications__613d0d</name>
   <tag></tag>
   <elementGuidId>def7d85d-2917-4327-95ee-c07dd56c791e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MainContent_GvApplications_chkActivee1_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MainContent_GvApplications_chkActivee1_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#MainContent_GvApplications_chkActivee1_0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36ab8aeb-17f6-4619-b2f9-9136927cff36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainContent_GvApplications_chkActivee1_0</value>
      <webElementGuid>1d297c6b-4a8f-45d1-b9ac-9f0cccae41bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>56e01185-9147-411e-8c32-baa6ab3bdedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$GvApplications$ctl02$chkActivee1</value>
      <webElementGuid>b902239b-449c-471c-82d6-ae6fccd1131b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_GvApplications_chkActivee1_0&quot;)</value>
      <webElementGuid>08905947-40c3-4a96-9630-5a5a4efd0045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Parts segment/Application/Without Enginee Select/With Attribute/Add Application/Page_BDDemoPMT/iframe</value>
      <webElementGuid>7cfb8062-7a91-4a18-9e12-9e1a0af13f27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MainContent_GvApplications_chkActivee1_0']</value>
      <webElementGuid>ae791702-7d3b-492b-8d0b-92544bd29856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='MainContent_GvApplications']/tbody/tr[2]/td/span/input</value>
      <webElementGuid>3aee22b5-cd42-41db-9a8f-359eb3876925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span/input</value>
      <webElementGuid>2b716841-0119-42b4-8280-2932ea1d7e00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MainContent_GvApplications_chkActivee1_0' and @type = 'checkbox' and @name = 'ctl00$MainContent$GvApplications$ctl02$chkActivee1']</value>
      <webElementGuid>f4e7e660-d122-4f9c-9e16-6b8e992e2ea8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
