<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Region_MainContent_dlDisplayColumnLis_a29b34</name>
   <tag></tag>
   <elementGuidId>54f30c18-aeb6-4ecd-a189-0b448ab55df1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MainContent_dlDisplayColumnList_chkselectAll1_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MainContent_dlDisplayColumnList_chkselectAll1_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Region All&quot;i] >> internal:label=&quot;All&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e91b0dc2-6106-4dfd-bdf8-0f786d0cd9bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainContent_dlDisplayColumnList_chkselectAll1_0</value>
      <webElementGuid>c698fea0-63ca-481b-aa18-04de97a29f7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b0195006-86b4-420a-a4bd-7a7bc72e1b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$dlDisplayColumnList$ctl00$chkselectAll1</value>
      <webElementGuid>a74c5b22-645b-4690-8544-ed0c3544eac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CheckAllGrid(this);</value>
      <webElementGuid>eb2fdcb4-8962-4c99-9241-23e5e50134d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_dlDisplayColumnList_chkselectAll1_0&quot;)</value>
      <webElementGuid>b802ecc7-709b-4fcb-8752-359e04db147c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Parts segment/Application/Without Enginee Select/With Attribute/Add Application/Page_BDDemoPMT/iframe</value>
      <webElementGuid>e30ba375-3951-4f47-b18c-5f77df79bd4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MainContent_dlDisplayColumnList_chkselectAll1_0']</value>
      <webElementGuid>5530b693-14f6-4c90-8b03-f2ace537d628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_dlDisplayColumnList_UpdatePanel5_0']/h3/span/span/input</value>
      <webElementGuid>e8407531-f90e-49a3-be01-8d92585bfe12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/span/span/input</value>
      <webElementGuid>e7cd4a2d-86bc-4dd3-9c30-21f341989f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MainContent_dlDisplayColumnList_chkselectAll1_0' and @type = 'checkbox' and @name = 'ctl00$MainContent$dlDisplayColumnList$ctl00$chkselectAll1']</value>
      <webElementGuid>df0e12f0-b014-457f-aa24-2bc5f0f3d168</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
