<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_XML_ucMenu_rptLevel1_lnkLink1_1</name>
   <tag></tag>
   <elementGuidId>f2c4023a-a5f6-47f8-a918-cbd2253fe914</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucMenu_rptLevel1_lnkLink1_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Vehicle')])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Vehicle&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>70deaaf4-eb08-4fb9-aa36-242359f60b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucMenu_rptLevel1_lnkLink1_1</value>
      <webElementGuid>a81fa37f-7afd-4f86-b42d-87aeaa2ed86f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main_menu vehicle_icon active</value>
      <webElementGuid>510c117d-474c-4eb3-8309-c99e546df282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../Applications/Applnlist.aspx?PageTitle=Applications Data</value>
      <webElementGuid>5720a26b-011d-4399-9a51-590a3ca10fc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vehicle</value>
      <webElementGuid>8b12a0e1-76de-47d7-8a85-88e6ab7e9efb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucMenu_rptLevel1_lnkLink1_1&quot;)</value>
      <webElementGuid>7c299034-5a03-4945-ae65-3d116f7e2b22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucMenu_rptLevel1_lnkLink1_1']</value>
      <webElementGuid>5e53d42f-7769-4cb8-85a6-44c44e4488ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='ucMenu_rptLevel1_l1_1']/a</value>
      <webElementGuid>7e5a58af-1504-4f6a-b8e8-682faf1d6bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Vehicle')])[3]</value>
      <webElementGuid>ce4d9538-e35a-44a9-b98c-34557e7f848e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XML'])[1]/following::a[1]</value>
      <webElementGuid>20367983-2cb2-472e-bbc3-44a0caa68193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Excel'])[1]/following::a[2]</value>
      <webElementGuid>44403b0a-9421-4ee4-8f5e-59cc14bbbb64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Equipment'])[1]/preceding::a[1]</value>
      <webElementGuid>ea4dd3d9-3f04-47c1-b460-66bd206c9728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parts'])[1]/preceding::a[2]</value>
      <webElementGuid>1be00d58-f271-4a48-afb6-6c2c1f0ba732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vehicle']/parent::*</value>
      <webElementGuid>39441a3f-e298-439f-a90b-9465a72d22c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '../Applications/Applnlist.aspx?PageTitle=Applications Data')]</value>
      <webElementGuid>6fd681eb-2d00-4a36-ace3-02a1754854f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>70038390-4662-439c-8479-1a73b1a00390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucMenu_rptLevel1_lnkLink1_1' and @href = '../Applications/Applnlist.aspx?PageTitle=Applications Data' and (text() = 'Vehicle' or . = 'Vehicle')]</value>
      <webElementGuid>266b3836-001b-4af4-8c0d-027cb3613fbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
