<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_MfrLabel_MainContent_btnAdd</name>
   <tag></tag>
   <elementGuidId>13d6c42d-b398-487d-9c46-97459e8afa9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MainContent_btnAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='MainContent_btnAdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Add&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ef78e533-2f3e-4a64-983e-ef713736779c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>__doPostBack('ctl00$MainContent$btnAdd','')</value>
      <webElementGuid>65e7813e-463e-4036-bdc7-80a39bf22b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainContent_btnAdd</value>
      <webElementGuid>9b6f6c92-ee7d-4a71-861a-e898d5f7031f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add_button_icon</value>
      <webElementGuid>b8b0e73e-a667-4324-8ee3-bb0c5c2cf8ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>fb904303-8d5f-4d90-8a69-75c6e3c06c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_btnAdd&quot;)</value>
      <webElementGuid>eca973ab-9a63-4ca4-a8a8-3954683d492f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='MainContent_btnAdd']</value>
      <webElementGuid>c7f64708-553b-410b-9463-672640e772cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_div_partdescription']/div/p[7]/button</value>
      <webElementGuid>dc183551-b3ac-444e-bcc9-72e35f37ca03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MfrLabel :'])[1]/following::button[1]</value>
      <webElementGuid>20556c42-c1d7-46c9-afc1-e66f2f419ba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notes :'])[1]/following::button[1]</value>
      <webElementGuid>885b1b6b-8481-4b9f-91ac-5f588fc8ea32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Part#'])[2]/preceding::button[1]</value>
      <webElementGuid>e3a03382-53e9-40a6-b4b0-be186d31ba79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Line'])[3]/preceding::button[1]</value>
      <webElementGuid>2ce2c53c-823d-4722-a1d0-2c44843626f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>29923a0d-22ab-42c8-879b-3e80950148a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[7]/button</value>
      <webElementGuid>5dadb6df-4935-4c11-91b9-c6ac5afe0498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'MainContent_btnAdd' and (text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>0dd45c84-1618-4023-9ac8-500a6caae9a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
