<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Delete_MainContent_GVData_chkActivee1_0</name>
   <tag></tag>
   <elementGuidId>31d4389f-6ab0-4b95-b7c0-4d573c27945a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MainContent_GVData_chkActivee1_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MainContent_GVData_chkActivee1_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#MainContent_GVData_chkActivee1_0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0674234e-735f-45ff-8c57-cb39151bfddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainContent_GVData_chkActivee1_0</value>
      <webElementGuid>d6f9beec-a50d-47a2-93bf-eb26011eaa57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>34b195d6-3d3c-4f30-a632-54b9dbe63121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$GVData$ctl02$chkActivee1</value>
      <webElementGuid>23bfbcd1-825e-4e5d-93ca-cf23c00351fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_GVData_chkActivee1_0&quot;)</value>
      <webElementGuid>ce019c61-23a4-41f3-b321-f916bb044e64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MainContent_GVData_chkActivee1_0']</value>
      <webElementGuid>133bb40d-1d35-4ade-8bbc-a15086e4d41a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='MainContent_GVData']/tbody/tr[2]/td/span/input</value>
      <webElementGuid>f4ebff9c-cca2-42a3-8c7f-2b3bfde62348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span/input</value>
      <webElementGuid>326e72f3-1846-478f-9981-a6956642cd0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MainContent_GVData_chkActivee1_0' and @type = 'checkbox' and @name = 'ctl00$MainContent$GVData$ctl02$chkActivee1']</value>
      <webElementGuid>211e9143-599a-480e-9f62-5aaa4ba1fdf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
