<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__DrpLine</name>
   <tag></tag>
   <elementGuidId>3044653b-a306-444c-9843-669d9e714209</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DrpLine</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DrpLine']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Line *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4ff493cf-9753-4d1d-90c2-9cc0bb835d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DrpLine</value>
      <webElementGuid>97bfaae7-488b-4a78-af49-4ee8248bfc0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-SELECT-ALLAPEX | AP ExhaustAuto | AutoBBBB | 3MBDMJ | BruteBEC | BeckArnleyBFNK | Motorcar Parts of America IncBKRM | AutoZone IncCARD | Cardone RemanCDXT | DronningborgCPCM | MRCDPGF | Newell Rubbermaid IncDWDK | Nippon Oil CorporationFDCC | Ride Control LLCGGBF | Evolution DrivelineGTQB | KTM Sportmotorcycle GmbHHLYF | Sensata TechnologiesHSSQ | Arrowhead Electrical Products IncJLYQ | Pevisa Auto Parts SAJOD | JonDonKYYF | JN ElectricRCI | Reach CoolingREV | RevolutionRole MfrLine | Rolemanagement mfrLineRULE | BussinessRulesSandF | SandFSandQ | SandQSandS | SandSSandX | SandXSID | SIDEMTES | TESTUSA | USA CleanZZZZ | Others</value>
      <webElementGuid>f2bd1f38-aa83-468b-931b-ddbcb26df146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DrpLine&quot;)</value>
      <webElementGuid>dc91a3de-48eb-4a38-a61d-b98235d12fe1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DrpLine']</value>
      <webElementGuid>0e84ee4a-c528-4353-93a5-adcfae7da425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='Linelbldrp']/select</value>
      <webElementGuid>42d68222-8279-4d72-8533-8eb86cb49402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[1]</value>
      <webElementGuid>1eec9ff7-d4d8-4128-9991-bc92a54176a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ebay :'])[1]/preceding::select[1]</value>
      <webElementGuid>9eeb7223-ecb5-445a-854f-339fb919b9dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interchange :'])[1]/preceding::select[2]</value>
      <webElementGuid>ae48ae92-e0a3-419b-8cd3-9aa6c67b1a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>320a300a-6e9c-45f7-ae37-782db89615ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DrpLine' and (text() = '-SELECT-ALLAPEX | AP ExhaustAuto | AutoBBBB | 3MBDMJ | BruteBEC | BeckArnleyBFNK | Motorcar Parts of America IncBKRM | AutoZone IncCARD | Cardone RemanCDXT | DronningborgCPCM | MRCDPGF | Newell Rubbermaid IncDWDK | Nippon Oil CorporationFDCC | Ride Control LLCGGBF | Evolution DrivelineGTQB | KTM Sportmotorcycle GmbHHLYF | Sensata TechnologiesHSSQ | Arrowhead Electrical Products IncJLYQ | Pevisa Auto Parts SAJOD | JonDonKYYF | JN ElectricRCI | Reach CoolingREV | RevolutionRole MfrLine | Rolemanagement mfrLineRULE | BussinessRulesSandF | SandFSandQ | SandQSandS | SandSSandX | SandXSID | SIDEMTES | TESTUSA | USA CleanZZZZ | Others' or . = '-SELECT-ALLAPEX | AP ExhaustAuto | AutoBBBB | 3MBDMJ | BruteBEC | BeckArnleyBFNK | Motorcar Parts of America IncBKRM | AutoZone IncCARD | Cardone RemanCDXT | DronningborgCPCM | MRCDPGF | Newell Rubbermaid IncDWDK | Nippon Oil CorporationFDCC | Ride Control LLCGGBF | Evolution DrivelineGTQB | KTM Sportmotorcycle GmbHHLYF | Sensata TechnologiesHSSQ | Arrowhead Electrical Products IncJLYQ | Pevisa Auto Parts SAJOD | JonDonKYYF | JN ElectricRCI | Reach CoolingREV | RevolutionRole MfrLine | Rolemanagement mfrLineRULE | BussinessRulesSandF | SandFSandQ | SandQSandS | SandSSandX | SandXSID | SIDEMTES | TESTUSA | USA CleanZZZZ | Others')]</value>
      <webElementGuid>626adac2-fc1d-4cd6-bb30-bf59c440baaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
