<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_ALL ENGINES_MainContent_GvApplicat_b57c46</name>
   <tag></tag>
   <elementGuidId>24bd4215-b7c9-48cb-9899-3d391acb63b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MainContent_GvApplications_txtapppartsnotes_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='MainContent_GvApplications_txtapppartsnotes_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#MainContent_GvApplications_txtapppartsnotes_0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e34965c2-02f2-4a03-8691-eea3627b3a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$GvApplications$ctl02$txtapppartsnotes</value>
      <webElementGuid>c4f5f474-8fa4-43c5-a3e3-3c52faf9dbc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>dd3bb681-7d73-4527-8ce4-07ecc53fabe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>9d8ce32c-6486-49bf-883c-9d698b645a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainContent_GvApplications_txtapppartsnotes_0</value>
      <webElementGuid>5136dc44-f900-40b8-83d7-90758b090539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_GvApplications_txtapppartsnotes_0&quot;)</value>
      <webElementGuid>0e0e8b32-52d0-4d29-b1a5-fd794a07af13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Parts segment/Application/Without Enginee Select/Without Attribute/Add Application/Page_BDDemoPMT/iframe</value>
      <webElementGuid>21a5e41b-9953-41e7-8d45-7dde8bb8d01a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='MainContent_GvApplications_txtapppartsnotes_0']</value>
      <webElementGuid>66542b92-4404-4a4f-80a0-fbd0ebeef29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='MainContent_GvApplications']/tbody/tr[2]/td[4]/textarea</value>
      <webElementGuid>33b55332-30ee-45a5-8bee-2715d8038849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>98f7fdbe-92a3-422b-89b2-b6a3d274d0c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$MainContent$GvApplications$ctl02$txtapppartsnotes' and @id = 'MainContent_GvApplications_txtapppartsnotes_0']</value>
      <webElementGuid>f8cfeba9-d6d0-48a8-a186-decabcc67c82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
