<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Price Break Quantity_txtPriceBreak</name>
   <tag></tag>
   <elementGuidId>e39c13c1-6de4-4443-917b-46c719cddfbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtPriceBreak</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtPriceBreak']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtPriceBreak</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a17b6784-3210-49ae-9f38-65c016a3abfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_input</value>
      <webElementGuid>40c638a1-0ff1-4efd-8ed7-7992f8c710d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtPriceBreak</value>
      <webElementGuid>3cae5cf8-053e-477b-9dc8-8464d46b7301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>c2b0596e-2f4f-4204-ad86-abb0bbac81b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4b2cff11-a673-4046-ac8c-7c7904b4c049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return NoDecimal(event)</value>
      <webElementGuid>f22e987e-6234-469b-8ba3-36b719c3af94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtPriceBreak&quot;)</value>
      <webElementGuid>91ccf10f-9a72-4081-b4db-b284d435e829</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtPriceBreak']</value>
      <webElementGuid>56c3604f-67aa-47e5-a6f3-ad825edb4864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div[2]/div/div[3]/div[6]/input</value>
      <webElementGuid>6de79b1f-cf75-4b97-aaac-8aa8b916b770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div[3]/div[6]/input</value>
      <webElementGuid>00a54003-df17-4e34-a763-c58baaa05c8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtPriceBreak']</value>
      <webElementGuid>a28b177e-64fd-477e-9ba8-e83fa7987be1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
