<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Effective Date_txtEffectivecalender</name>
   <tag></tag>
   <elementGuidId>deb16e3e-11ce-4860-994d-1f517bb9691c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtEffectivecalender</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtEffectivecalender']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtEffectivecalender</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>00f5a556-8c76-4bb0-9875-bdf53d5e0f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_input hasDatepicker</value>
      <webElementGuid>00210d1f-1cb4-43c7-acfc-2b796f7723fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtEffectivecalender</value>
      <webElementGuid>ce444d88-655d-47d4-9078-f02ccd5ddd82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.blur()</value>
      <webElementGuid>2b85d37b-a63e-4e37-83e4-6a880f218fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtEffectivecalender&quot;)</value>
      <webElementGuid>961b7b38-67b5-49d2-9ead-270cf50dabe0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtEffectivecalender']</value>
      <webElementGuid>a46fa134-9438-45bb-a821-0a8fed38c3e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div[2]/div/div[3]/div[3]/input</value>
      <webElementGuid>c542c5e0-830f-4088-a62d-22ae534a2e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div[3]/div[3]/input</value>
      <webElementGuid>4232c55f-8c93-4bce-86e3-8eb122328861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtEffectivecalender']</value>
      <webElementGuid>40cd404a-9fe8-4c96-a310-2d8dc69a0a16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
