<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Currency Code_drpCurrencyCode</name>
   <tag></tag>
   <elementGuidId>cd4d4e81-1313-4a5a-9dcc-a52077bd3ffc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drpCurrencyCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='drpCurrencyCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#drpCurrencyCode</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>12705f78-6bde-4a13-9da4-ad302d6eb293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_select</value>
      <webElementGuid>893fb87a-53d4-4472-9803-c07843a717ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drpCurrencyCode</value>
      <webElementGuid>af04f149-b80f-4d23-8aa9-195c19d16c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Canadian DollarChina Yuan RenminbiEuropean Composite UnitEuropean EUROEuropean Monetary UnitHong Kong DollarMexican PesosU.S. DollarUnited Kingdom Pound Sterling</value>
      <webElementGuid>9a2ae674-444d-458c-a5af-7e4b398145ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drpCurrencyCode&quot;)</value>
      <webElementGuid>e7eb9269-a7a6-497d-b297-5841a7490067</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='drpCurrencyCode']</value>
      <webElementGuid>7c6319ca-714d-495b-9d59-1d66b643ad48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div[2]/div/div[3]/div[11]/select</value>
      <webElementGuid>63fbf701-0b93-4af7-ac07-4af1a98b677f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currency Code'])[1]/following::select[1]</value>
      <webElementGuid>c5390a65-859f-465d-83b8-fbec1a539565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price Type Description'])[1]/following::select[1]</value>
      <webElementGuid>64cdda1f-8245-43d4-b83a-db0911d8fe19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price Multiplier'])[1]/preceding::select[1]</value>
      <webElementGuid>0f0ae035-5adb-44d9-8cc2-22c5379c550b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/select</value>
      <webElementGuid>261b3ca6-9a05-4eee-9380-aafb9f5a3f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'drpCurrencyCode' and (text() = '--Select--Canadian DollarChina Yuan RenminbiEuropean Composite UnitEuropean EUROEuropean Monetary UnitHong Kong DollarMexican PesosU.S. DollarUnited Kingdom Pound Sterling' or . = '--Select--Canadian DollarChina Yuan RenminbiEuropean Composite UnitEuropean EUROEuropean Monetary UnitHong Kong DollarMexican PesosU.S. DollarUnited Kingdom Pound Sterling')]</value>
      <webElementGuid>ef1e0396-14f6-47f0-9bbc-f6b63e83b1f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
