<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Brand Master_ucMenu_rptLevel1_rptLevel2_0_47c4f4</name>
   <tag></tag>
   <elementGuidId>43f9a0de-6014-4bf5-9194-3b8b0df9893d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucMenu_rptLevel1_rptLevel2_0_rptLevel3_0_lnkLink3_4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Product Line')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Product Line&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6cae4e80-1e0b-42de-89c0-67376ff477ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucMenu_rptLevel1_rptLevel2_0_rptLevel3_0_lnkLink3_4</value>
      <webElementGuid>51bb8cb6-7a04-4933-b89f-26d8e6655431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>AddMfrBrand.aspx?PageTitle=Product Line</value>
      <webElementGuid>75b6d4f9-9c41-4213-a792-9b8e6710692e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Product Line</value>
      <webElementGuid>6a5806ae-8f90-4ad6-8d9e-f0118f5fa27e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucMenu_rptLevel1_rptLevel2_0_rptLevel3_0_lnkLink3_4&quot;)</value>
      <webElementGuid>01029639-b7d2-4bce-b668-9de7e8150c69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucMenu_rptLevel1_rptLevel2_0_rptLevel3_0_lnkLink3_4']</value>
      <webElementGuid>0519d40e-c43e-4bde-a195-87076353bbcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='ucMenu_rptLevel1_l1_0']/div/div/div/div/a[5]</value>
      <webElementGuid>3cf180fa-c18f-4b27-be86-5a3eabdc59b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Product Line')]</value>
      <webElementGuid>8463ad18-e8c3-4377-ab96-866b5e6573da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand Master'])[1]/following::a[1]</value>
      <webElementGuid>2a0d6c55-4f8e-4ca5-a6b2-b2e5407853bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Receiver Files'])[1]/following::a[2]</value>
      <webElementGuid>17bbed0c-cb1d-4fa0-8381-789e47b5e97c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Web Category'])[1]/preceding::a[1]</value>
      <webElementGuid>35dba5e4-13f1-4a48-b87d-e720962e89b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub Product Line Master'])[1]/preceding::a[2]</value>
      <webElementGuid>63f9ed6e-d406-4d93-9516-78736b4ea8a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Product Line']/parent::*</value>
      <webElementGuid>ed2a548a-12a0-4621-ad1b-373d561c0c84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'AddMfrBrand.aspx?PageTitle=Product Line')]</value>
      <webElementGuid>489009f0-1a09-4404-9bbd-7d34c1e6b34a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]</value>
      <webElementGuid>0500b312-26b2-4ebb-969b-295739eaf6c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucMenu_rptLevel1_rptLevel2_0_rptLevel3_0_lnkLink3_4' and @href = 'AddMfrBrand.aspx?PageTitle=Product Line' and (text() = 'Product Line' or . = 'Product Line')]</value>
      <webElementGuid>1c694f11-299b-4d29-8e36-42c5b453bbe0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
