<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Vendor Master_ucMenu_rptLevel1_rptLevel2__5603b8</name>
   <tag></tag>
   <elementGuidId>ccccc4bc-4263-4d5e-8d30-d0072cd73235</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucMenu_rptLevel1_rptLevel2_0_rptLevel3_0_lnkLink3_17</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Part Description')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Part Description&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fa26e342-4e7d-4740-9cd7-c8d7138f4149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucMenu_rptLevel1_rptLevel2_0_rptLevel3_0_lnkLink3_17</value>
      <webElementGuid>4fd64cf1-eb3a-4232-9325-b6adbea8314a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>PartDescription_New.aspx?PageTitle=Part Description</value>
      <webElementGuid>530737a1-0a90-481f-afc1-978cfea35bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Part Description</value>
      <webElementGuid>1909dc5e-0c21-44af-a5fc-3911e4ece7ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucMenu_rptLevel1_rptLevel2_0_rptLevel3_0_lnkLink3_17&quot;)</value>
      <webElementGuid>d17ebda0-ae63-4612-9bc9-cdb894825e19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucMenu_rptLevel1_rptLevel2_0_rptLevel3_0_lnkLink3_17']</value>
      <webElementGuid>4888ac1d-a330-4e91-bba2-6342f3971abd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='ucMenu_rptLevel1_l1_0']/div/div/div/div/a[18]</value>
      <webElementGuid>4dc18fc1-997b-436d-823e-c334075274a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Part Description')]</value>
      <webElementGuid>14ac3710-0dad-423d-90c6-29db37f025ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor Master'])[1]/following::a[1]</value>
      <webElementGuid>014429ae-c120-406e-a20a-ecf66c1d3d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor Product Line'])[1]/following::a[2]</value>
      <webElementGuid>727811c9-4320-42de-aec9-d3de6987e51f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MarketPlace Import'])[1]/preceding::a[1]</value>
      <webElementGuid>39f22f33-b714-416a-82a8-cbfea9beca78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Web SubCategory'])[1]/preceding::a[2]</value>
      <webElementGuid>d0ce1a20-4eb8-4d6c-b036-11cee27749d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'PartDescription_New.aspx?PageTitle=Part Description')]</value>
      <webElementGuid>f7a51a32-44e7-4b4a-ac67-9a7c6deaa51c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[18]</value>
      <webElementGuid>d246e948-cd29-41ea-bedc-1643b7620ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucMenu_rptLevel1_rptLevel2_0_rptLevel3_0_lnkLink3_17' and @href = 'PartDescription_New.aspx?PageTitle=Part Description' and (text() = 'Part Description' or . = 'Part Description')]</value>
      <webElementGuid>98a27241-367e-4509-8623-860c7d40417e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
