<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Type_MainContent_btnsearch</name>
   <tag></tag>
   <elementGuidId>77729d87-ebae-42e3-bed3-1ed529692e9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MainContent_btnsearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MainContent_btnsearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c7cfe67-f37a-4521-8d38-083bc2025cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>3d256b8f-03a0-4589-9b37-7f8198178d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$btnsearch</value>
      <webElementGuid>b92a8539-f5b8-4d79-84dd-ba9bfda8846d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>View Associated Applications</value>
      <webElementGuid>7acb38e4-1237-4628-a63a-dd5257d63f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return searchvalidate();</value>
      <webElementGuid>92b81027-21df-4540-ac10-eb3cd60bc057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainContent_btnsearch</value>
      <webElementGuid>a38aac69-75ad-43c1-8f92-11b7fa034bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button_search m_t_20</value>
      <webElementGuid>31ce13c8-3f47-4652-99af-31066471bbd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_btnsearch&quot;)</value>
      <webElementGuid>500a23f3-cce0-45d4-ad57-80f6a85c4818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Parts segment/Application/Edit new application/Page_EcatPMT/iframe</value>
      <webElementGuid>a027877e-7301-4e36-b1e2-6775cc61b1b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MainContent_btnsearch']</value>
      <webElementGuid>b0267468-3fcf-41b1-a506-c0306c469aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_div_searchfilter']/b/span[3]/input</value>
      <webElementGuid>ea0694f6-7453-4620-96c4-48bf96222e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/input</value>
      <webElementGuid>fa1ebcc7-84ae-4d8c-a052-9cd120631d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$MainContent$btnsearch' and @id = 'MainContent_btnsearch']</value>
      <webElementGuid>d2818e2c-bd69-4e21-99bd-0836927f4447</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
