<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txtTealpartno</name>
   <tag></tag>
   <elementGuidId>01af39f4-d442-4384-8648-9dbba22ea057</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtTealpartno</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtTealpartno']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dff794c7-3a40-486b-b9f8-c3e9608dd164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d4f00ca5-b76d-4c8a-9a1d-ba340b5ecdf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ea24687b-bfe1-44a8-a0e7-1014d1984aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtTealpartno</value>
      <webElementGuid>1df96b35-a323-4f11-bd17-15580cec2ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>PartnotxtValidate(this)</value>
      <webElementGuid>644ab1df-72a6-4bd7-bfcb-f322e9b83873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtTealpartno&quot;)</value>
      <webElementGuid>59753a2a-7ba1-449b-af4d-46ce0e58664b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtTealpartno']</value>
      <webElementGuid>bb804e06-bb4f-4f8d-9bea-9e3331c671ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lobipanel-parent']/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>5e1ee339-e892-4a29-9157-5a63ab14b457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>e8638fcd-6a6a-4b5b-89c2-271d82226bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtTealpartno']</value>
      <webElementGuid>ebbef656-4382-486f-8a96-ea6d5e9f6d1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
