<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txtsuffix</name>
   <tag></tag>
   <elementGuidId>45cc43bb-f613-4cd0-a757-b2cc265c98d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtsuffix</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtsuffix']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9add6a5b-ee05-4319-9e19-d18d9c5db23d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4412d95b-6885-483b-815c-ed5f3a3d0b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>323aa533-194a-4c80-9f43-d8da603f5948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtsuffix</value>
      <webElementGuid>7fdb8712-0048-428e-a9fe-ba44fae508ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>this.value = this.value.toUpperCase();</value>
      <webElementGuid>2443d914-7c83-41d9-9e54-ab54f3523db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>69cd0a2c-3f3b-4472-bbb5-c7b9ea54ff8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>16101115-8c4e-4898-9e62-05791ea1f7ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtsuffix&quot;)</value>
      <webElementGuid>18ae3ca9-7e21-4cd0-8336-219b422907d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtsuffix']</value>
      <webElementGuid>cfc2d7ef-8f5b-4b9a-82c8-73056e149b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lobipanel-parent']/div/div/div[2]/div/div/div[4]/input</value>
      <webElementGuid>781d560b-d5f4-4665-94e9-4bf1c94327c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div[2]/div/div/div[4]/input</value>
      <webElementGuid>30d86d60-046c-4fd9-97d1-f2e580ebc74a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtsuffix']</value>
      <webElementGuid>e055cea6-ade6-427e-8e96-2dc5dd3cc376</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
