<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Web Sub Category_btnTealsave</name>
   <tag></tag>
   <elementGuidId>8afa1cfd-d79c-484d-8d63-cab82441b1b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnTealsave</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnTealsave']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>187a5fe9-e9f7-404f-84c7-364794c9c1f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e8779969-7708-4654-899a-eeaa56d57ab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>72b9947e-dcdc-4123-bb4f-544931c00c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>6d51cca3-8780-4513-938c-29c8c3911db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnTealsave</value>
      <webElementGuid>26dd80a7-cc7f-49dd-9c3c-8d73d1219a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return process('Part')</value>
      <webElementGuid>b70ae30b-6e71-41bd-a781-b91594c3f34b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnTealsave&quot;)</value>
      <webElementGuid>4bfd2efa-709e-4c79-9d94-c2b831d0a0a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnTealsave']</value>
      <webElementGuid>d3a44a6f-ba8b-4bb0-9745-b5bf8a5b6cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lobipanel-parent']/div/div/div[2]/div/div/div[9]/input</value>
      <webElementGuid>0c7ff79b-bcc1-4963-b160-2283039def64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/input</value>
      <webElementGuid>8d413a82-6d86-44cc-a361-12c72ed57575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnTealsave']</value>
      <webElementGuid>b9fad7b7-ede8-441e-9e2c-a1d2f533bbbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
