<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__drpTealproductsubcategory</name>
   <tag></tag>
   <elementGuidId>b7295d85-86f8-4f1c-90d3-3bc9d2a40ffa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drpTealproductsubcategory</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='drpTealproductsubcategory']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3c35d955-043a-41ce-9226-0245f934c1c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drpTealproductsubcategory</value>
      <webElementGuid>843e189d-5b6c-49be-bf74-9eb92282c3e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_select</value>
      <webElementGuid>55d5a1f6-9fa7-4690-9973-6032c6b0fe47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-SELECT-Adhesives, Sealants and TapeBattery and Related ComponentsBrackets, Flanges and HangersCylinder Block ComponentsDecals and EmblemsElectrical ConnectorsExterior AccessoriesFood and DrinkHardware, Fasteners and FittingsInformation LabelsInterior AccessoriesLighting - ExteriorLighting - InteriorMiscellaneous MerchandisePowersport AccessoriesRV and Marine AccessoriesSafety Equipment, Tools and AccessoriesShop Equipment, Tools and AccessoriesSignageStorage and OrganizationSwitches, Solenoids and ActuatorsTow, Hoist and Lift Tools and AccessoriesUnderhoodUnderhood AccessoriesWheel</value>
      <webElementGuid>df17ba93-dac4-402c-9fa4-bebd7b6c3711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drpTealproductsubcategory&quot;)</value>
      <webElementGuid>3a160e5f-dd15-4e3b-aa8e-06d6a9b2e589</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='drpTealproductsubcategory']</value>
      <webElementGuid>ced1f48c-d60c-408d-a71a-abc45aab05ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lobipanel-parent']/div/div/div[2]/div/div/div/div[3]/select</value>
      <webElementGuid>839debc6-a9fd-41e7-a3fc-8528a790e0c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[10]/following::select[1]</value>
      <webElementGuid>97ccdb3e-cac0-4787-928c-a324fc28c8c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/preceding::select[1]</value>
      <webElementGuid>3416608e-229d-4a15-93c2-b416f3ff3c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>e79f7deb-666e-4c47-bf4a-1e624e9ea9a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'drpTealproductsubcategory' and (text() = '-SELECT-Adhesives, Sealants and TapeBattery and Related ComponentsBrackets, Flanges and HangersCylinder Block ComponentsDecals and EmblemsElectrical ConnectorsExterior AccessoriesFood and DrinkHardware, Fasteners and FittingsInformation LabelsInterior AccessoriesLighting - ExteriorLighting - InteriorMiscellaneous MerchandisePowersport AccessoriesRV and Marine AccessoriesSafety Equipment, Tools and AccessoriesShop Equipment, Tools and AccessoriesSignageStorage and OrganizationSwitches, Solenoids and ActuatorsTow, Hoist and Lift Tools and AccessoriesUnderhoodUnderhood AccessoriesWheel' or . = '-SELECT-Adhesives, Sealants and TapeBattery and Related ComponentsBrackets, Flanges and HangersCylinder Block ComponentsDecals and EmblemsElectrical ConnectorsExterior AccessoriesFood and DrinkHardware, Fasteners and FittingsInformation LabelsInterior AccessoriesLighting - ExteriorLighting - InteriorMiscellaneous MerchandisePowersport AccessoriesRV and Marine AccessoriesSafety Equipment, Tools and AccessoriesShop Equipment, Tools and AccessoriesSignageStorage and OrganizationSwitches, Solenoids and ActuatorsTow, Hoist and Lift Tools and AccessoriesUnderhoodUnderhood AccessoriesWheel')]</value>
      <webElementGuid>9bd81fe0-02ee-4667-938d-9258d6be10c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
