<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Web Category_drpTealwebcategory</name>
   <tag></tag>
   <elementGuidId>bd3da915-18b4-4827-936e-6d1f62e49fbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drpTealwebcategory</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='drpTealwebcategory']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1453f2ab-1c79-4c69-b661-88971cac86ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_select</value>
      <webElementGuid>68a7054c-dfd3-4b7f-9308-e438514b0ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drpTealwebcategory</value>
      <webElementGuid>48955a40-abe4-4922-bec3-874bc953ccbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-SELECT--test-test-0AccessoriesAccessories and FluidsAces CategoryAir and Fuel DeliveryBelts and CoolingBodyBrakeDriveline and AxlesElectrical, Charging and StartingElectrical, Lighting and BodyEmission ControlEngineEntertainment and TelematicsExhaustHardware and Service SuppliesHousehold and Office ProductsHousehold, Shop and Office ProductsHVACIgnitionMultifunction TermsOil, Fluids and ChemicalsPlumbingRole CategoreySteeringSuspensionTestTest-categoryTest1TestentryTire and WheelTools and EquipmentTools, Equipment and SuppliesTransfer CaseTransmissionVehicles, Equipment, Tools, and SuppliesWiper and Washer</value>
      <webElementGuid>f25c5036-ef0d-4426-87f8-d5a04336c00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drpTealwebcategory&quot;)</value>
      <webElementGuid>1d1ea268-f159-4f97-901f-7509cd0a982f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='drpTealwebcategory']</value>
      <webElementGuid>8e3477c8-41df-439e-82ff-96aa503c96a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lobipanel-parent']/div/div/div[2]/div/div/div[6]/select</value>
      <webElementGuid>e86fa447-fda0-4234-9aba-220e8c1e33d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Web Category'])[2]/following::select[1]</value>
      <webElementGuid>10ae1394-d4ec-411a-b392-e0bbeeb6ee6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[15]/following::select[2]</value>
      <webElementGuid>978cc33d-3caf-41aa-8369-3f8a481f0c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Web Sub Category'])[1]/preceding::select[1]</value>
      <webElementGuid>7a41c601-947f-4492-8924-bcf90a16c9dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::select[2]</value>
      <webElementGuid>a248ae6e-e905-403e-8aed-d94ffd554a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/select</value>
      <webElementGuid>84fef2ae-604b-440c-8f2c-e1d7ac817207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'drpTealwebcategory' and (text() = '-SELECT--test-test-0AccessoriesAccessories and FluidsAces CategoryAir and Fuel DeliveryBelts and CoolingBodyBrakeDriveline and AxlesElectrical, Charging and StartingElectrical, Lighting and BodyEmission ControlEngineEntertainment and TelematicsExhaustHardware and Service SuppliesHousehold and Office ProductsHousehold, Shop and Office ProductsHVACIgnitionMultifunction TermsOil, Fluids and ChemicalsPlumbingRole CategoreySteeringSuspensionTestTest-categoryTest1TestentryTire and WheelTools and EquipmentTools, Equipment and SuppliesTransfer CaseTransmissionVehicles, Equipment, Tools, and SuppliesWiper and Washer' or . = '-SELECT--test-test-0AccessoriesAccessories and FluidsAces CategoryAir and Fuel DeliveryBelts and CoolingBodyBrakeDriveline and AxlesElectrical, Charging and StartingElectrical, Lighting and BodyEmission ControlEngineEntertainment and TelematicsExhaustHardware and Service SuppliesHousehold and Office ProductsHousehold, Shop and Office ProductsHVACIgnitionMultifunction TermsOil, Fluids and ChemicalsPlumbingRole CategoreySteeringSuspensionTestTest-categoryTest1TestentryTire and WheelTools and EquipmentTools, Equipment and SuppliesTransfer CaseTransmissionVehicles, Equipment, Tools, and SuppliesWiper and Washer')]</value>
      <webElementGuid>9bbe3cb3-751d-43db-858f-7964a5658608</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
