<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__drpTealProductCategory</name>
   <tag></tag>
   <elementGuidId>cdfc7eec-e572-4fa1-9065-4ffc426bf2f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drpTealProductCategory</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='drpTealProductCategory']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b4e64d34-303d-459e-a531-5534aadbc8df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drpTealProductCategory</value>
      <webElementGuid>90542804-6c44-4e23-9544-ed57415c9edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_select</value>
      <webElementGuid>64244f7a-f0b4-4397-9517-dc5a6302a130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                -SELECT-
                                            AccessoriesAir and Fuel DeliveryBelts and CoolingBodyBrakeDriveline and AxlesElectrical, Charging and StartingElectrical, Lighting and BodyEmission ControlEngineEntertainment and TelematicsExhaustHardware and Service SuppliesHousehold, Shop and Office ProductsHVACIgnitionMultifunction TermsOil, Fluids and ChemicalsPlumbingRole CategoreySteeringSuspensionTire and WheelTransfer CaseTransmissionVehicles, Equipment, Tools, and SuppliesWiper and Washer</value>
      <webElementGuid>15c891c2-fce1-46b1-a366-34ef4cbf87c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drpTealProductCategory&quot;)</value>
      <webElementGuid>8fe06205-6d1c-48dd-bb90-85ca585f3ceb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='drpTealProductCategory']</value>
      <webElementGuid>be0436a1-8ea1-4fca-a4d7-7ab29fa2aaff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lobipanel-parent']/div/div/div[2]/div/div/div/div[2]/select</value>
      <webElementGuid>43c3224e-d08f-43b5-a985-771eeeb46080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/following::select[1]</value>
      <webElementGuid>ccc54fb0-ab25-4e88-ac5a-0d4c12ea89c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[10]/preceding::select[1]</value>
      <webElementGuid>de25d462-d0eb-46cd-ac32-692f2258869d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/select</value>
      <webElementGuid>b37d4281-3b2b-4d47-ac82-04b6645233d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'drpTealProductCategory' and (text() = '
                                                -SELECT-
                                            AccessoriesAir and Fuel DeliveryBelts and CoolingBodyBrakeDriveline and AxlesElectrical, Charging and StartingElectrical, Lighting and BodyEmission ControlEngineEntertainment and TelematicsExhaustHardware and Service SuppliesHousehold, Shop and Office ProductsHVACIgnitionMultifunction TermsOil, Fluids and ChemicalsPlumbingRole CategoreySteeringSuspensionTire and WheelTransfer CaseTransmissionVehicles, Equipment, Tools, and SuppliesWiper and Washer' or . = '
                                                -SELECT-
                                            AccessoriesAir and Fuel DeliveryBelts and CoolingBodyBrakeDriveline and AxlesElectrical, Charging and StartingElectrical, Lighting and BodyEmission ControlEngineEntertainment and TelematicsExhaustHardware and Service SuppliesHousehold, Shop and Office ProductsHVACIgnitionMultifunction TermsOil, Fluids and ChemicalsPlumbingRole CategoreySteeringSuspensionTire and WheelTransfer CaseTransmissionVehicles, Equipment, Tools, and SuppliesWiper and Washer')]</value>
      <webElementGuid>f2e72211-1804-47af-a71b-8e9f4786a529</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
