<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>5a78cc74-8ba4-474a-8fd5-2923e64eb430</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;delete&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[3]/div/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;delete&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>206cb197-54a7-42d9-aa59-9720b45cff4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//bddemo.apapmt.com/Images/New_design_img/delete_icon.png</value>
      <webElementGuid>c204a172-b77d-4c6b-8f13-cd36d0ebdc5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>delete</value>
      <webElementGuid>4ad3d804-69fb-4f6a-8715-3bb960580430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divdeletebtn_'Testing_Automations'&quot;)/img[1]</value>
      <webElementGuid>6106f284-294f-4b4d-8b56-fedc92568289</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=&quot;divdeletebtn_'Testing_Automations'&quot;]/img</value>
      <webElementGuid>f5f3fa6c-4471-460f-b612-e84fa7dda4d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='delete']</value>
      <webElementGuid>dc07393f-a38b-4809-96c4-e185165b7cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div[2]/img</value>
      <webElementGuid>f7e44da5-b8b8-40db-8eb2-a0df8e1a38b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//bddemo.apapmt.com/Images/New_design_img/delete_icon.png' and @alt = 'delete']</value>
      <webElementGuid>82b97ba6-b534-43d7-bf4b-a16ede95b44e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
