<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No-Override_glowing-border</name>
   <tag></tag>
   <elementGuidId>b391a177-ee23-4dbe-9883-a043eed0d64f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'text' and @placeholder = 'Description']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th:nth-of-type(3) > input.glowing-border</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Description&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>abcdcf95-38a4-48ed-afe0-2af68bce5a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glowing-border</value>
      <webElementGuid>55e283b3-3394-47e9-9886-630603121aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>315a4720-719b-4088-98de-5cd753da9753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>0717f3f6-2f39-41bb-aaa2-1e8f338ff504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTableViewer&quot;)/tfoot[1]/tr[1]/th[3]/input[@class=&quot;glowing-border&quot;]</value>
      <webElementGuid>bfb4c178-5a00-4e1f-aa6d-b59d798dedf1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[31]</value>
      <webElementGuid>ed031e83-ab32-4eb3-89b2-0bb8615252a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTableViewer']/tfoot/tr/th[3]/input</value>
      <webElementGuid>96218103-e4c1-4b72-b25b-df087299edd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/input</value>
      <webElementGuid>3315bce6-a30b-4bca-85db-4e2aca2a35ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Description']</value>
      <webElementGuid>51308d0b-2093-46a4-bbf0-c27593b9a6d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
