<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Enter Long Description (DES) first_d_7e7635</name>
   <tag></tag>
   <elementGuidId>9fbd59cb-17be-4623-9251-4dd6e5d14442</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drpNotesType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='drpNotesType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#drpNotesType</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>547bc926-6f24-4190-b97a-47ad5bb2f369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_select</value>
      <webElementGuid>7b536dac-da8c-4b74-be83-e24cc0a8caac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drpNotesType</value>
      <webElementGuid>4fd7eb5b-9aaa-469d-9159-fcdc775e0eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;--Select-->Amazon Product Description - 4000(AMD)Amazon Title - 200(AMZ)BIGC Product Description - 4000(BGD)BigCommerce Title - 250(BIG)Brand Description - 240(BRD)Catalog Description - 2000(CAT)Custom description - 5000(CUS)Custom Description1 - 2000(CT1)Custom Description2 - 2000(CT2)Custom Description3 - 2000(CT3)Disclaimer Description - 2000(DIS)eBay Title - 80(EBY)Ecom Detail Description 1 - 4000(ED1)Ecom Detail Description 2 - 4000(ED2)Ecom Detail Description 3 - 4000(ED3)Ecom Long Description - 4000(ELD)Ecom Title - 500(ETE)Exceptions - 2000(EXP)Installation Note - 500(INS)Magento Title - 80(MAG)Walmart Title - 80(WAL)</value>
      <webElementGuid>c160d32c-b497-4a2d-ba04-3f161c651b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drpNotesType&quot;)</value>
      <webElementGuid>f1ec3844-214f-4c31-9368-fa0f0f21e81b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='drpNotesType']</value>
      <webElementGuid>d8bd517f-988a-45bf-9123-b4a383b13858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='piespages']/div[2]/div[2]/div[3]/div[2]/select</value>
      <webElementGuid>1febf182-73fd-4087-90be-ab92ac4d917c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter Long Description (DES) first'])[1]/following::select[1]</value>
      <webElementGuid>2a20c9e8-8540-4a43-9fa3-22adf9a49fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::select[1]</value>
      <webElementGuid>70f44846-c7e8-40a0-a288-08462a7b11f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description Sequence'])[1]/preceding::select[1]</value>
      <webElementGuid>34ff750b-321e-4d9f-afdb-9b47cb8c2cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language (Code)'])[1]/preceding::select[1]</value>
      <webElementGuid>3fa6be23-d8cb-4cb8-841c-b35d41d8bdaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>12dc3699-eb54-4a6e-bc6d-1d3e3d2f72df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'drpNotesType' and (text() = '&lt;--Select-->Amazon Product Description - 4000(AMD)Amazon Title - 200(AMZ)BIGC Product Description - 4000(BGD)BigCommerce Title - 250(BIG)Brand Description - 240(BRD)Catalog Description - 2000(CAT)Custom description - 5000(CUS)Custom Description1 - 2000(CT1)Custom Description2 - 2000(CT2)Custom Description3 - 2000(CT3)Disclaimer Description - 2000(DIS)eBay Title - 80(EBY)Ecom Detail Description 1 - 4000(ED1)Ecom Detail Description 2 - 4000(ED2)Ecom Detail Description 3 - 4000(ED3)Ecom Long Description - 4000(ELD)Ecom Title - 500(ETE)Exceptions - 2000(EXP)Installation Note - 500(INS)Magento Title - 80(MAG)Walmart Title - 80(WAL)' or . = '&lt;--Select-->Amazon Product Description - 4000(AMD)Amazon Title - 200(AMZ)BIGC Product Description - 4000(BGD)BigCommerce Title - 250(BIG)Brand Description - 240(BRD)Catalog Description - 2000(CAT)Custom description - 5000(CUS)Custom Description1 - 2000(CT1)Custom Description2 - 2000(CT2)Custom Description3 - 2000(CT3)Disclaimer Description - 2000(DIS)eBay Title - 80(EBY)Ecom Detail Description 1 - 4000(ED1)Ecom Detail Description 2 - 4000(ED2)Ecom Detail Description 3 - 4000(ED3)Ecom Long Description - 4000(ELD)Ecom Title - 500(ETE)Exceptions - 2000(EXP)Installation Note - 500(INS)Magento Title - 80(MAG)Walmart Title - 80(WAL)')]</value>
      <webElementGuid>be6c8f50-6c7a-4cc4-808b-722843efc563</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
