<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search By_txtsearchpartno</name>
   <tag></tag>
   <elementGuidId>42205518-8123-4292-8391-acf085b5a026</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtsearchpartno</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtsearchpartno']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Enter your part number&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f4aa67e-4981-413a-bbaf-8fb3d5c7021e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4bec60c9-f192-47a3-aec2-a395d91c0d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtsearchpartno</value>
      <webElementGuid>b0d74729-3790-44b3-b655-8776e278c819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>7ca4a53e-3d5f-4f61-8445-177771ce6fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input</value>
      <webElementGuid>bac3a470-04df-4014-9780-69abc59dffcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>LoadSearchByPartNo(this)</value>
      <webElementGuid>fe76917a-9074-4451-a2ee-8631ae331a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>LoadCompNo(this)</value>
      <webElementGuid>7281d2cd-b4a2-49de-96a3-e50cc66a6abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your part number</value>
      <webElementGuid>f3d208ee-433e-46a1-884f-b179e7b886d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4d441b93-6c5b-47a7-a898-2c630878cc16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtsearchpartno&quot;)</value>
      <webElementGuid>faa42869-53c8-4738-9dc5-f802ec87a67d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtsearchpartno']</value>
      <webElementGuid>b96b9c6a-986f-4d3b-a812-ddf8d26bd1e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_upAttribute']/div[2]/div/div/div[3]/div/div[2]/input</value>
      <webElementGuid>87969e87-71ef-4691-8edd-7bded276d6b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/div[2]/input</value>
      <webElementGuid>3669c924-ed8e-40b5-83fd-ada6e9b8fcbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtsearchpartno' and @placeholder = 'Enter your part number']</value>
      <webElementGuid>9cb8e367-3ee0-4296-b8c0-92be754b3f29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
