<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Data Import_ucMenu_rptLevel1_rptLevel2_0__663825</name>
   <tag></tag>
   <elementGuidId>b9da0911-1ded-47b2-bff3-48cc142311e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucMenu_rptLevel1_rptLevel2_0_rptLevel3_3_lnkLink3_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Excel')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Excel&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5fc30f68-2dd2-47bc-91c8-dcf9adb27a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucMenu_rptLevel1_rptLevel2_0_rptLevel3_3_lnkLink3_0</value>
      <webElementGuid>5a0b4b14-c2ad-43a0-8579-e5f76100a33f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>DataImport.aspx?PageTitle=Excel</value>
      <webElementGuid>bafaffd8-4e98-41a6-9f7f-b38491d361a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Excel</value>
      <webElementGuid>3a2bcb72-900a-4f5f-abed-94d08e362851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucMenu_rptLevel1_rptLevel2_0_rptLevel3_3_lnkLink3_0&quot;)</value>
      <webElementGuid>45b65f79-e283-4bcb-9ad6-9b5c678c4bd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucMenu_rptLevel1_rptLevel2_0_rptLevel3_3_lnkLink3_0']</value>
      <webElementGuid>4aafac2a-d4ea-4477-8e06-ded7888002b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='ucMenu_rptLevel1_l1_0']/div/div/div[4]/div/a</value>
      <webElementGuid>8abc85ac-eece-43e3-bbf7-bc0ef68dcea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Excel')]</value>
      <webElementGuid>8f1b1266-7af7-4b8b-99e0-cbeaf8663387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Import'])[1]/following::a[1]</value>
      <webElementGuid>9768597f-b06d-44d2-97c9-e169fcc74020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interchange Part#'])[1]/following::a[2]</value>
      <webElementGuid>1b9e2498-f0b8-4bd1-8a63-b9a163cdea48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XML'])[1]/preceding::a[1]</value>
      <webElementGuid>f2894882-4abc-4b21-9268-12d9a15c31b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle'])[1]/preceding::a[2]</value>
      <webElementGuid>7fa4d284-b6c3-4d92-bea7-ec371b3390d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Excel']/parent::*</value>
      <webElementGuid>c1ef6e10-4b01-4832-b905-d90234948cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'DataImport.aspx?PageTitle=Excel')]</value>
      <webElementGuid>836005e2-6181-44a6-8c12-24dab7d6c671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div[4]/div/a</value>
      <webElementGuid>83c25abe-4e22-41ff-9f4a-5e119db20220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucMenu_rptLevel1_rptLevel2_0_rptLevel3_3_lnkLink3_0' and @href = 'DataImport.aspx?PageTitle=Excel' and (text() = 'Excel' or . = 'Excel')]</value>
      <webElementGuid>08e051d0-400f-494f-9f7d-41273adc11e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
