<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Upload my file_MainContent_FileUpload1</name>
   <tag></tag>
   <elementGuidId>40c14ba5-58cf-4909-a05d-d51e971c7c5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MainContent_FileUpload1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MainContent_FileUpload1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#MainContent_FileUpload1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69379a42-a26a-461a-b8df-a4ec50b45a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>3df354b2-3ae5-4a25-b116-9c2c4537ae72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$FileUpload1</value>
      <webElementGuid>cd13d945-035e-4877-bd2f-8e6cd22cc3d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainContent_FileUpload1</value>
      <webElementGuid>c16dbfaa-2fd2-466c-af53-4a5ee98c4fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Fileupload</value>
      <webElementGuid>28a92f22-ea05-427f-8193-750ca84fd0b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_FileUpload1&quot;)</value>
      <webElementGuid>b35810c2-42ef-4c14-9b72-f86d43fcf9b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MainContent_FileUpload1']</value>
      <webElementGuid>d72aec66-4b77-456a-b17e-8557d322495a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_panel_dataimport']/table[2]/tbody/tr/td[2]/input</value>
      <webElementGuid>4cc687c6-d50e-4e16-97fd-cd0fab03c815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>b13aba8c-d32e-476a-a78d-569ba89ff5b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'ctl00$MainContent$FileUpload1' and @id = 'MainContent_FileUpload1']</value>
      <webElementGuid>4a23c3f0-e622-46fa-9d11-a02e8e58e91a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
