<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_If you have more than 1,048,576 rows_517df0</name>
   <tag></tag>
   <elementGuidId>7559437d-f084-4108-882c-a7980df82cf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ExcelExport</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ExcelExport']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Generate Excel&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ee2d4e48-8188-4251-b47a-b003b45bfdf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ExcelExport</value>
      <webElementGuid>0ad646ac-8aa2-4d50-83bc-34957b28e4e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Exportbutton</value>
      <webElementGuid>2bd387f9-c2df-47e8-a993-12c832ced630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d735d774-22a5-44c7-b259-036b68885211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>getExcel()</value>
      <webElementGuid>f95eea67-0710-4f83-9fab-a3c0466b6429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generate Excel</value>
      <webElementGuid>5219854c-1f18-4335-8938-6db148d06aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExcelExport&quot;)</value>
      <webElementGuid>06221239-e93f-434d-aebc-3f9199646b91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ExcelExport']</value>
      <webElementGuid>2168cad4-deb8-4cb2-a9a9-d7ca0648d89a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Bottomdata']/div[3]/button</value>
      <webElementGuid>c8c19ca1-1ccb-4110-987e-17fe25b6587b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='If you have more than 1,048,576 rows, use CSV to export.'])[1]/following::button[1]</value>
      <webElementGuid>4181d38d-37f7-4146-8842-0e00735a2bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable this field to exclude the overlapping records in the export you want to generate'])[1]/following::button[1]</value>
      <webElementGuid>4fec978e-d4c8-4931-8f9b-ab85744be067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate CSV'])[1]/preceding::button[1]</value>
      <webElementGuid>33d650cc-4be0-4e63-9cf7-1833fe784e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate XML'])[1]/preceding::button[7]</value>
      <webElementGuid>132d2a6f-1fa3-4c7a-b9d1-6deebd1cde17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Generate Excel']/parent::*</value>
      <webElementGuid>75111591-b442-4ec8-8880-f7035868ef8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>66072f12-a5f3-402c-b538-016e145b4aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ExcelExport' and @type = 'button' and (text() = 'Generate Excel' or . = 'Generate Excel')]</value>
      <webElementGuid>6ab2aad5-e98d-4b45-97f8-dbf8f64c3fea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
