<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Brand_txtbrandmasterid</name>
   <tag></tag>
   <elementGuidId>2067f37b-6111-4435-967b-4b59023fdee9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtbrandmasterid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtbrandmasterid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter Brand Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d98f382-8bbb-4fbd-934d-d76a30843d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7f81f6ed-e04e-42c8-982d-a76675212f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtbrandmasterid</value>
      <webElementGuid>738ae81f-a43e-4ac6-92b5-fc54a9623cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input field_input</value>
      <webElementGuid>ce8153a6-9f7b-4c85-8476-0840db45e320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Brand Name</value>
      <webElementGuid>e541cc6c-741d-4c31-9509-11d3071759fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>CheckBrandValue()</value>
      <webElementGuid>fc5a6c8d-f30c-4920-8297-9cd8980c2e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>PartBrandName(this); PartnoValidate(this)</value>
      <webElementGuid>4ca3ebc5-440b-46a1-8b2d-f63507fd3c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1d64c1b9-3169-4df5-ab96-3435022d001e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtbrandmasterid&quot;)</value>
      <webElementGuid>99f55c60-0d7f-4918-b6a3-18b4f183fa93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtbrandmasterid']</value>
      <webElementGuid>4f0a9f6d-a793-4caa-a55c-bd9ef33b039f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divData']/table/tbody/tr/td/table/tbody/tr[11]/td[4]/input</value>
      <webElementGuid>970694c1-fd30-4be1-8fc9-c74b0c13da8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[11]/td[4]/input</value>
      <webElementGuid>512c6a25-51e3-4fd7-af2a-8386b88d6cb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtbrandmasterid' and @placeholder = 'Enter Brand Name']</value>
      <webElementGuid>31ca8087-102c-4914-a863-5d10f9aa9d64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
