<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UNSPSC Code_MainContent_txtvnspsc</name>
   <tag></tag>
   <elementGuidId>29c7eaa7-ed1e-47df-915b-9834c4d2b04f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MainContent_txtvnspsc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MainContent_txtvnspsc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#MainContent_txtvnspsc</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b8eac898-558a-4771-b512-7a99cb628219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$txtvnspsc</value>
      <webElementGuid>b90136a0-f1ad-4357-bcbf-b152daae56d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4de55755-67e8-42eb-a512-f4cd502268bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>ab4f5f07-539c-454e-976f-eacc48425a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainContent_txtvnspsc</value>
      <webElementGuid>25e195ac-b37f-4ca2-92ba-a151d3879bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return NoDecimal(event)</value>
      <webElementGuid>ecaa4f4a-eeb0-4811-98b4-36b7442d25f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>onlyNum(this)</value>
      <webElementGuid>3a899377-15dd-454b-9df5-32e5cc6fe8d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_txtvnspsc&quot;)</value>
      <webElementGuid>989695cd-0994-4834-8924-eff72b79475c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MainContent_txtvnspsc']</value>
      <webElementGuid>d7237af6-7571-455a-8726-a6903c8c546c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divData']/table/tbody/tr/td/table/tbody/tr[12]/td[2]/input</value>
      <webElementGuid>bf488a8f-0579-427f-bee3-bac0d9c35966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[12]/td[2]/input</value>
      <webElementGuid>d60596c8-f903-4ff2-9503-956fa30f64de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$MainContent$txtvnspsc' and @type = 'text' and @id = 'MainContent_txtvnspsc']</value>
      <webElementGuid>eaf1c2da-61c2-47c1-91b3-50981ce96760</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
