<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Qty Qualifier_drpQtyQualifier</name>
   <tag></tag>
   <elementGuidId>6b7e1962-1f40-4e94-8fd4-67d845d76a7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drpQtyQualifier</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='drpQtyQualifier']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#drpQtyQualifier</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>adaf7087-8ce4-42cf-adf9-83d50df265b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drpQtyQualifier</value>
      <webElementGuid>f8068678-0969-48de-b4be-29e5d70c53ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-SELECT-As Required-REQMaximum Used in any Vehicle-MAXMinimum Quantity Used in a Vehicle-MINNormal Quantity Used in a Vehicle-NORNot Applicable to Vehicles-NOTUser Defined-ZZ1User Defined-ZZ2User Defined-ZZ3User Defined-ZZ4User Defined-ZZ5User Defined-ZZ6User Defined-ZZ7User Defined-ZZ8User Defined-ZZ9Variable - See ACES Application Field V91-VAR</value>
      <webElementGuid>a2e91932-dd00-447f-bb86-87bcb6bad17f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drpQtyQualifier&quot;)</value>
      <webElementGuid>80a1f013-8307-4fa8-85bd-d37a580a8296</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='drpQtyQualifier']</value>
      <webElementGuid>ad301cc5-c87e-4003-8dce-a0fbfedc2b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divData']/table/tbody/tr/td/table/tbody/tr[4]/td[4]/select</value>
      <webElementGuid>6f371409-bee4-47c9-8b6d-cc33f53d7cb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty Qualifier'])[1]/following::select[1]</value>
      <webElementGuid>3bce8507-9d4a-4732-9758-254eefbe5891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[2]</value>
      <webElementGuid>9da1b3cd-abce-4f55-950f-7f9aae0f59ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Line'])[2]/preceding::select[1]</value>
      <webElementGuid>ff8bfad2-8544-48f1-b382-f881ff47f7b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/preceding::select[1]</value>
      <webElementGuid>b5d971d0-8ec6-4c26-b641-d9ba68568b3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[4]/select</value>
      <webElementGuid>934cf600-2f25-43d0-8d76-4992eb27fcfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'drpQtyQualifier' and (text() = '-SELECT-As Required-REQMaximum Used in any Vehicle-MAXMinimum Quantity Used in a Vehicle-MINNormal Quantity Used in a Vehicle-NORNot Applicable to Vehicles-NOTUser Defined-ZZ1User Defined-ZZ2User Defined-ZZ3User Defined-ZZ4User Defined-ZZ5User Defined-ZZ6User Defined-ZZ7User Defined-ZZ8User Defined-ZZ9Variable - See ACES Application Field V91-VAR' or . = '-SELECT-As Required-REQMaximum Used in any Vehicle-MAXMinimum Quantity Used in a Vehicle-MINNormal Quantity Used in a Vehicle-NORNot Applicable to Vehicles-NOTUser Defined-ZZ1User Defined-ZZ2User Defined-ZZ3User Defined-ZZ4User Defined-ZZ5User Defined-ZZ6User Defined-ZZ7User Defined-ZZ8User Defined-ZZ9Variable - See ACES Application Field V91-VAR')]</value>
      <webElementGuid>48ca5a8f-6c8a-4c30-9a5c-2e4bc73489b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
