<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Recommended_drpMinQtyUOM</name>
   <tag></tag>
   <elementGuidId>3e432501-af83-4736-8539-acdc479b68e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drpMinQtyUOM</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='drpMinQtyUOM']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Status Min Qty UOM  Recommended . If this is filled up, Minimum Order Quantity also need to be provided.&quot;s] >> internal:role=combobox >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>428e4400-d731-4351-8b97-655fa4e897a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drpMinQtyUOM</value>
      <webElementGuid>6496b72c-ef28-4b2b-ab03-a856e5268842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-SELECT-AssortmentBagBookBottleBoxBucketBundleCanCardCartonCartridgeCaseClamshellCoilContainerCrateDozenDrumEachEnvelopeFootGallonHundredHundred CountJarKegKilogramKitLiterMeterPack (PAK)PackagePailPairPalletPallet Unit LoadPiecePintPoundQuartReelRodRollSetSheetSleeveSpoolStickThousandTrayTubeTwo Pack</value>
      <webElementGuid>c9239d99-d2ab-48f7-bf81-3635d8bc7bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drpMinQtyUOM&quot;)</value>
      <webElementGuid>a10b0ddf-3eee-409e-ad65-65feef273146</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='drpMinQtyUOM']</value>
      <webElementGuid>60303909-4134-4009-bf3a-31a9292463c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divData']/table/tbody/tr/td/table/tbody/tr[8]/td[4]/select</value>
      <webElementGuid>a4b030b7-2263-44be-8b3d-950cab2ffa45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recommended .'])[1]/following::select[1]</value>
      <webElementGuid>eb3e43b8-065c-4d80-b5ff-be3cb137324e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Effective Date'])[1]/preceding::select[1]</value>
      <webElementGuid>f5f0ef90-24a6-43f3-8849-b4719d75554e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inventory'])[1]/preceding::select[1]</value>
      <webElementGuid>7355176b-0f09-4017-8de2-44e4f561dbee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[4]/select</value>
      <webElementGuid>d171475f-3f36-4d33-93bf-9eaf38e68c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'drpMinQtyUOM' and (text() = '-SELECT-AssortmentBagBookBottleBoxBucketBundleCanCardCartonCartridgeCaseClamshellCoilContainerCrateDozenDrumEachEnvelopeFootGallonHundredHundred CountJarKegKilogramKitLiterMeterPack (PAK)PackagePailPairPalletPallet Unit LoadPiecePintPoundQuartReelRodRollSetSheetSleeveSpoolStickThousandTrayTubeTwo Pack' or . = '-SELECT-AssortmentBagBookBottleBoxBucketBundleCanCardCartonCartridgeCaseClamshellCoilContainerCrateDozenDrumEachEnvelopeFootGallonHundredHundred CountJarKegKilogramKitLiterMeterPack (PAK)PackagePailPairPalletPallet Unit LoadPiecePintPoundQuartReelRodRollSetSheetSleeveSpoolStickThousandTrayTubeTwo Pack')]</value>
      <webElementGuid>ba480e70-7b4b-4924-8650-34ba2ce38fa9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
